// Copyright 2026 Nessprim Karol Kozer
// SPDX-License-Identifier: Apache-2.0
import type { Lang, Table } from '../../report-copy.ts';

/**
 * The words the UI kit writes, whatever page it is on: the sidebar, the looks, the file chips, folding. In the
 * glossary of `.ai/design/2026-09-23-design-guidelines.md` §7 - *private*, *read*, *helper*, *stopped* - and read
 * through the one `translator` every page uses.
 */
export const APP_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'app.project': 'Your project',
    'app.shared': 'A shared page',
    'app.nav': 'Pages',
    'app.nav.conversations': 'Conversations',
    'app.nav.toFix': 'To fix',
    'app.nav.month': 'This month',
    'app.nav.settings': 'Settings',
    'app.local': 'Runs on your computer. Nothing is uploaded.',
    'app.lang': 'Language',
    'look.read': 'Read private files',
    'look.fixed': 'Read, now fixed',
    'look.allowed': 'Read — tracked',
    'look.name': 'Only saw a name',
    'look.stopped': 'Stopped',
    'look.none': 'Nothing private',
    'look.unchecked': 'Couldn’t check fully',
    'look.failed': 'Couldn’t be read',
    'look.outside': 'Not checked yet',
    'chip.more': '+{n} more',
    'chip.less': 'Show less',
    'fold.show': 'Show',
    'fold.hide': 'Hide',
    'app.close': 'Close',
    'app.cancel': 'Cancel',
    'upd.title': 'A new version of agentwhy is ready',
    'upd.sentence': 'This project still uses {from}. agentwhy never updates by itself, so nothing changes until you say so.',
    'upd.sentence.shared': 'Everyone who works on this project still uses {from}. agentwhy never updates by itself, so nothing changes until you say so.',
    'upd.update': 'Update to {to}',
    'upd.later': 'Not now',
    'upd.saving': 'Updating…',
    'upd.refused': 'Not updated.',
    'upd.unreachable': 'agentwhy could not be reached, so nothing changed.',
    'upd.command': 'To update, run this in your project:',
    'upd.copy': 'Copy',
    'upd.copied': 'Copied',
    'upd.done': 'Updated. Your AI’s next reply is checked by {to}.',
    'upd.confirm.title': 'Update agentwhy in this project?',
    'upd.confirm.sentence': 'Your AI’s next reply is checked by {to}. Nothing else in your settings changes.',
    'upd.confirm.sentence.shared': 'Your AI’s next reply is checked by {to}, for everyone on this project once they have your change. Nothing else in your settings changes.',
    'upd.confirm.do': 'Update',
    'live.new.one': '1 new conversation ↑',
    'live.new.other': '{n} new conversations ↑',
    'live.updated': 'Updated · Show',
    'live.go.one': '1 new conversation · Show',
    'live.go.other': '{n} new conversations · Show',
    // which-project V14: a switch in another tab ends this page's run as Ctrl+C does, and the page cannot tell which.
    'live.stopped': 'agentwhy stopped showing this project here: its pages were closed for a while, or another tab switched project. To open it again, ask your AI: “open agentwhy’s report” - or type npx @agentwhy/cli in a terminal.',
    'app.stuck': '✦ I\u2019m stuck',
    'app.tick': 'Mark as done',
    'app.ticked': 'Done',
  },
  pl: {
    'app.project': 'Twój projekt',
    'app.shared': 'Udostępniona strona',
    'app.nav': 'Strony',
    'app.nav.conversations': 'Rozmowy',
    'app.nav.toFix': 'Do naprawy',
    'app.nav.month': 'Ten miesiąc',
    'app.nav.settings': 'Ustawienia',
    'app.local': 'Działa na twoim komputerze. Nic nie jest wysyłane.',
    'app.lang': 'Język',
    'look.read': 'Przeczytało prywatne pliki',
    'look.fixed': 'Przeczytało, już naprawione',
    'look.allowed': 'Przeczytało — obserwowane',
    'look.name': 'Widziało tylko nazwę',
    'look.stopped': 'Zatrzymane',
    'look.none': 'Nic prywatnego',
    'look.unchecked': 'Nie w pełni sprawdzone',
    'look.failed': 'Nie dało się odczytać',
    'look.outside': 'Jeszcze nie sprawdzona',
    'chip.more': '+{n} więcej',
    'chip.less': 'Pokaż mniej',
    'fold.show': 'Pokaż',
    'fold.hide': 'Ukryj',
    'app.close': 'Zamknij',
    'app.cancel': 'Anuluj',
    'upd.title': 'Nowa wersja agentwhy jest gotowa',
    'upd.sentence': 'Ten projekt nadal używa wersji {from}. agentwhy nigdy nie aktualizuje się samo, więc nic się nie zmieni, dopóki nie zdecydujesz.',
    'upd.sentence.shared': 'Wszyscy, którzy pracują nad tym projektem, nadal używają wersji {from}. agentwhy nigdy nie aktualizuje się samo, więc nic się nie zmieni, dopóki nie zdecydujesz.',
    'upd.update': 'Zaktualizuj do {to}',
    'upd.later': 'Nie teraz',
    'upd.saving': 'Aktualizuję…',
    'upd.refused': 'Nie zaktualizowano.',
    'upd.unreachable': 'Nie udało się połączyć z agentwhy, więc nic się nie zmieniło.',
    'upd.command': 'Aby zaktualizować, uruchom w projekcie:',
    'upd.copy': 'Kopiuj',
    'upd.copied': 'Skopiowano',
    'upd.done': 'Zaktualizowano. Następną odpowiedź twojego AI sprawdzi wersja {to}.',
    'upd.confirm.title': 'Zaktualizować agentwhy w tym projekcie?',
    'upd.confirm.sentence': 'Następną odpowiedź twojego AI sprawdzi wersja {to}. Nic innego w ustawieniach się nie zmieni.',
    'upd.confirm.sentence.shared': 'Następną odpowiedź AI sprawdzi wersja {to} u wszystkich w tym projekcie, gdy dostaną twoją zmianę. Nic innego w ustawieniach się nie zmieni.',
    'upd.confirm.do': 'Zaktualizuj',
    'live.new.one': '1 nowa rozmowa ↑',
    'live.new.few': '{n} nowe rozmowy ↑',
    'live.new.many': '{n} nowych rozmów ↑',
    'live.updated': 'Zaktualizowano · Pokaż',
    'live.go.one': '1 nowa rozmowa · Pokaż',
    'live.go.few': '{n} nowe rozmowy · Pokaż',
    'live.go.many': '{n} nowych rozmów · Pokaż',
    'live.stopped': 'agentwhy przestał tu pokazywać ten projekt: jego strony były przez chwilę zamknięte albo w innej karcie przełączono projekt. Żeby otworzyć go ponownie, napisz do AI: „otwórz raport agentwhy” - albo wpisz npx @agentwhy/cli w terminalu.',
    'app.stuck': '✦ Utknąłem',
    'app.tick': 'Oznacz jako zrobione',
    'app.ticked': 'Zrobione',
  },
  de: {
    'app.project': 'Dein Projekt',
    'app.shared': 'Eine geteilte Seite',
    'app.nav': 'Seiten',
    'app.nav.conversations': 'Unterhaltungen',
    'app.nav.toFix': 'Zu beheben',
    'app.nav.month': 'Dieser Monat',
    'app.nav.settings': 'Einstellungen',
    'app.local': 'Läuft auf deinem Computer. Nichts wird hochgeladen.',
    'app.lang': 'Sprache',
    'look.read': 'Private Dateien gelesen',
    'look.fixed': 'Gelesen, schon behoben',
    'look.allowed': 'Gelesen — beobachtet',
    'look.name': 'Nur einen Namen gesehen',
    'look.stopped': 'Gestoppt',
    'look.none': 'Nichts Privates',
    'look.unchecked': 'Nicht ganz geprüft',
    'look.failed': 'Nicht lesbar',
    'look.outside': 'Noch nicht geprüft',
    'chip.more': '+{n} weitere',
    'chip.less': 'Weniger zeigen',
    'fold.show': 'Zeigen',
    'fold.hide': 'Ausblenden',
    'app.close': 'Schließen',
    'app.cancel': 'Abbrechen',
    'upd.title': 'Eine neue Version von agentwhy ist bereit',
    'upd.sentence': 'Dieses Projekt nutzt noch {from}. agentwhy aktualisiert sich nie von selbst, also ändert sich nichts, bis du es sagst.',
    'upd.sentence.shared': 'Alle, die an diesem Projekt arbeiten, nutzen noch {from}. agentwhy aktualisiert sich nie von selbst, also ändert sich nichts, bis du es sagst.',
    'upd.update': 'Auf {to} aktualisieren',
    'upd.later': 'Nicht jetzt',
    'upd.saving': 'Wird aktualisiert …',
    'upd.refused': 'Nicht aktualisiert.',
    'upd.unreachable': 'agentwhy war nicht erreichbar, also hat sich nichts geändert.',
    'upd.command': 'Zum Aktualisieren führe das in deinem Projekt aus:',
    'upd.copy': 'Kopieren',
    'upd.copied': 'Kopiert',
    'upd.done': 'Aktualisiert. Die nächste Antwort deiner KI prüft {to}.',
    'upd.confirm.title': 'agentwhy in diesem Projekt aktualisieren?',
    'upd.confirm.sentence': 'Die nächste Antwort deiner KI prüft {to}. Sonst ändert sich nichts an deinen Einstellungen.',
    'upd.confirm.sentence.shared': 'Die nächste Antwort der KI prüft {to}, für alle in diesem Projekt, sobald sie deine Änderung haben. Sonst ändert sich nichts an deinen Einstellungen.',
    'upd.confirm.do': 'Aktualisieren',
    'live.new.one': '1 neue Unterhaltung ↑',
    'live.new.other': '{n} neue Unterhaltungen ↑',
    'live.updated': 'Aktualisiert · Anzeigen',
    'live.go.one': '1 neue Unterhaltung · Anzeigen',
    'live.go.other': '{n} neue Unterhaltungen · Anzeigen',
    'live.stopped': 'agentwhy zeigt dieses Projekt hier nicht mehr: Seine Seiten waren eine Weile geschlossen, oder ein anderer Tab hat das Projekt gewechselt. Um es wieder zu öffnen, schreib deiner KI: „öffne den Bericht von agentwhy“ - oder tippe npx @agentwhy/cli in ein Terminal.',
    'app.stuck': '✦ Ich komme nicht weiter',
    'app.tick': 'Als erledigt markieren',
    'app.ticked': 'Erledigt',
  },
};
