// Copyright 2026 Nessprim Karol Kozer
// SPDX-License-Identifier: Apache-2.0
import type { Lang, Table } from '../../report-copy.ts';

/**
 * What only the Conversations page says (`for-people-who-build-with-ai.md` F7-F17). Values arrive escaped: `{ask}`
 * is a session's title, already past the redactor and escaped by the page before it is put here.
 */
export const CONVERSATIONS_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'conv.title': 'Conversations · agentwhy',
    'conv.week.this': 'This week',
    'conv.week.last': 'Last week',
    'conv.week.ago': '{n} weeks ago',
    'conv.hero.fact.one': 'Your AI worked for you once.',
    'conv.hero.fact.other': 'Your AI worked for you {n} times.',
    'conv.hero.fact.zero': 'No conversations yet this week.',
    'conv.hero.none': 'Nothing private was read.',
    'conv.hero.times.one': 'Once it read something private.',
    'conv.hero.times.other': '{n} times it read something private.',
    'conv.hero.lead': 'Each time is one conversation with your AI. Most were fine. The ones marked in coral need a few minutes of your time.',
    'conv.day.today': 'Today',
    'conv.day.yesterday': 'Yesterday',
    'conv.guide.today': 'today',
    'conv.guide.yesterday': 'yesterday',
    'conv.guide.title': 'Start with {when}, {time}.',
    'conv.guide.asked': 'You asked: “{ask}”.',
    'conv.guide.read': 'Your AI read {what} along the way. About 2 minutes to fix.',
    'conv.guide.files.one': 'a private file',
    'conv.guide.files.other': '{n} private files',
    'conv.guide.something': 'something private',
    'conv.guide.go': 'Fix it now →',
    'conv.clean.title': 'Nothing to fix this week.',
    'conv.clean.body': 'Your AI didn’t read anything private.',
    'conv.clean.fixed': 'Your AI read something private, and it’s all fixed now.',
    'conv.clean.allowed': 'Your AI read only private files you let it read.',
    'conv.clean.fixedAllowed': 'Your AI read something private. What needed fixing is fixed, and the rest you let it read.',
    'conv.week.heading': 'Your week',
    'conv.week.earlier': 'An earlier week',
    'conv.week.later': 'A later week',
    'conv.week.back': 'Back to this week',
    'conv.week.pick': 'Choose a week',
    'conv.week.hint': 'Tap a day to see only that day',
    'conv.day.toCheck': '{n} to check',
    'conv.day.fixed.one': '1 read, fixed',
    'conv.day.fixed.other': '{n} read, fixed',
    'conv.day.good': 'All good',
    'conv.day.none': 'No work',
    'conv.need': 'Needs your attention',
    'conv.info': 'For your info',
    'conv.info.rest': '— your AI read files you track. Nothing to fix.',
    'conv.col.when': 'When',
    'conv.col.ask': 'What you asked',
    'conv.col.action': 'Action',
    'conv.untitled': 'A conversation with no title',
    'conv.day.unchecked.one': '1 not checked',
    'conv.day.unchecked.other': '{n} not checked',
    'conv.day.partial.one': '1 not fully checked',
    'conv.day.partial.other': '{n} not fully checked',
    'conv.unchecked.below.one': 'It’s listed below, with the reason.',
    'conv.unchecked.below.other': 'They’re listed below, with the reason.',
    'conv.hero.unchecked.one': 'One couldn’t be checked.',
    'conv.hero.unchecked.other': '{n} couldn’t be checked.',
    'conv.hero.partial.one': 'One couldn’t be fully checked.',
    'conv.hero.partial.other': '{n} couldn’t be fully checked.',
    'conv.unchecked': 'Not checked',
    'conv.unchecked.title.one': '1 conversation wasn’t checked.',
    'conv.unchecked.title.other': '{n} conversations weren’t checked.',
    'conv.unchecked.lead': 'This run didn’t read them: they are older than it, or their record couldn’t be read. To include older ones, run {command}',
    'conv.unchecked.check': 'This run didn’t read them yet. Press Check it beside one to read it now, or run {command} to include them all.',
    'conv.unchecked.partial.title.one': '1 conversation couldn’t be fully checked.',
    'conv.unchecked.partial.title.other': '{n} conversations couldn’t be fully checked.',
    'conv.unchecked.partial': 'Their record leaves out some steps, so their reports may not show everything your AI opened. Open one to see what was written down.',
    'conv.unchecked.mixed': 'Some are older than this check, or their record couldn’t be opened. The others leave out some steps, so their reports may not show everything. To include older ones, run {command}',
    'conv.unchecked.lead.rest': '— older than this check, or their record couldn’t be read.',
    'conv.unchecked.check.rest': '— not read yet.',
    'conv.unchecked.partial.rest': '— read, but their record has gaps.',
    'conv.unchecked.mixed.rest': '— some older than this check, the rest read with gaps.',
    'conv.act.fix': 'Fix it →',
    'conv.act.see': 'See report',
    'conv.act.none': 'No report',
    'conv.act.include': 'Check it',
    'conv.include.saving': 'Checking…',
    'conv.include.refused': 'That didn’t work:',
    'conv.include.asFile': 'This page was opened as a file. To check it, run this in your project:',
    'conv.include.unreachable': 'The page could not reach agentwhy - it may have stopped. Run it again.',
    'conv.others.count.one': '1 other conversation',
    'conv.others.count.other': '{n} other conversations',
    'conv.others.rest': '— nothing private to fix.',
    'conv.search': 'Find a conversation',
    'conv.empty': 'No conversations match.',
    'conv.shown': '{shown} of {total} shown. Most recent first.',
    'conv.tech.show': 'Show technical details',
    'conv.tech.hide': 'Hide technical details',
    'conv.tech.helpers.one': '1 helper',
    'conv.tech.helpers.other': '{n} helpers',
    'conv.tech.widen': 'to include it: {command}',
    'conv.tech.zone': 'Days and times are {zone}.',
    'conv.day.clear': 'Show the whole week',
    'conv.hero.lead.clean': 'Each time is one conversation with your AI. All of them were fine — open any to see what your AI did.',
    'conv.hero.lead.unchecked': 'Each time is one conversation with your AI. Nothing is waiting for you to fix.',
    'conv.hero.lead.fixed': 'Each time is one conversation with your AI. Everything it read has been fixed — open any to see what your AI did.',
    'conv.hero.lead.allowed': 'Each time is one conversation with your AI. It read only files you let it read — open any to see what your AI did.',
    'conv.hero.lead.fixedAllowed': 'Each time is one conversation with your AI. What it read has been fixed, or was a file you let it read — open any to see what your AI did.',
    'conv.list': 'Your conversations',
    'conv.filter.all': 'All',
    'conv.filter.label': 'Show only',
    'conv.more.all': 'Show all {n}',
    'conv.more.less': 'Show less',
    'conv.more.rest': '{n} more',
    'conv.day.count.one': '1 conversation',
    'conv.day.count.other': '{n} conversations',
    'conv.files.asked': 'You asked: “{ask}” · {when}',
    'conv.files.loading': 'Opening the files…',
    'conv.gap.unread.one': '1 command ran with no record of what it opened',
    'conv.gap.unread.other': '{n} commands ran with no record of what they opened',
    'conv.gap.unsure.one': '1 output not known to be whole',
    'conv.gap.unsure.other': '{n} outputs not known to be whole',
    'conv.gap.noResult.one': '1 step has no result',
    'conv.gap.noResult.other': '{n} steps have no result',
    'conv.gap.damaged.one': 'Part of the record couldn’t be read',
    'conv.gap.damaged.other': 'Parts of the record couldn’t be read',
    'conv.gap.unlinked.one': '1 message couldn’t be matched to its step',
    'conv.gap.unlinked.other': '{n} messages couldn’t be matched to their step',
    'conv.gap.format': '{ai} doesn’t write down every step',
    'conv.files.note': 'The same list as the Files tab of this conversation’s report.',
    'conv.files.full': 'Open the full report →',
    'conv.col.happened': 'What happened',
    'conv.did.read.one': 'Read 1 private file',
    'conv.did.read.other': 'Read {n} private files',
    'conv.did.partial.name.one': 'Its record names 1 private file.',
    'conv.did.partial.name.other': 'Its record names {n} private files.',
    'conv.col.setting': 'Your setting',
    'conv.fixed.yes': 'Fixed',
    'conv.fixed.no': 'Not yet',
    'conv.fixed.na': 'Nothing to fix',
    'conv.fixed.unknown': 'Not known',
    'conv.seeAll.one': 'See 1 file →',
    'conv.seeAll.other': 'See all {n} files →',
    'conv.empty.lead': 'That’s normal — you haven’t asked your AI for anything in this project since Monday.',
    'conv.empty.lead.today': 'That’s normal — you haven’t asked your AI for anything in this project today.',
    'conv.empty.safe': 'Your private files are protected either way.',
    'conv.empty.on': 'Protection is on.',
    'conv.empty.on.body': 'Your private files stay blocked.',
    'conv.empty.on.chosen': 'The private files you chose to block stay blocked.',
    'conv.empty.on.alert': 'If your AI tries to open one, we’ll alert you.',
    'conv.empty.last': 'See last week →',
    'conv.empty.earlier': 'See your last conversations →',
    'conv.empty.gap.one': '1 private file isn’t fully blocked.',
    'conv.empty.gap.other': '{n} private files aren’t fully blocked.',
    'conv.empty.gap.body': 'Your AI can still read what’s inside. You can finish blocking in Settings.',
    'conv.empty.settings': 'Open Settings →',
    'conv.day.yet': 'Nothing yet',
    'conv.day.ahead': 'Coming up',
    'conv.next': 'What happens next',
    'conv.next.1.title': 'Talk to your AI',
    'conv.next.1.body': 'Open Claude Code or Codex and ask for anything.',
    'conv.next.2.title': 'Work together',
    'conv.next.2.body': 'Let it do the job, like always.',
    'conv.next.3.title': 'See your conversation',
    'conv.next.3.body': 'Come back here to see what your AI did.',
    'conv.live': 'Connected · this page updates by itself',
    'conv.ask': '✦ Nothing showing up? See answers',
    'conv.ask.which': 'Which AI does agentwhy see?',
    'conv.ask.where': 'I asked my AI something, and it isn’t here.',
    'conv.ask.where.a': 'This page shows only this project’s conversations. One held in another folder belongs to that folder’s project.',
  },
  pl: {
    'conv.title': 'Rozmowy · agentwhy',
    'conv.week.this': 'Ten tydzień',
    'conv.week.last': 'Poprzedni tydzień',
    'conv.week.ago.few': '{n} tygodnie temu',
    'conv.week.ago.many': '{n} tygodni temu',
    'conv.hero.fact.one': 'Twoje AI pracowało dla ciebie raz.',
    'conv.hero.fact.few': 'Twoje AI pracowało dla ciebie {n} razy.',
    'conv.hero.fact.many': 'Twoje AI pracowało dla ciebie {n} razy.',
    'conv.hero.fact.zero': 'W tym tygodniu nie było jeszcze rozmów.',
    'conv.hero.none': 'Nic prywatnego nie zostało przeczytane.',
    'conv.hero.times.one': 'Raz przeczytało coś prywatnego.',
    'conv.hero.times.few': '{n} razy przeczytało coś prywatnego.',
    'conv.hero.times.many': '{n} razy przeczytało coś prywatnego.',
    'conv.hero.lead': 'Każdy raz to jedna rozmowa z twoim AI. Większość była w porządku. Te oznaczone na koralowo wymagają kilku minut twojego czasu.',
    'conv.day.today': 'Dziś',
    'conv.day.yesterday': 'Wczoraj',
    'conv.guide.today': 'dziś',
    'conv.guide.yesterday': 'wczoraj',
    'conv.guide.title': 'Zacznij od: {when}, {time}.',
    'conv.guide.asked': 'Prosiłeś: „{ask}”.',
    'conv.guide.read': 'Twoje AI przeczytało po drodze {what}. Naprawa zajmie około 2 minut.',
    'conv.guide.files.one': 'prywatny plik',
    'conv.guide.files.few': '{n} prywatne pliki',
    'conv.guide.files.many': '{n} prywatnych plików',
    'conv.guide.something': 'coś prywatnego',
    'conv.guide.go': 'Napraw teraz →',
    'conv.clean.title': 'W tym tygodniu nie ma nic do naprawy.',
    'conv.clean.body': 'Twoje AI nie przeczytało nic prywatnego.',
    'conv.clean.fixed': 'Twoje AI przeczytało coś prywatnego, ale wszystko jest już naprawione.',
    'conv.clean.allowed': 'Twoje AI przeczytało tylko prywatne pliki, na które mu pozwoliłeś.',
    'conv.clean.fixedAllowed': 'Twoje AI przeczytało coś prywatnego. To, co wymagało naprawy, jest naprawione, a resztę pozwoliłeś mu przeczytać.',
    'conv.week.heading': 'Twój tydzień',
    'conv.week.earlier': 'Wcześniejszy tydzień',
    'conv.week.later': 'Późniejszy tydzień',
    'conv.week.back': 'Wróć do tego tygodnia',
    'conv.week.pick': 'Wybierz tydzień',
    'conv.week.hint': 'Kliknij dzień, by zobaczyć tylko ten dzień',
    'conv.day.toCheck': '{n} do sprawdzenia',
    'conv.day.fixed.one': '1 odczyt, naprawiony',
    'conv.day.fixed.few': '{n} odczyty, naprawione',
    'conv.day.fixed.many': '{n} odczytów, naprawione',
    'conv.day.good': 'Wszystko dobrze',
    'conv.day.none': 'Bez pracy',
    'conv.need': 'Wymaga twojej uwagi',
    'conv.info': 'Dla twojej wiadomości',
    'conv.info.rest': '— twoje AI przeczytało pliki, które obserwujesz. Nic do naprawy.',
    'conv.col.when': 'Kiedy',
    'conv.col.ask': 'O co prosiłeś',
    'conv.col.action': 'Akcja',
    'conv.untitled': 'Rozmowa bez tytułu',
    'conv.day.unchecked.one': '1 niesprawdzona',
    'conv.day.unchecked.few': '{n} niesprawdzone',
    'conv.day.unchecked.many': '{n} niesprawdzonych',
    'conv.day.partial.one': '1 nie w pełni sprawdzona',
    'conv.day.partial.few': '{n} nie w pełni sprawdzone',
    'conv.day.partial.many': '{n} nie w pełni sprawdzonych',
    'conv.day.partial.other': '{n} nie w pełni sprawdzonej',
    'conv.unchecked.below.one': 'Jest na liście poniżej, razem z wyjaśnieniem.',
    'conv.unchecked.below.few': 'Są na liście poniżej, razem z wyjaśnieniem.',
    'conv.unchecked.below.many': 'Są na liście poniżej, razem z wyjaśnieniem.',
    'conv.unchecked.below.other': 'Są na liście poniżej, razem z wyjaśnieniem.',
    'conv.hero.unchecked.one': 'Jednej nie udało się sprawdzić.',
    'conv.hero.unchecked.few': '{n} nie udało się sprawdzić.',
    'conv.hero.unchecked.many': '{n} nie udało się sprawdzić.',
    'conv.hero.partial.one': 'Jednej nie udało się w pełni sprawdzić.',
    'conv.hero.partial.few': '{n} nie udało się w pełni sprawdzić.',
    'conv.hero.partial.many': '{n} nie udało się w pełni sprawdzić.',
    'conv.hero.partial.other': '{n} nie udało się w pełni sprawdzić.',
    'conv.unchecked': 'Nie sprawdzono',
    'conv.unchecked.title.one': '1 rozmowa nie została sprawdzona.',
    'conv.unchecked.title.few': '{n} rozmowy nie zostały sprawdzone.',
    'conv.unchecked.title.many': '{n} rozmów nie zostało sprawdzonych.',
    'conv.unchecked.lead': 'Ten przebieg ich nie czytał: są starsze niż on albo nie dało się odczytać ich zapisu. Żeby dołączyć starsze, uruchom {command}',
    'conv.unchecked.check': 'Ten przebieg jeszcze ich nie czytał. Kliknij Sprawdź przy którejś, żeby przeczytać ją teraz, albo uruchom {command}, żeby dołączyć wszystkie.',
    'conv.unchecked.partial.title.one': '1 rozmowa nie została w pełni sprawdzona.',
    'conv.unchecked.partial.title.few': '{n} rozmowy nie zostały w pełni sprawdzone.',
    'conv.unchecked.partial.title.many': '{n} rozmów nie zostało w pełni sprawdzonych.',
    'conv.unchecked.partial': 'Ich zapis pomija niektóre kroki, więc raporty mogą nie pokazywać wszystkiego, co otworzyło twoje AI. Otwórz którąś, żeby zobaczyć, co zostało zapisane.',
    'conv.unchecked.mixed': 'Część jest starsza niż to sprawdzenie albo nie dało się otworzyć ich zapisu. Zapis pozostałych pomija niektóre kroki, więc raporty mogą nie pokazywać wszystkiego. Żeby dołączyć starsze, uruchom {command}',
    'conv.unchecked.lead.rest': '— starsze niż to sprawdzenie albo nie dało się odczytać ich zapisu.',
    'conv.unchecked.check.rest': '— jeszcze nieprzeczytane.',
    'conv.unchecked.partial.rest': '— przeczytane, ale ich zapis ma luki.',
    'conv.unchecked.mixed.rest': '— część starsza niż to sprawdzenie, reszta przeczytana z lukami.',
    'conv.act.fix': 'Napraw →',
    'conv.act.see': 'Zobacz raport',
    'conv.act.none': 'Brak raportu',
    'conv.act.include': 'Sprawdź',
    'conv.include.saving': 'Sprawdzam…',
    'conv.include.refused': 'Nie udało się:',
    'conv.include.asFile': 'Ta strona została otwarta jako plik. Żeby to sprawdzić, uruchom w swoim projekcie:',
    'conv.include.unreachable': 'Strona nie mogła połączyć się z agentwhy - mógł się zatrzymać. Uruchom go ponownie.',
    'conv.others.count.one': '1 inna rozmowa',
    'conv.others.count.few': '{n} inne rozmowy',
    'conv.others.count.many': '{n} innych rozmów',
    'conv.others.rest': '— nic prywatnego do naprawy.',
    'conv.search': 'Znajdź rozmowę',
    'conv.empty': 'Żadna rozmowa nie pasuje.',
    'conv.shown': 'Pokazano {shown} z {total}. Najnowsze na górze.',
    'conv.tech.show': 'Pokaż szczegóły techniczne',
    'conv.tech.hide': 'Ukryj szczegóły techniczne',
    'conv.tech.helpers.one': '1 pomocnik',
    'conv.tech.helpers.few': '{n} pomocników',
    'conv.tech.helpers.many': '{n} pomocników',
    'conv.tech.widen': 'by ją dołączyć: {command}',
    'conv.tech.zone': 'Dni i godziny w strefie {zone}.',
    'conv.day.clear': 'Pokaż cały tydzień',
    'conv.hero.lead.clean': 'Każdy raz to jedna rozmowa z twoim AI. Wszystkie były w porządku — otwórz dowolną, żeby zobaczyć, co robiło twoje AI.',
    'conv.hero.lead.unchecked': 'Każdy raz to jedna rozmowa z twoim AI. Nic nie czeka na naprawę.',
    'conv.hero.lead.fixed': 'Każdy raz to jedna rozmowa z twoim AI. Wszystko, co przeczytało, jest już naprawione — otwórz dowolną, żeby zobaczyć, co robiło twoje AI.',
    'conv.hero.lead.allowed': 'Każdy raz to jedna rozmowa z twoim AI. Przeczytało tylko pliki, na które mu pozwoliłeś — otwórz dowolną, żeby zobaczyć, co robiło twoje AI.',
    'conv.hero.lead.fixedAllowed': 'Każdy raz to jedna rozmowa z twoim AI. To, co przeczytało, jest już naprawione albo było plikiem, na który mu pozwoliłeś — otwórz dowolną, żeby zobaczyć, co robiło twoje AI.',
    'conv.list': 'Twoje rozmowy',
    'conv.filter.all': 'Wszystkie',
    'conv.filter.label': 'Pokaż tylko',
    'conv.more.all': 'Pokaż wszystkie ({n})',
    'conv.more.less': 'Pokaż mniej',
    'conv.more.rest': 'jeszcze {n}',
    'conv.day.count.one': '1 rozmowa',
    'conv.day.count.few': '{n} rozmowy',
    'conv.day.count.many': '{n} rozmów',
    'conv.files.asked': 'Twoje pytanie: „{ask}” · {when}',
    'conv.files.loading': 'Otwieram pliki…',
    'conv.gap.unread.one': '1 polecenie bez zapisu, co otworzyło',
    'conv.gap.unread.few': '{n} polecenia bez zapisu, co otworzyły',
    'conv.gap.unread.many': '{n} poleceń bez zapisu, co otworzyły',
    'conv.gap.unsure.one': '1 wynik bez pewności, że jest cały',
    'conv.gap.unsure.few': '{n} wyniki bez pewności, że są całe',
    'conv.gap.unsure.many': '{n} wyników bez pewności, że są całe',
    'conv.gap.noResult.one': '1 krok bez wyniku',
    'conv.gap.noResult.few': '{n} kroki bez wyniku',
    'conv.gap.noResult.many': '{n} kroków bez wyniku',
    'conv.gap.damaged.one': 'Części zapisu nie dało się odczytać',
    'conv.gap.damaged.few': 'Części zapisu nie dało się odczytać',
    'conv.gap.damaged.many': 'Części zapisu nie dało się odczytać',
    'conv.gap.unlinked.one': 'Jednej wiadomości nie dało się przypiąć do kroku',
    'conv.gap.unlinked.few': '{n} wiadomości nie dało się przypiąć do kroku',
    'conv.gap.unlinked.many': '{n} wiadomości nie dało się przypiąć do kroku',
    'conv.gap.format': '{ai} nie zapisuje każdego kroku',
    'conv.files.note': 'Ta sama lista co zakładka Pliki w raporcie tej rozmowy.',
    'conv.files.full': 'Otwórz cały raport →',
    'conv.col.happened': 'Co się stało',
    'conv.did.read.one': 'Przeczytało 1 plik prywatny',
    'conv.did.read.few': 'Przeczytało {n} pliki prywatne',
    'conv.did.read.many': 'Przeczytało {n} plików prywatnych',
    'conv.did.partial.name.one': 'W zapisie jest nazwa 1 prywatnego pliku.',
    'conv.did.partial.name.few': 'W zapisie są nazwy {n} prywatnych plików.',
    'conv.did.partial.name.many': 'W zapisie są nazwy {n} prywatnych plików.',
    'conv.col.setting': 'Twoje ustawienie',
    'conv.fixed.yes': 'Naprawione',
    'conv.fixed.no': 'Jeszcze nie',
    'conv.fixed.na': 'Nic do naprawy',
    'conv.fixed.unknown': 'Nie wiadomo',
    'conv.seeAll.one': 'Zobacz 1 plik →',
    'conv.seeAll.few': 'Zobacz wszystkie {n} pliki →',
    'conv.seeAll.many': 'Zobacz wszystkie {n} plików →',
    'conv.empty.lead': 'To normalne — od poniedziałku o nic nie prosiłeś swojego AI w tym projekcie.',
    'conv.empty.lead.today': 'To normalne — dziś o nic nie prosiłeś swojego AI w tym projekcie.',
    'conv.empty.safe': 'Twoje prywatne pliki i tak są chronione.',
    'conv.empty.on': 'Ochrona jest włączona.',
    'conv.empty.on.body': 'Twoje prywatne pliki pozostają zablokowane.',
    'conv.empty.on.chosen': 'Prywatne pliki, które wybrałeś do zablokowania, pozostają zablokowane.',
    'conv.empty.on.alert': 'Jeśli twoje AI spróbuje któryś otworzyć, powiadomimy cię.',
    'conv.empty.last': 'Zobacz poprzedni tydzień →',
    'conv.empty.earlier': 'Zobacz ostatnie rozmowy →',
    'conv.empty.gap.one': '1 prywatny plik nie jest w pełni zablokowany.',
    'conv.empty.gap.few': '{n} prywatne pliki nie są w pełni zablokowane.',
    'conv.empty.gap.many': '{n} prywatnych plików nie jest w pełni zablokowanych.',
    'conv.empty.gap.body': 'Twoje AI wciąż może przeczytać, co jest w środku. Blokowanie dokończysz w Ustawieniach.',
    'conv.empty.settings': 'Otwórz Ustawienia →',
    'conv.day.yet': 'Jeszcze nic',
    'conv.day.ahead': 'Wkrótce',
    'conv.next': 'Co dalej',
    'conv.next.1.title': 'Porozmawiaj ze swoim AI',
    'conv.next.1.body': 'Otwórz Claude Code lub Codexa i poproś o cokolwiek.',
    'conv.next.2.title': 'Pracujcie razem',
    'conv.next.2.body': 'Pozwól mu wykonać zadanie, jak zawsze.',
    'conv.next.3.title': 'Zobacz swoją rozmowę',
    'conv.next.3.body': 'Wróć tutaj, żeby zobaczyć, co zrobiło twoje AI.',
    'conv.live': 'Połączono · ta strona odświeża się sama',
    'conv.ask': '✦ Nic się nie pojawia? Zobacz odpowiedzi',
    'conv.ask.which': 'Które AI widzi agentwhy?',
    'conv.ask.where': 'Poprosiłem AI o coś, a tego tu nie ma.',
    'conv.ask.where.a': 'Ta strona pokazuje tylko rozmowy z tego projektu. Rozmowa prowadzona w innym folderze należy do projektu tamtego folderu.',
  },
  de: {
    'conv.title': 'Unterhaltungen · agentwhy',
    'conv.week.this': 'Diese Woche',
    'conv.week.last': 'Letzte Woche',
    'conv.week.ago': 'vor {n} Wochen',
    'conv.hero.fact.one': 'Deine KI hat einmal für dich gearbeitet.',
    'conv.hero.fact.other': 'Deine KI hat {n}-mal für dich gearbeitet.',
    'conv.hero.fact.zero': 'Diese Woche gab es noch keine Unterhaltungen.',
    'conv.hero.none': 'Nichts Privates wurde gelesen.',
    'conv.hero.times.one': 'Einmal hat sie etwas Privates gelesen.',
    'conv.hero.times.other': '{n}-mal hat sie etwas Privates gelesen.',
    'conv.hero.lead': 'Jedes Mal ist eine Unterhaltung mit deiner KI. Die meisten waren in Ordnung. Die korallenrot markierten brauchen ein paar Minuten deiner Zeit.',
    'conv.day.today': 'Heute',
    'conv.day.yesterday': 'Gestern',
    'conv.guide.today': 'heute',
    'conv.guide.yesterday': 'gestern',
    'conv.guide.title': 'Fang mit {when}, {time} an.',
    'conv.guide.asked': 'Du hast gefragt: „{ask}“.',
    'conv.guide.read': 'Deine KI hat dabei {what} gelesen. Etwa 2 Minuten zum Beheben.',
    'conv.guide.files.one': 'eine private Datei',
    'conv.guide.files.other': '{n} private Dateien',
    'conv.guide.something': 'etwas Privates',
    'conv.guide.go': 'Jetzt beheben →',
    'conv.clean.title': 'Diese Woche gibt es nichts zu beheben.',
    'conv.clean.body': 'Deine KI hat nichts Privates gelesen.',
    'conv.clean.fixed': 'Deine KI hat etwas Privates gelesen, aber alles ist schon behoben.',
    'conv.clean.allowed': 'Deine KI hat nur private Dateien gelesen, die du ihr erlaubt hast.',
    'conv.clean.fixedAllowed': 'Deine KI hat etwas Privates gelesen. Was zu beheben war, ist behoben, den Rest hast du ihr erlaubt.',
    'conv.week.heading': 'Deine Woche',
    'conv.week.earlier': 'Eine frühere Woche',
    'conv.week.later': 'Eine spätere Woche',
    'conv.week.back': 'Zurück zu dieser Woche',
    'conv.week.pick': 'Woche wählen',
    'conv.week.hint': 'Tippe auf einen Tag, um nur diesen zu sehen',
    'conv.day.toCheck': '{n} zu prüfen',
    'conv.day.fixed.one': '1 gelesen, behoben',
    'conv.day.fixed.other': '{n} gelesen, behoben',
    'conv.day.good': 'Alles gut',
    'conv.day.none': 'Keine Arbeit',
    'conv.need': 'Braucht deine Aufmerksamkeit',
    'conv.info': 'Zur Info',
    'conv.info.rest': '— deine KI hat Dateien gelesen, die du beobachtest. Nichts zu beheben.',
    'conv.col.when': 'Wann',
    'conv.col.ask': 'Was du gefragt hast',
    'conv.col.action': 'Aktion',
    'conv.untitled': 'Eine Unterhaltung ohne Titel',
    'conv.day.unchecked.one': '1 nicht geprüft',
    'conv.day.unchecked.other': '{n} nicht geprüft',
    'conv.day.partial.one': '1 nicht ganz geprüft',
    'conv.day.partial.other': '{n} nicht ganz geprüft',
    'conv.unchecked.below.one': 'Sie steht unten in der Liste, mit dem Grund.',
    'conv.unchecked.below.other': 'Sie stehen unten in der Liste, mit dem Grund.',
    'conv.hero.unchecked.one': 'Eine konnte nicht geprüft werden.',
    'conv.hero.unchecked.other': '{n} konnten nicht geprüft werden.',
    'conv.hero.partial.one': 'Eine konnte nicht vollständig geprüft werden.',
    'conv.hero.partial.other': '{n} konnten nicht vollständig geprüft werden.',
    'conv.unchecked': 'Nicht geprüft',
    'conv.unchecked.title.one': '1 Unterhaltung wurde nicht geprüft.',
    'conv.unchecked.title.other': '{n} Unterhaltungen wurden nicht geprüft.',
    'conv.unchecked.lead': 'Dieser Lauf hat sie nicht gelesen: Sie sind älter als er, oder ihre Aufzeichnung konnte nicht gelesen werden. Um ältere einzubeziehen, führe {command} aus',
    'conv.unchecked.check': 'Dieser Lauf hat sie noch nicht gelesen. Klicke bei einer auf Prüfen, um sie jetzt zu lesen, oder führe {command} aus, um alle einzubeziehen.',
    'conv.unchecked.partial.title.one': '1 Unterhaltung konnte nicht vollständig geprüft werden.',
    'conv.unchecked.partial.title.other': '{n} Unterhaltungen konnten nicht vollständig geprüft werden.',
    'conv.unchecked.partial': 'Ihre Aufzeichnung lässt einige Schritte aus, daher zeigen ihre Berichte vielleicht nicht alles, was deine KI geöffnet hat. Öffne eine, um zu sehen, was aufgezeichnet wurde.',
    'conv.unchecked.mixed': 'Einige sind älter als diese Prüfung, oder ihre Aufzeichnung ließ sich nicht öffnen. Die übrigen lassen einige Schritte aus, daher zeigen ihre Berichte vielleicht nicht alles. Um ältere einzubeziehen, führe {command} aus',
    'conv.unchecked.lead.rest': '— älter als diese Prüfung, oder ihre Aufzeichnung war nicht lesbar.',
    'conv.unchecked.check.rest': '— noch nicht gelesen.',
    'conv.unchecked.partial.rest': '— gelesen, aber ihre Aufzeichnung hat Lücken.',
    'conv.unchecked.mixed.rest': '— einige älter als diese Prüfung, die übrigen mit Lücken gelesen.',
    'conv.act.fix': 'Beheben →',
    'conv.act.see': 'Bericht ansehen',
    'conv.act.none': 'Kein Bericht',
    'conv.act.include': 'Prüfen',
    'conv.include.saving': 'Wird geprüft…',
    'conv.include.refused': 'Das hat nicht geklappt:',
    'conv.include.asFile': 'Diese Seite wurde als Datei geöffnet. Um sie zu prüfen, führe das hier in deinem Projekt aus:',
    'conv.include.unreachable': 'Die Seite hat agentwhy nicht erreicht - vielleicht wurde es beendet. Starte es neu.',
    'conv.others.count.one': '1 weitere Unterhaltung',
    'conv.others.count.other': '{n} weitere Unterhaltungen',
    'conv.others.rest': '— nichts Privates zu beheben.',
    'conv.search': 'Unterhaltung suchen',
    'conv.empty': 'Keine Unterhaltung passt.',
    'conv.shown': '{shown} von {total} angezeigt. Neueste zuerst.',
    'conv.tech.show': 'Technische Details zeigen',
    'conv.tech.hide': 'Technische Details ausblenden',
    'conv.tech.helpers.one': '1 Helfer',
    'conv.tech.helpers.other': '{n} Helfer',
    'conv.tech.widen': 'um sie aufzunehmen: {command}',
    'conv.tech.zone': 'Tage und Uhrzeiten in {zone}.',
    'conv.day.clear': 'Die ganze Woche zeigen',
    'conv.hero.lead.clean': 'Jedes Mal ist eine Unterhaltung mit deiner KI. Alle waren in Ordnung — öffne eine, um zu sehen, was deine KI getan hat.',
    'conv.hero.lead.unchecked': 'Jedes Mal ist eine Unterhaltung mit deiner KI. Nichts wartet darauf, behoben zu werden.',
    'conv.hero.lead.fixed': 'Jedes Mal ist eine Unterhaltung mit deiner KI. Alles, was sie gelesen hat, ist behoben — öffne eine, um zu sehen, was deine KI getan hat.',
    'conv.hero.lead.allowed': 'Jedes Mal ist eine Unterhaltung mit deiner KI. Sie hat nur Dateien gelesen, die du ihr erlaubt hast — öffne eine, um zu sehen, was deine KI getan hat.',
    'conv.hero.lead.fixedAllowed': 'Jedes Mal ist eine Unterhaltung mit deiner KI. Was sie gelesen hat, ist behoben oder war eine Datei, die du ihr erlaubt hast — öffne eine, um zu sehen, was deine KI getan hat.',
    'conv.list': 'Deine Unterhaltungen',
    'conv.filter.all': 'Alle',
    'conv.filter.label': 'Nur zeigen',
    'conv.more.all': 'Alle {n} zeigen',
    'conv.more.less': 'Weniger zeigen',
    'conv.more.rest': '{n} weitere',
    'conv.day.count.one': '1 Unterhaltung',
    'conv.day.count.other': '{n} Unterhaltungen',
    'conv.files.asked': 'Du hast gefragt: „{ask}“ · {when}',
    'conv.files.loading': 'Dateien werden geöffnet…',
    'conv.gap.unread.one': '1 Befehl lief ohne Aufzeichnung, was er geöffnet hat',
    'conv.gap.unread.other': '{n} Befehle liefen ohne Aufzeichnung, was sie geöffnet haben',
    'conv.gap.unsure.one': '1 Ausgabe, von der unklar ist, ob sie vollständig ist',
    'conv.gap.unsure.other': '{n} Ausgaben, von denen unklar ist, ob sie vollständig sind',
    'conv.gap.noResult.one': '1 Schritt hat kein Ergebnis',
    'conv.gap.noResult.other': '{n} Schritte haben kein Ergebnis',
    'conv.gap.damaged.one': 'Ein Teil des Protokolls war nicht lesbar',
    'conv.gap.damaged.other': 'Teile des Protokolls waren nicht lesbar',
    'conv.gap.unlinked.one': '1 Nachricht ließ sich keinem Schritt zuordnen',
    'conv.gap.unlinked.other': '{n} Nachrichten ließen sich keinem Schritt zuordnen',
    'conv.gap.format': '{ai} zeichnet nicht jeden Schritt auf',
    'conv.files.note': 'Dieselbe Liste wie der Tab Dateien im Bericht dieser Unterhaltung.',
    'conv.files.full': 'Ganzen Bericht öffnen →',
    'conv.col.happened': 'Was passiert ist',
    'conv.did.read.one': '1 private Datei gelesen',
    'conv.did.read.other': '{n} private Dateien gelesen',
    'conv.did.partial.name.one': 'Im Protokoll steht der Name von 1 privaten Datei.',
    'conv.did.partial.name.other': 'Im Protokoll stehen die Namen von {n} privaten Dateien.',
    'conv.col.setting': 'Deine Einstellung',
    'conv.fixed.yes': 'Behoben',
    'conv.fixed.no': 'Noch nicht',
    'conv.fixed.na': 'Nichts zu beheben',
    'conv.fixed.unknown': 'Unbekannt',
    'conv.seeAll.one': '1 Datei ansehen →',
    'conv.seeAll.other': 'Alle {n} Dateien ansehen →',
    'conv.empty.lead': 'Das ist normal — du hast deine KI seit Montag in diesem Projekt um nichts gebeten.',
    'conv.empty.lead.today': 'Das ist normal — du hast deine KI heute in diesem Projekt um nichts gebeten.',
    'conv.empty.safe': 'Deine privaten Dateien sind so oder so geschützt.',
    'conv.empty.on': 'Der Schutz ist an.',
    'conv.empty.on.body': 'Deine privaten Dateien bleiben blockiert.',
    'conv.empty.on.chosen': 'Die privaten Dateien, die du blockieren wolltest, bleiben blockiert.',
    'conv.empty.on.alert': 'Wenn deine KI versucht, eine davon zu öffnen, geben wir dir einen Hinweis.',
    'conv.empty.last': 'Letzte Woche ansehen →',
    'conv.empty.earlier': 'Deine letzten Unterhaltungen ansehen →',
    'conv.empty.gap.one': '1 private Datei ist nicht ganz blockiert.',
    'conv.empty.gap.other': '{n} private Dateien sind nicht ganz blockiert.',
    'conv.empty.gap.body': 'Deine KI kann ihren Inhalt noch lesen. In den Einstellungen kannst du das Blockieren abschließen.',
    'conv.empty.settings': 'Einstellungen öffnen →',
    'conv.day.yet': 'Noch nichts',
    'conv.day.ahead': 'Kommt noch',
    'conv.next': 'Wie es weitergeht',
    'conv.next.1.title': 'Sprich mit deiner KI',
    'conv.next.1.body': 'Öffne Claude Code oder Codex und bitte um irgendetwas.',
    'conv.next.2.title': 'Arbeitet zusammen',
    'conv.next.2.body': 'Lass sie die Arbeit machen, wie immer.',
    'conv.next.3.title': 'Sieh dir deine Unterhaltung an',
    'conv.next.3.body': 'Komm hierher zurück, um zu sehen, was deine KI getan hat.',
    'conv.live': 'Verbunden · diese Seite aktualisiert sich selbst',
    'conv.ask': '✦ Nichts zu sehen? Antworten ansehen',
    'conv.ask.which': 'Welche KI sieht agentwhy?',
    'conv.ask.where': 'Ich habe meine KI etwas gefragt, und es ist nicht hier.',
    'conv.ask.where.a': 'Diese Seite zeigt nur die Unterhaltungen dieses Projekts. Eine Unterhaltung in einem anderen Ordner gehört zum Projekt dieses Ordners.',
  },
};
