// Copyright 2026 Nessprim Karol Kozer
// SPDX-License-Identifier: Apache-2.0
import type { Lang, Table } from '../../report-copy.ts';

/**
 * The words of the onboarding's computer-wide path (`.ai/specs/2026-10-05-protected-everywhere.md` G7-G10), as the
 * maintainer approved them in the design canvas *Protected everywhere* on 2026-10-06, in the glossary of the design
 * guidelines §7. They name the AIs and never a settings file (GD13), and say Codex only where its check is turned on
 * with the rules (G17) - so each sentence that names the AIs has a form for a computer with Codex and one without.
 *
 * Its "you can change this later in Settings" was left out while Settings could not show the computer's rules, and came
 * back with step 3's display half, which lists them there and switches and takes them out (guidelines §5: a page
 * promises only what can be done).
 */
export const EVERYWHERE_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'ob.ev.scope.title': 'What should agentwhy protect?',
    'ob.ev.scope.text': 'Most people start with the project they work on. You can protect files that belong to no project as well.',
    'ob.ev.scope.project': 'This project',
    'ob.ev.scope.project.text': 'Who agentwhy watches here, and which of its files are private.',
    'ob.ev.wayin.go': 'Choose files →',
    'ob.ev.scope.pick': 'A project',
    'ob.ev.scope.pick.text': 'The one you work on with your AI. You pick it next, from your projects or any folder.',
    'ob.ev.scope.hint.pick': 'Not sure? Start with the project you work on. You can protect the rest of your computer later, by going through the setup again from Settings.',
    'ob.ev.scope.chats.one': '1 AI chat',
    'ob.ev.scope.chats.other': '{n} AI chats',
    'ob.ev.scope.everywhere': 'Everything on this computer',
    'ob.ev.scope.everywhere.text': 'Files that belong to no project: your logins, keys, and folders you choose.',
    'ob.ev.where.codex': 'Kept from your AI in every project, in Claude Code and in Codex.',
    'ob.ev.where.claude': 'Kept from your AI in every project, in Claude Code.',
    'ob.ev.scope.hint': 'Not sure? Start with this project. You can protect the rest of your computer later, by going through the setup again from Settings.',
    'ob.ev.scope.again': 'Setting up again. Nothing is written until you finish.',
    'ob.ev.scope.text.again': 'Pick one to see what’s in force and change it.',
    'ob.ev.scope.hint.again': 'Each step shows what is set now. Only what you change is written, when you press Finish.',
    'ob.ev.scope.next.project': 'Next: three short steps. Who agentwhy is for, which files are private, and when to tell you.',
    'ob.ev.scope.next.everywhere': 'Next: one step. The files to keep from your AI in every project.',

    'ob.ev.stepper': 'Setup steps, everything on this computer',
    'ob.ev.stepper.choose': 'Choose',
    'ob.ev.step': 'Step 2 of 2',
    'ob.ev.for': 'For everything on this computer',
    'ob.ev.include': 'Add',
    'ob.ev.note.blocked': 'Already blocked in every project',
    'ob.ev.note.tracked': 'Already tracked in every project',
    'ob.ev.note.absent': 'Not on this computer yet',
    'ob.ev.files.title': 'Which files on this computer are private?',
    'ob.ev.files.text': 'None of these is in a project. Choose what happens when your AI reaches one, in any project.',
    'ob.ev.row.ssh': 'Your server login keys',
    'ob.ev.row.aws': 'Your Amazon Web Services login',
    'ob.ev.row.azure': 'Your Microsoft Azure login',
    'ob.ev.row.gcloud': 'Your Google Cloud login',
    'ob.ev.row.github': 'Your GitHub login',
    'ob.ev.row.git-credentials': 'Saved Git passwords',
    'ob.ev.row.gnupg': 'Your signing keys',
    'ob.ev.row.kube': 'Access to your Kubernetes clusters',
    'ob.ev.row.docker': 'Your Docker login',
    'ob.ev.row.netrc': 'Logins saved for other tools',
    'ob.ev.more.one': '1 more, for a tool not on this computer · Show',
    'ob.ev.more.other': '{n} more, for tools not on this computer · Show',
    'ob.ev.less': 'Show less',
    'ob.ev.add': 'Add another private file or folder',
    'ob.ev.files.hint': 'Not sure about one? Leave it on Block. Blocking stops the obvious tries, not every trick; if something slips past, you’ll still see it in your report.',
    'ob.ev.count.zero': 'Nothing new chosen',
    'ob.ev.count.one': '1 to protect',
    'ob.ev.count.other': '{n} to protect',
    'ob.ev.cannot': 'agentwhy couldn’t read your Claude Code settings, so nothing can be changed here. Once they can be read, open this page again.',

    'ob.ev.confirm.title': 'Protect these files on this computer?',
    'ob.ev.confirm.codex': 'This holds in every project on this computer, in Claude Code and in Codex.',
    'ob.ev.confirm.claude': 'This holds in every project on this computer, in Claude Code.',
    'ob.ev.confirm.blocked': 'Kept from your AI',
    'ob.ev.confirm.blocked.text': 'No project can turn this off, and a blocked file can’t be read either, not only changed.',
    'ob.ev.confirm.blockedN.one': '1 private file kept from your AI',
    'ob.ev.confirm.blockedN.other': '{n} private files kept from your AI',
    'ob.ev.confirm.trackedN.one': '1 file your AI may read — you’ll be told',
    'ob.ev.confirm.trackedN.other': '{n} files your AI may read — you’ll be told',
    'ob.ev.confirm.tracked': 'Your AI may read it, and you’ll be told',
    'ob.ev.confirm.tracked.text': 'agentwhy tells you when your AI reads one.',
    'ob.ev.confirm.check': 'This also turns on agentwhy’s check in Codex, so Codex keeps to these too.',
    'ob.ev.confirm.yes': 'Yes, protect them',
    'ob.ev.confirm.later': 'You can switch or take out any of these later in Settings, under Private files.',
    'ob.ev.done.later': 'Change any of this later in {settings}, under Private files.',
    'ob.ev.done.settings': 'Settings',

    'ob.ev.done.title': 'You’re set up on this computer.',
    'ob.ev.done.where': 'Everything on this computer',
    'ob.ev.done.blocked.one': '1 kind of files blocked',
    'ob.ev.done.blocked.other': '{n} kinds of files blocked',
    'ob.ev.done.tracked.one': '1 tracked',
    'ob.ev.done.tracked.other': '{n} tracked',
    'ob.ev.done.blockedLine.codex': 'Your AI can’t read the blocked files, in any project, in Claude Code or in Codex.',
    'ob.ev.done.blockedLine.claude': 'Your AI can’t read the blocked files, in any project, in Claude Code.',
    'ob.ev.done.trackedLine': 'When it reads a tracked one, agentwhy tells you.',
    'ob.ev.done.codexOff': 'Codex isn’t covered yet: agentwhy’s check couldn’t be turned on there, so Codex can still open these files.',
    'ob.ev.done.failed.block': 'The files to block couldn’t be written, so they aren’t blocked.',
    'ob.ev.done.failed.tell': 'The files to track couldn’t be written, so you won’t be told about them.',
    'ob.ev.done.failed.alerts': 'Alerts couldn’t be turned on. You can turn them on later in Settings, under Alerts.',
    'ob.ev.done.alertsLine': 'Alerts are on in every project: a short note in your Claude Code chat when your AI reads a private file.',
    'ob.ev.confirm.alerts': 'Alerts in every project',
    'ob.ev.confirm.alerts.text': 'A short note in your Claude Code chat when your AI reads a private file. A project with its own alerts isn’t told twice.',
    'ob.ev.done.project.title': '{name} isn’t set up yet',
    'ob.ev.done.project.text': 'These rules cover files that belong to no project. The private files inside {name}, like the passwords for its live app, need its own setup.',
    'ob.ev.done.project.go': 'Set up {name} too',
    'ob.ev.done.pick.title': 'Now the project you work on',
    'ob.ev.done.pick.text': 'The private files inside a project, like the passwords for its live app, need that project’s own setup.',
    'ob.ev.done.pick.go': 'Choose a project →',

    'proj.ev.shown': 'Shown now',
    'app.computer': 'Showing',
    'app.computer.name': 'This computer',
    'proj.ev.held.one': '1 kind of files kept from your AI, in every project',
    'proj.ev.held.other': '{n} kinds of files kept from your AI, in every project',

    // Settings' rows of the computer (step 3): its badge, a project row it also blocks, and its windows.
    'set.src.short.computer': 'This computer',
    'set.elsewhere.title': 'Also kept on this whole computer',
    'set.elsewhere.lead': 'These come from This computer and hold in every project, this one included. They’re changed there, not here.',
    'set.elsewhere.go': 'Change them in This computer →',
    'set.elsewhere.where': 'Change them on This computer’s page: run agentwhy in your home folder.',
    'set.rule.everywhere': 'Blocked in every project on this computer too, so Track here would change nothing.',
    'set.ev.tell': 'Let your AI read it, in every project?',
    'set.ev.tell.text': 'Your AI will be able to read {name} in any project on this computer, and agentwhy tells you when it does. Once it has seen what’s inside, you can’t take that back.',
    'set.ev.block': 'Block it in every project?',
    'set.ev.block.text': 'Your AI won’t be able to read {name} in any project on this computer, in Claude Code, and no project can turn that off.',
    'set.ev.block.text.codex': 'Your AI won’t be able to read {name} in any project on this computer, in Claude Code and in Codex, and no project can turn that off.',
    'set.ev.unblock': 'Stop protecting it on this computer?',
    'set.ev.unblock.text': '{name} is no longer kept from your AI in every project. A project that protects it itself still does.',
    'set.ev.untell': 'Stop tracking it on this computer?',
    'set.ev.untell.text': 'agentwhy no longer tells you when your AI reads {name}, in any project, unless a project tracks it itself.',
    'set.ev.notWritten': 'not every change to this computer’s rules could be made. Reload the page to see them as they are now.',
    'set.ev.add': 'Protect it in every project?',
    'set.ev.addMany': 'Keep these from your AI in every project?',
    'set.ev.addMany.text': 'In every project on this computer, and no project can turn that off.',
    'set.place.file': 'Only this file, wherever your AI works',
    'set.place.folder': 'This folder and everything in it, wherever your AI works',
    'set.place.name': 'Matched by name, and only inside the folder your AI works in',
    'set.ev.stale.one': '1 rule here is written the old way: Claude Code applies it only inside the folder your AI works in.',
    'set.ev.stale.other': '{n} rules here are written the old way: Claude Code applies them only inside the folder your AI works in.',
    'set.ev.stale.row': 'Written the old way: it holds only inside the folder your AI works in.',
    'set.ev.update': 'Write it for its place?',
    'set.ev.update.text': 'An older agentwhy wrote it by name, and Claude Code applies it only inside the folder your AI works in. Written for its place, it holds wherever your AI works, and the old rule comes out.',
    'set.ev.update.go': 'Update',
    'set.ev.updateAll': 'Write them for their places?',
    'set.ev.updateAll.text': 'An older agentwhy wrote them by name, and Claude Code applies them only inside the folder your AI works in. Written for their places, they hold wherever your AI works, and the old rules come out.',
    'set.ev.updateAll.go': 'Update them',
    'set.ev.alerts.lead': 'agentwhy adds a short note to your Claude Code chat, in every project on this computer. A project that has its own alerts keeps them, and is never told twice. The first one matters most; the other two are optional and only work when it is on.',
    'set.ev.state.on': 'On — in every project',
    'cs.label': 'What this page shows',
    'cs.outside': 'Outside projects',
    'cs.projects': 'Projects',
    'cs.say.outside': 'Conversations of projects not set up yet, and of chats with no project.',
    'cs.say.projects': 'The conversations of the projects you set up, each named by its project.',
    'cs.failed': 'Couldn’t switch:',
    'cs.kind.none': 'No project',
    'cs.kind.notSetUp': 'not set up',
    'set.ev.uninstall.title': 'Uninstall agentwhy from this computer',
    'set.ev.uninstall.text': 'Takes out what was set up for every project: the files blocked and tracked on this computer, and alerts in every project. Each project’s own setup stays.',
    'set.ev.confirm.uninstall': 'Uninstall agentwhy from this computer?',
    'set.ev.confirm.uninstall.text': 'We’ll take out the files agentwhy blocks and tracks on this computer, and turn off alerts in every project. Your AI can open those files again outside the projects that protect them themselves. Each project’s own setup stays, and so does agentwhy’s check in Codex, which your projects share. A rule you wrote yourself stays too.',
    'set.ev.confirm.alerts.on': 'Turn on alerts in every project?',
    'set.ev.confirm.alerts.on.text': 'You’ll get a short message in your Claude Code chat when your AI reads something private, in every project on this computer — ones you haven’t set up too. A project with its own alerts isn’t told twice.',
    'set.ev.confirm.alerts.off': 'Turn off alerts in every project?',
    'set.ev.confirm.alerts.off.text': 'Projects that have their own alerts keep them. Everywhere else you won’t be told right away; you’ll still see everything later in your report.',
  },
  pl: {
    'ob.ev.scope.title': 'Co agentwhy ma chronić?',
    'ob.ev.scope.text': 'Większość osób zaczyna od projektu, nad którym pracuje. Możesz też chronić pliki, które nie należą do żadnego projektu.',
    'ob.ev.scope.project': 'Ten projekt',
    'ob.ev.scope.project.text': 'Kogo agentwhy tu pilnuje i które jego pliki są prywatne.',
    'ob.ev.wayin.go': 'Wybierz pliki →',
    'ob.ev.scope.pick': 'Projekt',
    'ob.ev.scope.pick.text': 'Ten, nad którym pracujesz z AI. Wybierzesz go za chwilę — z listy projektów albo dowolny folder.',
    'ob.ev.scope.hint.pick': 'Nie wiesz? Zacznij od projektu, nad którym pracujesz. Resztę komputera możesz ochronić później, przechodząc konfigurację jeszcze raz z Ustawień.',
    'ob.ev.scope.chats.one': '1 czat z AI',
    'ob.ev.scope.chats.few': '{n} czaty z AI',
    'ob.ev.scope.chats.many': '{n} czatów z AI',
    'ob.ev.scope.everywhere': 'Wszystko na tym komputerze',
    'ob.ev.scope.everywhere.text': 'Pliki, które nie należą do żadnego projektu: Twoje loginy, klucze i foldery, które wybierzesz.',
    'ob.ev.where.codex': 'Niedostępne dla Twojego AI w każdym projekcie, w Claude Code i w Codex.',
    'ob.ev.where.claude': 'Niedostępne dla Twojego AI w każdym projekcie, w Claude Code.',
    'ob.ev.scope.hint': 'Nie wiesz? Zacznij od tego projektu. Resztę komputera możesz ochronić później, przechodząc ustawienia jeszcze raz z poziomu Ustawień.',
    'ob.ev.scope.again': 'Konfiguracja jeszcze raz. Nic nie zostanie zapisane, zanim nie skończysz.',
    'ob.ev.scope.text.again': 'Wybierz jedno, żeby zobaczyć, co obowiązuje, i to zmienić.',
    'ob.ev.scope.hint.again': 'Każdy krok pokazuje, co jest ustawione teraz. Zapisze się tylko to, co zmienisz, gdy naciśniesz Zakończ.',
    'ob.ev.scope.next.project': 'Dalej: trzy krótkie kroki. Dla kogo jest agentwhy, które pliki są prywatne i kiedy ci powiedzieć.',
    'ob.ev.scope.next.everywhere': 'Dalej: jeden krok. Pliki, które mają być trzymane z dala od twojego AI w każdym projekcie.',

    'ob.ev.stepper': 'Kroki ustawień, wszystko na tym komputerze',
    'ob.ev.stepper.choose': 'Wybór',
    'ob.ev.step': 'Krok 2 z 2',
    'ob.ev.for': 'Dla wszystkiego na tym komputerze',
    'ob.ev.include': 'Dodaj',
    'ob.ev.note.blocked': 'Już zablokowany w każdym projekcie',
    'ob.ev.note.tracked': 'Już obserwowany w każdym projekcie',
    'ob.ev.note.absent': 'Jeszcze go nie ma na tym komputerze',
    'ob.ev.files.title': 'Które pliki na tym komputerze są prywatne?',
    'ob.ev.files.text': 'Żaden z nich nie jest w projekcie. Wybierz, co ma się stać, gdy Twoje AI po któryś sięgnie, w dowolnym projekcie.',
    'ob.ev.row.ssh': 'Twoje klucze do logowania na serwery',
    'ob.ev.row.aws': 'Twój login do Amazon Web Services',
    'ob.ev.row.azure': 'Twój login do Microsoft Azure',
    'ob.ev.row.gcloud': 'Twój login do Google Cloud',
    'ob.ev.row.github': 'Twój login do GitHuba',
    'ob.ev.row.git-credentials': 'Zapisane hasła do Gita',
    'ob.ev.row.gnupg': 'Twoje klucze do podpisywania',
    'ob.ev.row.kube': 'Dostęp do Twoich klastrów Kubernetes',
    'ob.ev.row.docker': 'Twój login do Dockera',
    'ob.ev.row.netrc': 'Loginy zapisane przez inne narzędzia',
    'ob.ev.more.one': 'Jeszcze 1, dla narzędzia, którego nie ma na tym komputerze · Pokaż',
    'ob.ev.more.few': 'Jeszcze {n}, dla narzędzi, których nie ma na tym komputerze · Pokaż',
    'ob.ev.more.many': 'Jeszcze {n}, dla narzędzi, których nie ma na tym komputerze · Pokaż',
    'ob.ev.less': 'Pokaż mniej',
    'ob.ev.add': 'Dodaj kolejny prywatny plik lub folder',
    'ob.ev.files.hint': 'Nie wiesz, co wybrać? Zostaw Blokuj. Blokowanie zatrzymuje oczywiste próby, nie każdą sztuczkę; jeśli coś się prześlizgnie, i tak zobaczysz to w raporcie.',
    'ob.ev.count.zero': 'Nic nowego nie wybrano',
    'ob.ev.count.one': '1 do ochrony',
    'ob.ev.count.few': '{n} do ochrony',
    'ob.ev.count.many': '{n} do ochrony',
    'ob.ev.cannot': 'agentwhy nie mógł odczytać Twoich ustawień Claude Code, więc nic nie można tu zmienić. Gdy da się je odczytać, otwórz tę stronę ponownie.',

    'ob.ev.confirm.title': 'Chronić te pliki na tym komputerze?',
    'ob.ev.confirm.codex': 'Obowiązuje to w każdym projekcie na tym komputerze, w Claude Code i w Codex.',
    'ob.ev.confirm.claude': 'Obowiązuje to w każdym projekcie na tym komputerze, w Claude Code.',
    'ob.ev.confirm.blocked': 'Niedostępne dla Twojego AI',
    'ob.ev.confirm.blocked.text': 'Żaden projekt nie może tego wyłączyć, a zablokowanego pliku nie da się też odczytać, nie tylko zmienić.',
    'ob.ev.confirm.blockedN.one': '1 prywatny plik chroniony przed AI',
    'ob.ev.confirm.blockedN.few': '{n} prywatne pliki chronione przed AI',
    'ob.ev.confirm.blockedN.many': '{n} prywatnych plików chronionych przed AI',
    'ob.ev.confirm.trackedN.one': '1 plik, który AI może czytać — powiemy Ci o tym',
    'ob.ev.confirm.trackedN.few': '{n} pliki, które AI może czytać — powiemy Ci o tym',
    'ob.ev.confirm.trackedN.many': '{n} plików, które AI może czytać — powiemy Ci o tym',
    'ob.ev.confirm.tracked': 'Twoje AI może je odczytać, a Ty się o tym dowiesz',
    'ob.ev.confirm.tracked.text': 'agentwhy powie Ci, gdy Twoje AI któryś odczyta.',
    'ob.ev.confirm.check': 'To włącza też sprawdzanie agentwhy w Codex, więc Codex również się tego trzyma.',
    'ob.ev.confirm.yes': 'Tak, chroń je',
    'ob.ev.confirm.later': 'Każdy z nich możesz później przełączyć albo usunąć w Ustawieniach, w zakładce Prywatne pliki.',
    'ob.ev.done.later': 'Możesz to później zmienić w {settings}, w zakładce Prywatne pliki.',
    'ob.ev.done.settings': 'Ustawieniach',

    'ob.ev.done.title': 'Ten komputer jest ustawiony.',
    'ob.ev.done.where': 'Wszystko na tym komputerze',
    'ob.ev.done.blocked.one': '1 rodzaj plików zablokowany',
    'ob.ev.done.blocked.few': '{n} rodzaje plików zablokowane',
    'ob.ev.done.blocked.many': '{n} rodzajów plików zablokowanych',
    'ob.ev.done.tracked.one': '1 obserwowany',
    'ob.ev.done.tracked.few': '{n} obserwowane',
    'ob.ev.done.tracked.many': '{n} obserwowanych',
    'ob.ev.done.blockedLine.codex': 'Twoje AI nie odczyta zablokowanych plików, w żadnym projekcie, w Claude Code ani w Codex.',
    'ob.ev.done.blockedLine.claude': 'Twoje AI nie odczyta zablokowanych plików, w żadnym projekcie, w Claude Code.',
    'ob.ev.done.trackedLine': 'Gdy odczyta któryś z obserwowanych, agentwhy Ci powie.',
    'ob.ev.done.codexOff': 'Codex nie jest jeszcze objęty: nie udało się tam włączyć sprawdzania agentwhy, więc Codex nadal może otwierać te pliki.',
    'ob.ev.done.failed.block': 'Nie udało się zapisać plików do zablokowania, więc nie są zablokowane.',
    'ob.ev.done.failed.tell': 'Nie udało się zapisać plików do obserwowania, więc nie dowiesz się o nich.',
    'ob.ev.done.failed.alerts': 'Nie udało się włączyć powiadomień. Możesz je włączyć później w Ustawieniach, w zakładce Powiadomienia.',
    'ob.ev.done.alertsLine': 'Powiadomienia działają w każdym projekcie: krótka wiadomość w czacie z Claude Code, gdy twoje AI przeczyta prywatny plik.',
    'ob.ev.confirm.alerts': 'Powiadomienia w każdym projekcie',
    'ob.ev.confirm.alerts.text': 'Krótka wiadomość w czacie z Claude Code, gdy twoje AI przeczyta prywatny plik. Projekt z własnymi powiadomieniami nie dostanie ich podwójnie.',
    'ob.ev.done.project.title': '{name} nie jest jeszcze ustawiony',
    'ob.ev.done.project.text': 'Te zasady obejmują pliki, które nie należą do żadnego projektu. Prywatne pliki w {name}, na przykład hasła do działającej aplikacji, potrzebują jego własnych ustawień.',
    'ob.ev.done.project.go': 'Ustaw też {name}',
    'ob.ev.done.pick.title': 'Teraz projekt, nad którym pracujesz',
    'ob.ev.done.pick.text': 'Prywatne pliki w projekcie, na przykład hasła do działającej aplikacji, potrzebują ustawień tego projektu.',
    'ob.ev.done.pick.go': 'Wybierz projekt →',

    'proj.ev.shown': 'Widoczny teraz',
    'app.computer': 'Widok',
    'app.computer.name': 'Ten komputer',
    'proj.ev.held.one': '1 rodzaj plików niedostępny dla Twojego AI, w każdym projekcie',
    'proj.ev.held.few': '{n} rodzaje plików niedostępne dla Twojego AI, w każdym projekcie',
    'proj.ev.held.many': '{n} rodzajów plików niedostępnych dla Twojego AI, w każdym projekcie',

    // Wiersze komputera w Ustawieniach (krok 3): plakietka, wiersz projektu, który komputer też blokuje, i okna.
    'set.src.short.computer': 'Ten komputer',
    'set.elsewhere.title': 'Chronione też na całym komputerze',
    'set.elsewhere.lead': 'Te reguły pochodzą z „Ten komputer” i działają w każdym projekcie, także w tym. Zmienia się je tam, nie tutaj.',
    'set.elsewhere.go': 'Zmień je w „Ten komputer” →',
    'set.elsewhere.where': 'Zmienisz je na stronie „Ten komputer”: uruchom agentwhy w katalogu domowym.',
    'set.rule.everywhere': 'Zablokowany też w każdym projekcie na tym komputerze, więc Obserwuj tutaj niczego by nie zmieniło.',
    'set.ev.tell': 'Pozwolić Twojemu AI to czytać, w każdym projekcie?',
    'set.ev.tell.text': 'Twoje AI będzie mogło czytać {name} w każdym projekcie na tym komputerze, a agentwhy powie Ci, gdy to zrobi. Gdy już zobaczy, co jest w środku, nie da się tego cofnąć.',
    'set.ev.block': 'Zablokować to w każdym projekcie?',
    'set.ev.block.text': 'Twoje AI nie odczyta {name} w żadnym projekcie na tym komputerze, w Claude Code, i żaden projekt nie może tego wyłączyć.',
    'set.ev.block.text.codex': 'Twoje AI nie odczyta {name} w żadnym projekcie na tym komputerze, w Claude Code ani w Codex, i żaden projekt nie może tego wyłączyć.',
    'set.ev.unblock': 'Przestać to chronić na tym komputerze?',
    'set.ev.unblock.text': '{name} nie jest już niedostępne dla Twojego AI w każdym projekcie. Projekt, który chroni to sam, nadal to robi.',
    'set.ev.untell': 'Przestać to obserwować na tym komputerze?',
    'set.ev.untell.text': 'agentwhy nie powie Ci już, gdy Twoje AI odczyta {name}, w żadnym projekcie, chyba że projekt sam to obserwuje.',
    'set.ev.notWritten': 'nie każdą zmianę zasad tego komputera udało się wprowadzić. Odśwież stronę, żeby zobaczyć, jak jest teraz.',
    'set.ev.add': 'Chronić to w każdym projekcie?',
    'set.ev.addMany': 'Ukryć je przed AI w każdym projekcie?',
    'set.ev.addMany.text': 'W każdym projekcie na tym komputerze, i żaden projekt nie może tego wyłączyć.',
    'set.place.file': 'Tylko ten plik, gdziekolwiek pracuje twoje AI',
    'set.place.folder': 'Ten folder z całą zawartością, gdziekolwiek pracuje twoje AI',
    'set.place.name': 'Po nazwie, i tylko w folderze, w którym pracuje twoje AI',
    'set.ev.stale.one': '1 reguła jest tu zapisana po staremu: Claude Code stosuje ją tylko w folderze, w którym pracuje twoje AI.',
    'set.ev.stale.few': '{n} reguły są tu zapisane po staremu: Claude Code stosuje je tylko w folderze, w którym pracuje twoje AI.',
    'set.ev.stale.many': '{n} reguł jest tu zapisanych po staremu: Claude Code stosuje je tylko w folderze, w którym pracuje twoje AI.',
    'set.ev.stale.row': 'Zapisana po staremu: działa tylko w folderze, w którym pracuje twoje AI.',
    'set.ev.update': 'Zapisać ją dla jej miejsca?',
    'set.ev.update.text': 'Starsza wersja agentwhy zapisała ją po nazwie, a Claude Code stosuje ją tylko w folderze, w którym pracuje twoje AI. Zapisana dla swojego miejsca działa wszędzie, gdzie pracuje twoje AI, a stara reguła zostaje usunięta.',
    'set.ev.update.go': 'Zaktualizuj',
    'set.ev.updateAll': 'Zapisać je dla ich miejsc?',
    'set.ev.updateAll.text': 'Starsza wersja agentwhy zapisała je po nazwie, a Claude Code stosuje je tylko w folderze, w którym pracuje twoje AI. Zapisane dla swoich miejsc działają wszędzie, gdzie pracuje twoje AI, a stare reguły zostają usunięte.',
    'set.ev.updateAll.go': 'Zaktualizuj je',
    'set.ev.alerts.lead': 'agentwhy dopisuje krótką wiadomość do twojego czatu z Claude Code, w każdym projekcie na tym komputerze. Projekt, który ma własne powiadomienia, zachowuje je i nigdy nie dostaje ich podwójnie. Pierwsza jest najważniejsza; pozostałe dwie są opcjonalne i działają tylko wtedy, gdy jest włączona.',
    'set.ev.state.on': 'Włączone — w każdym projekcie',
    'cs.label': 'Co pokazuje ta strona',
    'cs.outside': 'Poza projektami',
    'cs.projects': 'Projekty',
    'cs.say.outside': 'Rozmowy z projektów, które nie są jeszcze ustawione, i z czatów bez projektu.',
    'cs.say.projects': 'Rozmowy z projektów, które są ustawione, każda z nazwą swojego projektu.',
    'cs.failed': 'Nie udało się przełączyć:',
    'cs.kind.none': 'Bez projektu',
    'cs.kind.notSetUp': 'nieustawiony',
    'set.ev.uninstall.title': 'Odinstaluj agentwhy z tego komputera',
    'set.ev.uninstall.text': 'Usuwa to, co ustawiono dla każdego projektu: pliki zablokowane i śledzone na tym komputerze oraz powiadomienia w każdym projekcie. Ustawienia każdego projektu zostają.',
    'set.ev.confirm.uninstall': 'Odinstalować agentwhy z tego komputera?',
    'set.ev.confirm.uninstall.text': 'Usuniemy pliki, które agentwhy blokuje i śledzi na tym komputerze, i wyłączymy powiadomienia w każdym projekcie. Twoje AI znów będzie mogło otwierać te pliki poza projektami, które same je chronią. Ustawienia każdego projektu zostają, podobnie jak kontrola agentwhy w Codexie, którą dzielą Twoje projekty. Reguła dopisana ręcznie też zostaje.',
    'set.ev.confirm.alerts.on': 'Włączyć powiadomienia w każdym projekcie?',
    'set.ev.confirm.alerts.on.text': 'Dostaniesz krótką wiadomość w czacie z Claude Code, gdy twoje AI przeczyta coś prywatnego, w każdym projekcie na tym komputerze — także w tych, które nie są jeszcze ustawione. Projekt z własnymi powiadomieniami nie dostanie ich podwójnie.',
    'set.ev.confirm.alerts.off': 'Wyłączyć powiadomienia w każdym projekcie?',
    'set.ev.confirm.alerts.off.text': 'Projekty z własnymi powiadomieniami je zachowają. Wszędzie indziej nie dowiesz się od razu; wszystko i tak zobaczysz później w raporcie.',
  },
  de: {
    'ob.ev.scope.title': 'Was soll agentwhy schützen?',
    'ob.ev.scope.text': 'Die meisten beginnen mit dem Projekt, an dem sie arbeiten. Du kannst auch Dateien schützen, die zu keinem Projekt gehören.',
    'ob.ev.scope.project': 'Dieses Projekt',
    'ob.ev.scope.project.text': 'Wen agentwhy hier im Blick hat und welche seiner Dateien privat sind.',
    'ob.ev.wayin.go': 'Dateien wählen →',
    'ob.ev.scope.pick': 'Ein Projekt',
    'ob.ev.scope.pick.text': 'Das, an dem du mit deiner KI arbeitest. Du wählst es gleich – aus deinen Projekten oder einen beliebigen Ordner.',
    'ob.ev.scope.hint.pick': 'Unsicher? Fang mit dem Projekt an, an dem du arbeitest. Den Rest deines Computers kannst du später schützen, indem du die Einrichtung in den Einstellungen noch einmal durchgehst.',
    'ob.ev.scope.chats.one': '1 KI-Chat',
    'ob.ev.scope.chats.other': '{n} KI-Chats',
    'ob.ev.scope.everywhere': 'Alles auf diesem Computer',
    'ob.ev.scope.everywhere.text': 'Dateien, die zu keinem Projekt gehören: deine Logins, Schlüssel und Ordner, die du auswählst.',
    'ob.ev.where.codex': 'Für deine KI gesperrt, in jedem Projekt, in Claude Code und in Codex.',
    'ob.ev.where.claude': 'Für deine KI gesperrt, in jedem Projekt, in Claude Code.',
    'ob.ev.scope.hint': 'Unsicher? Beginne mit diesem Projekt. Den Rest deines Computers kannst du später schützen, indem du die Einrichtung über die Einstellungen noch einmal durchgehst.',
    'ob.ev.scope.again': 'Einrichtung noch einmal. Nichts wird geschrieben, bevor du fertig bist.',
    'ob.ev.scope.text.again': 'Wähle eines, um zu sehen, was gilt, und es zu ändern.',
    'ob.ev.scope.hint.again': 'Jeder Schritt zeigt, was jetzt eingestellt ist. Geschrieben wird nur, was du änderst, wenn du auf Fertig drückst.',
    'ob.ev.scope.next.project': 'Als Nächstes: drei kurze Schritte. Für wen agentwhy ist, welche Dateien privat sind und wann du Bescheid bekommst.',
    'ob.ev.scope.next.everywhere': 'Als Nächstes: ein Schritt. Die Dateien, die in jedem Projekt von deiner KI ferngehalten werden.',

    'ob.ev.stepper': 'Einrichtungsschritte, alles auf diesem Computer',
    'ob.ev.stepper.choose': 'Auswahl',
    'ob.ev.step': 'Schritt 2 von 2',
    'ob.ev.for': 'Für alles auf diesem Computer',
    'ob.ev.include': 'Hinzufügen',
    'ob.ev.note.blocked': 'Schon in jedem Projekt blockiert',
    'ob.ev.note.tracked': 'Schon in jedem Projekt beobachtet',
    'ob.ev.note.absent': 'Noch nicht auf diesem Computer',
    'ob.ev.files.title': 'Welche Dateien auf diesem Computer sind privat?',
    'ob.ev.files.text': 'Keine davon liegt in einem Projekt. Wähle, was passiert, wenn deine KI auf eine zugreift, in jedem Projekt.',
    'ob.ev.row.ssh': 'Deine Schlüssel für Server-Logins',
    'ob.ev.row.aws': 'Dein Amazon-Web-Services-Login',
    'ob.ev.row.azure': 'Dein Microsoft-Azure-Login',
    'ob.ev.row.gcloud': 'Dein Google-Cloud-Login',
    'ob.ev.row.github': 'Dein GitHub-Login',
    'ob.ev.row.git-credentials': 'Gespeicherte Git-Passwörter',
    'ob.ev.row.gnupg': 'Deine Signaturschlüssel',
    'ob.ev.row.kube': 'Zugang zu deinen Kubernetes-Clustern',
    'ob.ev.row.docker': 'Dein Docker-Login',
    'ob.ev.row.netrc': 'Logins, die andere Werkzeuge gespeichert haben',
    'ob.ev.more.one': 'Noch 1, für ein Werkzeug, das nicht auf diesem Computer ist · Zeigen',
    'ob.ev.more.other': 'Noch {n}, für Werkzeuge, die nicht auf diesem Computer sind · Zeigen',
    'ob.ev.less': 'Weniger zeigen',
    'ob.ev.add': 'Weitere private Datei oder weiteren Ordner hinzufügen',
    'ob.ev.files.hint': 'Unsicher bei einer? Lass sie auf Blockieren. Blockieren stoppt die offensichtlichen Versuche, nicht jeden Trick; wenn etwas durchrutscht, siehst du es trotzdem in deinem Bericht.',
    'ob.ev.count.zero': 'Nichts Neues gewählt',
    'ob.ev.count.one': '1 zu schützen',
    'ob.ev.count.other': '{n} zu schützen',
    'ob.ev.cannot': 'agentwhy konnte deine Claude-Code-Einstellungen nicht lesen, deshalb lässt sich hier nichts ändern. Sobald sie lesbar sind, öffne diese Seite erneut.',

    'ob.ev.confirm.title': 'Diese Dateien auf diesem Computer schützen?',
    'ob.ev.confirm.codex': 'Das gilt in jedem Projekt auf diesem Computer, in Claude Code und in Codex.',
    'ob.ev.confirm.claude': 'Das gilt in jedem Projekt auf diesem Computer, in Claude Code.',
    'ob.ev.confirm.blocked': 'Für deine KI gesperrt',
    'ob.ev.confirm.blocked.text': 'Kein Projekt kann das abschalten, und eine blockierte Datei kann auch nicht gelesen werden, nicht nur nicht geändert.',
    'ob.ev.confirm.blockedN.one': '1 private Datei vor deiner KI geschützt',
    'ob.ev.confirm.blockedN.other': '{n} private Dateien vor deiner KI geschützt',
    'ob.ev.confirm.trackedN.one': '1 Datei, die deine KI lesen darf — du wirst informiert',
    'ob.ev.confirm.trackedN.other': '{n} Dateien, die deine KI lesen darf — du wirst informiert',
    'ob.ev.confirm.tracked': 'Deine KI darf sie lesen, und du erfährst es',
    'ob.ev.confirm.tracked.text': 'agentwhy sagt dir, wenn deine KI eine davon liest.',
    'ob.ev.confirm.check': 'Damit wird auch die Prüfung von agentwhy in Codex eingeschaltet, sodass sich auch Codex daran hält.',
    'ob.ev.confirm.yes': 'Ja, schützen',
    'ob.ev.confirm.later': 'Du kannst jede davon später in den Einstellungen umschalten oder entfernen, unter Private Dateien.',
    'ob.ev.done.later': 'Ändere das später in den {settings}, unter Private Dateien.',
    'ob.ev.done.settings': 'Einstellungen',

    'ob.ev.done.title': 'Dieser Computer ist eingerichtet.',
    'ob.ev.done.where': 'Alles auf diesem Computer',
    'ob.ev.done.blocked.one': '1 Art von Dateien blockiert',
    'ob.ev.done.blocked.other': '{n} Arten von Dateien blockiert',
    'ob.ev.done.tracked.one': '1 beobachtet',
    'ob.ev.done.tracked.other': '{n} beobachtet',
    'ob.ev.done.blockedLine.codex': 'Deine KI kann die blockierten Dateien nicht lesen, in keinem Projekt, weder in Claude Code noch in Codex.',
    'ob.ev.done.blockedLine.claude': 'Deine KI kann die blockierten Dateien nicht lesen, in keinem Projekt, in Claude Code.',
    'ob.ev.done.trackedLine': 'Wenn sie eine beobachtete liest, sagt agentwhy es dir.',
    'ob.ev.done.codexOff': 'Codex ist noch nicht abgedeckt: Die Prüfung von agentwhy ließ sich dort nicht einschalten, deshalb kann Codex diese Dateien noch öffnen.',
    'ob.ev.done.failed.block': 'Die zu blockierenden Dateien konnten nicht geschrieben werden, deshalb sind sie nicht blockiert.',
    'ob.ev.done.failed.tell': 'Die zu beobachtenden Dateien konnten nicht geschrieben werden, deshalb erfährst du nichts über sie.',
    'ob.ev.done.failed.alerts': 'Die Hinweise konnten nicht eingeschaltet werden. Du kannst sie später in den Einstellungen unter Hinweise einschalten.',
    'ob.ev.done.alertsLine': 'Hinweise sind in jedem Projekt an: eine kurze Nachricht im Chat mit Claude Code, wenn deine KI eine private Datei liest.',
    'ob.ev.confirm.alerts': 'Hinweise in jedem Projekt',
    'ob.ev.confirm.alerts.text': 'Eine kurze Nachricht im Chat mit Claude Code, wenn deine KI eine private Datei liest. Ein Projekt mit eigenen Hinweisen bekommt sie nicht doppelt.',
    'ob.ev.done.project.title': '{name} ist noch nicht eingerichtet',
    'ob.ev.done.project.text': 'Diese Regeln gelten für Dateien, die zu keinem Projekt gehören. Die privaten Dateien in {name}, etwa die Passwörter für die laufende App, brauchen eine eigene Einrichtung.',
    'ob.ev.done.project.go': '{name} auch einrichten',
    'ob.ev.done.pick.title': 'Jetzt das Projekt, an dem du arbeitest',
    'ob.ev.done.pick.text': 'Die privaten Dateien in einem Projekt, etwa die Passwörter für die laufende App, brauchen die Einrichtung dieses Projekts.',
    'ob.ev.done.pick.go': 'Projekt wählen →',

    'proj.ev.shown': 'Jetzt gezeigt',
    'app.computer': 'Ansicht',
    'app.computer.name': 'Dieser Computer',
    'proj.ev.held.one': '1 Art von Dateien für deine KI gesperrt, in jedem Projekt',
    'proj.ev.held.other': '{n} Arten von Dateien für deine KI gesperrt, in jedem Projekt',

    // Die Zeilen des Computers in den Einstellungen (Schritt 3): ihr Abzeichen, eine Projektzeile, die er auch blockiert, und ihre Fenster.
    'set.src.short.computer': 'Dieser Computer',
    'set.elsewhere.title': 'Auch auf dem ganzen Computer geschützt',
    'set.elsewhere.lead': 'Diese Regeln kommen von „Dieser Computer“ und gelten in jedem Projekt, auch in diesem. Geändert werden sie dort, nicht hier.',
    'set.elsewhere.go': 'In „Dieser Computer“ ändern →',
    'set.elsewhere.where': 'Ändere sie auf der Seite „Dieser Computer“: Starte agentwhy in deinem Home-Ordner.',
    'set.rule.everywhere': 'Auch in jedem Projekt auf diesem Computer blockiert, deshalb würde Beobachten hier nichts ändern.',
    'set.ev.tell': 'Deine KI das lesen lassen, in jedem Projekt?',
    'set.ev.tell.text': 'Deine KI kann {name} in jedem Projekt auf diesem Computer lesen, und agentwhy sagt dir, wenn sie es tut. Hat sie den Inhalt einmal gesehen, lässt sich das nicht rückgängig machen.',
    'set.ev.block': 'In jedem Projekt blockieren?',
    'set.ev.block.text': 'Deine KI kann {name} in keinem Projekt auf diesem Computer lesen, in Claude Code, und kein Projekt kann das abschalten.',
    'set.ev.block.text.codex': 'Deine KI kann {name} in keinem Projekt auf diesem Computer lesen, weder in Claude Code noch in Codex, und kein Projekt kann das abschalten.',
    'set.ev.unblock': 'Auf diesem Computer nicht mehr schützen?',
    'set.ev.unblock.text': '{name} ist nicht mehr in jedem Projekt für deine KI gesperrt. Ein Projekt, das es selbst schützt, tut das weiterhin.',
    'set.ev.untell': 'Auf diesem Computer nicht mehr beobachten?',
    'set.ev.untell.text': 'agentwhy sagt dir nicht mehr, wenn deine KI {name} liest, in keinem Projekt, es sei denn, ein Projekt beobachtet es selbst.',
    'set.ev.notWritten': 'Nicht jede Änderung an den Regeln dieses Computers ließ sich vornehmen. Lade die Seite neu, um sie so zu sehen, wie sie jetzt sind.',
    'set.ev.add': 'In jedem Projekt schützen?',
    'set.ev.addMany': 'Diese in jedem Projekt vor deiner KI schützen?',
    'set.ev.addMany.text': 'In jedem Projekt auf diesem Computer, und kein Projekt kann das abschalten.',
    'set.place.file': 'Nur diese Datei, wo immer deine KI arbeitet',
    'set.place.folder': 'Dieser Ordner mit allem darin, wo immer deine KI arbeitet',
    'set.place.name': 'Nach dem Namen, und nur im Ordner, in dem deine KI arbeitet',
    'set.ev.stale.one': '1 Regel hier ist auf die alte Art geschrieben: Claude Code wendet sie nur im Ordner an, in dem deine KI arbeitet.',
    'set.ev.stale.other': '{n} Regeln hier sind auf die alte Art geschrieben: Claude Code wendet sie nur im Ordner an, in dem deine KI arbeitet.',
    'set.ev.stale.row': 'Auf die alte Art geschrieben: Sie gilt nur im Ordner, in dem deine KI arbeitet.',
    'set.ev.update': 'Für ihren Ort schreiben?',
    'set.ev.update.text': 'Eine ältere agentwhy-Version hat sie nach dem Namen geschrieben, und Claude Code wendet sie nur im Ordner an, in dem deine KI arbeitet. Für ihren Ort geschrieben, gilt sie überall, wo deine KI arbeitet, und die alte Regel wird entfernt.',
    'set.ev.update.go': 'Aktualisieren',
    'set.ev.updateAll': 'Für ihre Orte schreiben?',
    'set.ev.updateAll.text': 'Eine ältere agentwhy-Version hat sie nach dem Namen geschrieben, und Claude Code wendet sie nur im Ordner an, in dem deine KI arbeitet. Für ihre Orte geschrieben, gelten sie überall, wo deine KI arbeitet, und die alten Regeln werden entfernt.',
    'set.ev.updateAll.go': 'Alle aktualisieren',
    'set.ev.alerts.lead': 'agentwhy fügt deinem Chat mit Claude Code eine kurze Nachricht hinzu, in jedem Projekt auf diesem Computer. Ein Projekt mit eigenen Hinweisen behält sie und bekommt nie zwei. Auf die erste kommt es an; die anderen zwei sind optional und funktionieren nur, wenn sie an ist.',
    'set.ev.state.on': 'An — in jedem Projekt',
    'cs.label': 'Was diese Seite zeigt',
    'cs.outside': 'Außerhalb von Projekten',
    'cs.projects': 'Projekte',
    'cs.say.outside': 'Unterhaltungen aus noch nicht eingerichteten Projekten und aus Chats ohne Projekt.',
    'cs.say.projects': 'Die Unterhaltungen der eingerichteten Projekte, jede mit dem Namen ihres Projekts.',
    'cs.failed': 'Umschalten ging nicht:',
    'cs.kind.none': 'Kein Projekt',
    'cs.kind.notSetUp': 'nicht eingerichtet',
    'set.ev.uninstall.title': 'agentwhy von diesem Computer deinstallieren',
    'set.ev.uninstall.text': 'Entfernt, was für jedes Projekt eingerichtet wurde: die auf diesem Computer blockierten und verfolgten Dateien und die Hinweise in jedem Projekt. Die eigene Einrichtung jedes Projekts bleibt.',
    'set.ev.confirm.uninstall': 'agentwhy von diesem Computer deinstallieren?',
    'set.ev.confirm.uninstall.text': 'Wir entfernen die Dateien, die agentwhy auf diesem Computer blockiert und verfolgt, und schalten die Hinweise in jedem Projekt aus. Deine KI kann diese Dateien wieder öffnen, außer in Projekten, die sie selbst schützen. Die eigene Einrichtung jedes Projekts bleibt, ebenso agentwhys Kontrolle in Codex, die deine Projekte teilen. Eine Regel, die du selbst geschrieben hast, bleibt auch.',
    'set.ev.confirm.alerts.on': 'Hinweise in jedem Projekt einschalten?',
    'set.ev.confirm.alerts.on.text': 'Du bekommst eine kurze Nachricht im Chat mit Claude Code, wenn deine KI etwas Privates liest, in jedem Projekt auf diesem Computer — auch in denen, die du nicht eingerichtet hast. Ein Projekt mit eigenen Hinweisen bekommt sie nicht doppelt.',
    'set.ev.confirm.alerts.off': 'Hinweise in jedem Projekt ausschalten?',
    'set.ev.confirm.alerts.off.text': 'Projekte mit eigenen Hinweisen behalten sie. Überall sonst erfährst du es nicht sofort; du siehst trotzdem alles später in deinem Bericht.',
  },
};
