import type { Lang, Table } from '../../report-copy.ts';

/**
 * What only the This month page says (`.ai/plans/2026-09-23-month-redesign.md`). Everything else on it - the heading,
 * the guide card, the tiles, the lists - is the Conversations page's, in the Conversations page's words.
 */
export const MONTH_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'month.title': 'This month · agentwhy',
    'month.this': 'This month',
    'month.last': 'Last month',
    'month.ago': '{n} months ago',
    'month.hero.zero': 'Your AI didn’t work for you this month.',
    'month.heading': 'Your month',
    'month.earlier': 'An earlier month',
    'month.later': 'A later month',
    'month.back': 'Back to this month',
    'month.pick': 'Choose a month',
    'month.hint': 'Tap a day to see what happened',
    'month.day.count.one': '1 conversation',
    'month.day.count.other': '{n} conversations',
    'month.tip.open': 'Click to see them',
    'month.window.note': 'Private files first, then the rest. Most recent first.',
  },
  pl: {
    'month.title': 'Ten miesiąc · agentwhy',
    'month.this': 'Ten miesiąc',
    'month.last': 'Poprzedni miesiąc',
    'month.ago.few': '{n} miesiące temu',
    'month.ago.many': '{n} miesięcy temu',
    'month.hero.zero': 'W tym miesiącu twoje AI nie pracowało.',
    'month.heading': 'Twój miesiąc',
    'month.earlier': 'Wcześniejszy miesiąc',
    'month.later': 'Późniejszy miesiąc',
    'month.back': 'Wróć do tego miesiąca',
    'month.pick': 'Wybierz miesiąc',
    'month.hint': 'Kliknij dzień, by zobaczyć, co się wydarzyło',
    'month.day.count.one': '1 rozmowa',
    'month.day.count.few': '{n} rozmowy',
    'month.day.count.many': '{n} rozmów',
    'month.tip.open': 'Kliknij, by je zobaczyć',
    'month.window.note': 'Najpierw pliki prywatne, potem reszta. Najnowsze na górze.',
  },
  de: {
    'month.title': 'Dieser Monat · agentwhy',
    'month.this': 'Dieser Monat',
    'month.last': 'Letzter Monat',
    'month.ago': 'vor {n} Monaten',
    'month.hero.zero': 'Deine KI hat diesen Monat nicht für dich gearbeitet.',
    'month.heading': 'Dein Monat',
    'month.earlier': 'Ein früherer Monat',
    'month.later': 'Ein späterer Monat',
    'month.back': 'Zurück zu diesem Monat',
    'month.pick': 'Monat wählen',
    'month.hint': 'Tippe auf einen Tag, um zu sehen, was passiert ist',
    'month.day.count.one': '1 Unterhaltung',
    'month.day.count.other': '{n} Unterhaltungen',
    'month.tip.open': 'Klicke, um sie zu sehen',
    'month.window.note': 'Zuerst private Dateien, dann der Rest. Neueste zuerst.',
  },
};
