// Copyright 2026 Nessprim Karol Kozer
// SPDX-License-Identifier: Apache-2.0
import type { Lang, Table } from '../../report-copy.ts';

/**
 * The words of the onboarding (`.ai/specs/2026-09-24-onboarding.md`), in the glossary of the design guidelines §7. What
 * the onboarding shares with Settings - the rules' names, the three messages, the add popup - is Settings' words, read
 * by their keys, so the two pages cannot say one thing two ways (W28). The intro's files are fixed words, never a file
 * of the person's (W5).
 */
export const ONBOARDING_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'ob.title': 'Welcome · agentwhy',
    'ob.local': 'Runs on your computer',
    'ob.skipIntro': 'Skip intro',

    'ob.intro.working': 'Your AI is helping you with your project…',
    'ob.intro.photos': 'Photos', 'ob.intro.invoices': 'Invoices', 'ob.intro.passwords': 'Passwords', 'ob.intro.contract': 'Contract.pdf',
    'ob.intro.customers': 'Customer list.xlsx', 'ob.intro.notes': 'Notes.docx', 'ob.intro.bank': 'Bank details.pdf', 'ob.intro.website': 'Website',
    'ob.intro.you': 'You',
    'ob.intro.ai': 'Your AI',
    'ob.intro.ask': 'Can you fix my website?',
    'ob.intro.sure': 'Sure, I’m on it.',
    'ob.intro.hidden': 'You don’t see this part',
    'ob.intro.opening': 'I’m opening the file with your <strong>secret keys</strong>…',
    'ob.intro.reading': '…and reading one: {key}',
    'ob.intro.done': 'Done! Your website works again ✓',
    'ob.intro.nobody': 'Nobody asked you.',

    'ob.eyebrow': 'For people who build with an AI agent',
    'ob.h1': 'Your AI opens your files.',
    'ob.h1b': 'Now you’ll know which ones.',
    'ob.lead': 'Set it up once. We’ll tell you whenever Claude Code opens something private.',
    'ob.start': 'Get started →',
    'ob.trust.local': 'Nothing leaves your computer',
    'ob.trust.inside': 'Never shows what’s inside your files',
    'ob.trust.free': 'Free, no account',

    'ob.step': 'Step {n} of 3',
    'ob.stepper': 'Setup steps',
    'ob.stepper.who': 'Who',
    'ob.stepper.files': 'Files',
    'ob.stepper.project': 'Project',
    'ob.back': '← Back',
    'ob.skip': 'Skip',
    'ob.continue': 'Continue →',
    'ob.finish': 'Finish setup →',
    'ob.recommended': 'Recommended',
    'ob.for': 'For {name}',

    'ob.project.title': 'Which project is this for?',
    'ob.project.text': 'agentwhy looks at one project at a time. Pick the one you work on with your AI.',
    'ob.project.home': 'You started agentwhy in your home folder, which isn’t a project. Pick the one you work on with your AI.',
    'ob.project.root': 'You started agentwhy at the root of a disk, which isn’t a project. Pick the one you work on with your AI.',
    'ob.project.hint': 'Not sure? It’s the folder you open in your code editor.',
    'ob.project.pick': 'No, pick another project',
    'ob.project.worked.one': 'Your AI has worked here: 1 chat',
    'ob.project.worked.other': 'Your AI has worked here: {n} chats',
    'ob.project.in.editor': '{n} in your code editor',
    'ob.project.in.terminal': '{n} in the terminal',
    'ob.project.in.desktop': '{n} in the Claude desktop app',
    'ob.project.in.script': '{n} started by a script',
    'ob.project.in.unknown': 'and {n} elsewhere',
    'ob.project.found.title': 'We found your project.',
    'ob.project.found.text': 'This is where you started agentwhy. Is this the right one?',
    'ob.project.found.tag': 'This folder',
    'ob.project.use': 'Yes, use {name} →',
    'ob.project.inside.title': 'You’re inside a project.',
    'ob.project.inside.text': 'You started agentwhy in {place}. Your AI chats are {up}.',
    'ob.project.up.one': 'one folder up',
    'ob.project.up.other': '{n} folders up',
    'ob.project.upTag.one': 'One folder up',
    'ob.project.upTag.other': '{n} folders up',
    'ob.project.includes': 'Includes the {name} folder',
    'ob.project.whole': 'You’re in {here}. We’ll protect all of {name}.',
    'ob.project.useIt': 'Use {name} →',
    'ob.project.inside.hint': 'Protecting the whole project also covers {name}.',
    'ob.project.empty.title': 'Your AI hasn’t worked here yet.',
    'ob.project.empty.text': 'That’s fine if it’s a new project. We’ll start watching from now on.',
    'ob.project.empty.tag': 'No AI chats yet',
    'ob.project.isProject': 'It’s a project folder',
    'ob.project.none': 'No AI chats here yet',
    'ob.project.anyway': 'Use it anyway →',
    'ob.project.empty.hint': 'Expected to see your chats? You may have started agentwhy in the wrong folder.',
    'ob.project.refused.title': 'Pick your project’s folder.',
    'ob.project.refused.home': 'agentwhy doesn’t change settings in your home folder: Claude Code reads the ones there in every project.',
    'ob.project.refused.root': 'agentwhy doesn’t change settings at the root of a disk: it isn’t a project.',
    'ob.project.chatsIn': 'Your AI chats are in {name}.',
    'ob.project.chatsInside': 'Your AI chats are in projects inside {name}.',
    'ob.project.picked': 'You picked {place}. It has no AI chats of its own.',
    'ob.project.weUse': 'We’ll use this project',
    'ob.project.inThere': 'Projects inside it',
    'ob.project.nothingYet': 'It has no AI chats, so there would be nothing to show yet.',
    'ob.project.failed.title': 'That didn’t work.',
    'ob.project.moment': 'One moment. Setup goes on right here.',

    'ob.who.title': 'Who is agentwhy for?',
    'ob.who.text': 'We can watch your AI just for you, or for everyone who works on {name}.',
    'ob.who.local': 'Just me',
    'ob.who.local.sub': 'Only on this computer. Nobody else is affected.',
    'ob.who.shared': 'Everyone on this project',
    'ob.who.shared.sub': 'Anyone who works on this project with Claude Code gets the same protection.',
    'ob.who.you': 'You',
    'ob.who.hint': 'Working alone? Pick “Just me”. You can change this later in Settings.',

    'ob.files.title': 'Which files are private?',
    'ob.files.add': 'Add another private file',
    'ob.files.info': 'What this does',
    'ob.files.hint': 'Keep them all on Block if you’re not sure. Nothing here reads or uploads your files.',

    'ob.change.file': 'Claude Code will be stopped from opening every file called {name}.',
    'ob.change.folder': 'Claude Code will be stopped from opening anything in a folder called {name}.',
    'ob.change.pattern': 'Claude Code will be stopped from opening every file that matches {name}.',
    'ob.change.honest': 'This stops the obvious tries, not every trick. If something slips past, you’ll still see it in your report.',

    'ob.when.h.one': 'in the last hour', 'ob.when.h.other': 'in the last {n} hours',
    'ob.when.d.one': 'in the last day', 'ob.when.d.other': 'in the last {n} days',
    'ob.when.w.one': 'in the last week', 'ob.when.w.other': 'in the last {n} weeks',
    'ob.when.since': 'since {date}',

    'ob.done.files.title': 'Setup done. One thing left.',
    'ob.done.told': 'From now on, you’ll be told right away in Claude Code.',
    'ob.done.notTold': 'Turn on alerts in Settings to be told in Claude Code next time.',
    'ob.done.already.one': 'But {when}, your AI already read 1 private file.',
    'ob.done.already.other': 'But {when}, your AI already read {n} private files.',
    'ob.done.found.one': 'We found 1 file your AI read',
    'ob.done.found.other': 'We found {n} files your AI read',
    'ob.done.keys': 'The keys in them may still work. Change them now.',
    'ob.done.more': '+{n} more on your To fix list',
    'ob.done.later': 'Later — go to my dashboard',
    'ob.done.fix': 'Fix them now — about 2 min each →',
    'ob.done.protected': 'You’re protected.',
    'ob.done.set': 'Setup done.',
    'ob.done.knowing': 'From now on, you’ll know every time Claude Code opens something private.',
    'ob.done.good': 'Good news — nothing to fix.',
    'ob.done.good.text': 'We looked at your AI chats {when}. Your AI didn’t read anything private.',
    'ob.done.gaps': 'We couldn’t check every chat.',
    'ob.done.gaps.go': 'See Conversations',
    'ob.done.open': 'Open agentwhy →',
    'ob.done.empty.title': 'You’re set up.',
    'ob.done.empty.text': 'There are no AI chats in this folder yet. Work with your AI here, then run agentwhy again to see what it opened.',
    'ob.summary.local': 'Just you',
    'ob.summary.shared': 'Everyone on this project',
    'ob.summary.kinds.one': '1 kind of files',
    'ob.summary.kinds.other': '{n} kinds of files',
    'ob.summary.messages': '{n} of 3 messages on',
    'ob.summary.change': 'Change in Settings',
    'ob.failed.watch': 'Alerts weren’t turned on.',
    'ob.failed.protect': 'Your files weren’t added.',
    'ob.failed.notices': 'Your message choices weren’t saved.',
    'ob.failed.search': 'Searches weren’t blocked.',
    'ob.failed.mode': 'Some of your Block and Track choices weren’t saved.',
    'ob.failed.go': 'Try again in Settings',
    'ob.done.codex.on': 'Codex too, from the first message — nothing to confirm there.',
    'ob.done.codex.off': 'Codex isn’t blocked yet: it can still open these files.',
    'ob.done.codex.go': 'Block it in Settings',
    'ob.unrecorded': 'We couldn’t save that you’ve finished this, so you’ll see it again next time.',

    'ob.nojs': 'Your browser isn’t running this page’s script, so nothing can be set up here. Make these choices in Settings.',
    'ob.nojs.settings': 'Open Settings',
    'ob.nojs.conversations': 'Open Conversations',
    'ob.again.title': 'Go through the setup again',
    'ob.again.text': 'The three questions from the start: who agentwhy is for, which files are private, and when to tell you. Nothing changes until you finish.',
    'ob.again.go': 'Start the setup',
  },
  pl: {
    'ob.title': 'Witaj · agentwhy',
    'ob.local': 'Działa na twoim komputerze',
    'ob.skipIntro': 'Pomiń wstęp',

    'ob.intro.working': 'Twoje AI pomaga ci przy projekcie…',
    'ob.intro.photos': 'Zdjęcia', 'ob.intro.invoices': 'Faktury', 'ob.intro.passwords': 'Hasła', 'ob.intro.contract': 'Umowa.pdf',
    'ob.intro.customers': 'Lista klientów.xlsx', 'ob.intro.notes': 'Notatki.docx', 'ob.intro.bank': 'Dane bankowe.pdf', 'ob.intro.website': 'Strona',
    'ob.intro.you': 'Ty',
    'ob.intro.ai': 'Twoje AI',
    'ob.intro.ask': 'Naprawisz mi stronę?',
    'ob.intro.sure': 'Jasne, już się tym zajmuję.',
    'ob.intro.hidden': 'Tej części nie widzisz',
    'ob.intro.opening': 'Otwieram plik z twoimi <strong>tajnymi kluczami</strong>…',
    'ob.intro.reading': '…i czytam jeden z nich: {key}',
    'ob.intro.done': 'Gotowe! Strona znów działa ✓',
    'ob.intro.nobody': 'Nikt cię nie zapytał.',

    'ob.eyebrow': 'Dla osób, które budują z agentem AI',
    'ob.h1': 'Twoje AI otwiera twoje pliki.',
    'ob.h1b': 'Teraz będziesz wiedzieć które.',
    'ob.lead': 'Ustaw raz. Powiemy ci za każdym razem, gdy Claude Code otworzy coś prywatnego.',
    'ob.start': 'Zaczynamy →',
    'ob.trust.local': 'Nic nie opuszcza twojego komputera',
    'ob.trust.inside': 'Nigdy nie pokazuje zawartości twoich plików',
    'ob.trust.free': 'Za darmo, bez konta',

    'ob.step': 'Krok {n} z 3',
    'ob.stepper': 'Kroki ustawień',
    'ob.stepper.who': 'Kto',
    'ob.stepper.files': 'Pliki',
    'ob.stepper.project': 'Projekt',
    'ob.back': '← Wstecz',
    'ob.skip': 'Pomiń',
    'ob.continue': 'Dalej →',
    'ob.finish': 'Zakończ ustawianie →',
    'ob.recommended': 'Polecane',
    'ob.for': 'Projekt {name}',

    'ob.project.title': 'Którego projektu to dotyczy?',
    'ob.project.text': 'agentwhy patrzy na jeden projekt naraz. Wybierz ten, nad którym pracujesz ze swoim AI.',
    'ob.project.home': 'agentwhy uruchomiono w folderze domowym, a to nie projekt. Wybierz ten, nad którym pracujesz ze swoim AI.',
    'ob.project.root': 'agentwhy uruchomiono w katalogu głównym dysku, a to nie projekt. Wybierz ten, nad którym pracujesz ze swoim AI.',
    'ob.project.hint': 'Nie wiesz? To folder, który otwierasz w edytorze kodu.',
    'ob.project.pick': 'Nie, wybierz inny projekt',
    'ob.project.worked.one': 'Twoje AI pracowało tu: 1 czat',
    'ob.project.worked.few': 'Twoje AI pracowało tu: {n} czaty',
    'ob.project.worked.many': 'Twoje AI pracowało tu: {n} czatów',
    'ob.project.in.editor': '{n} w edytorze kodu',
    'ob.project.in.terminal': '{n} w terminalu',
    'ob.project.in.desktop': '{n} w aplikacji Claude na komputerze',
    'ob.project.in.script': '{n} ze skryptu',
    'ob.project.in.unknown': 'i {n} gdzie indziej',
    'ob.project.found.title': 'Znaleźliśmy twój projekt.',
    'ob.project.found.text': 'Tu uruchomiono agentwhy. Czy to właściwy projekt?',
    'ob.project.found.tag': 'Ten folder',
    'ob.project.use': 'Tak, użyj {name} →',
    'ob.project.inside.title': 'Jesteś wewnątrz projektu.',
    'ob.project.inside.text': 'agentwhy uruchomiono w {place}. Twoje czaty z AI są {up}.',
    'ob.project.up.one': 'folder wyżej',
    'ob.project.up.few': '{n} foldery wyżej',
    'ob.project.up.many': '{n} folderów wyżej',
    'ob.project.upTag.one': 'Folder wyżej',
    'ob.project.upTag.few': '{n} foldery wyżej',
    'ob.project.upTag.many': '{n} folderów wyżej',
    'ob.project.includes': 'Obejmuje folder {name}',
    'ob.project.whole': 'Jesteś w {here}. Ochronimy cały projekt {name}.',
    'ob.project.useIt': 'Użyj {name} →',
    'ob.project.inside.hint': 'Ochrona całego projektu obejmuje też {name}.',
    'ob.project.empty.title': 'Twoje AI jeszcze tu nie pracowało.',
    'ob.project.empty.text': 'Jeśli to nowy projekt, wszystko w porządku. Od teraz będziemy pilnować.',
    'ob.project.empty.tag': 'Brak czatów z AI',
    'ob.project.isProject': 'To folder projektu',
    'ob.project.none': 'Nie ma tu jeszcze czatów z AI',
    'ob.project.anyway': 'Użyj mimo to →',
    'ob.project.empty.hint': 'Miały tu być twoje czaty? Może agentwhy uruchomiono w złym folderze.',
    'ob.project.refused.title': 'Wybierz folder projektu.',
    'ob.project.refused.home': 'agentwhy nie zmienia ustawień w folderze domowym: Claude Code czyta je w każdym projekcie.',
    'ob.project.refused.root': 'agentwhy nie zmienia ustawień w katalogu głównym dysku: to nie jest projekt.',
    'ob.project.chatsIn': 'Twoje czaty z AI są w {name}.',
    'ob.project.chatsInside': 'Twoje czaty z AI są w projektach wewnątrz {name}.',
    'ob.project.picked': 'Wybrano {place}. Nie ma tam własnych czatów z AI.',
    'ob.project.weUse': 'Użyjemy tego projektu',
    'ob.project.inThere': 'Projekty w środku',
    'ob.project.nothingYet': 'Nie ma tam czatów z AI, więc na razie nie byłoby czego pokazać.',
    'ob.project.failed.title': 'To się nie udało.',
    'ob.project.moment': 'Chwila. Ustawianie trwa dalej tutaj.',

    'ob.who.title': 'Dla kogo jest agentwhy?',
    'ob.who.text': 'Możemy pilnować twojego AI tylko dla ciebie albo dla wszystkich, którzy pracują nad projektem {name}.',
    'ob.who.local': 'Tylko ja',
    'ob.who.local.sub': 'Tylko na tym komputerze. Nikogo innego to nie dotyczy.',
    'ob.who.shared': 'Wszyscy w tym projekcie',
    'ob.who.shared.sub': 'Każdy, kto pracuje nad tym projektem w Claude Code, dostaje tę samą ochronę.',
    'ob.who.you': 'Ty',
    'ob.who.hint': 'Pracujesz sam? Wybierz „Tylko ja”. Możesz to później zmienić w Ustawieniach.',

    'ob.files.title': 'Które pliki są prywatne?',
    'ob.files.add': 'Dodaj kolejny prywatny plik',
    'ob.files.info': 'Co to robi',
    'ob.files.hint': 'Jeśli nie masz pewności, zostaw wszystkie na Blokuj. Nic tutaj nie czyta ani nie wysyła twoich plików.',

    'ob.change.file': 'Claude Code nie otworzy żadnego pliku o nazwie {name}.',
    'ob.change.folder': 'Claude Code nie otworzy niczego w folderze o nazwie {name}.',
    'ob.change.pattern': 'Claude Code nie otworzy żadnego pliku pasującego do {name}.',
    'ob.change.honest': 'To zatrzymuje oczywiste próby, nie każdą sztuczkę. Jeśli coś się prześlizgnie, i tak zobaczysz to w raporcie.',

    'ob.when.h.one': 'w ciągu ostatniej godziny', 'ob.when.h.few': 'w ciągu ostatnich {n} godzin', 'ob.when.h.many': 'w ciągu ostatnich {n} godzin',
    'ob.when.d.one': 'w ciągu ostatniego dnia', 'ob.when.d.few': 'w ciągu ostatnich {n} dni', 'ob.when.d.many': 'w ciągu ostatnich {n} dni',
    'ob.when.w.one': 'w ciągu ostatniego tygodnia', 'ob.when.w.few': 'w ciągu ostatnich {n} tygodni', 'ob.when.w.many': 'w ciągu ostatnich {n} tygodni',
    'ob.when.since': 'od {date}',

    'ob.done.files.title': 'Gotowe. Została jedna rzecz.',
    'ob.done.told': 'Od teraz dowiesz się od razu w Claude Code.',
    'ob.done.notTold': 'Włącz powiadomienia w Ustawieniach, żeby następnym razem dowiedzieć się w Claude Code.',
    'ob.done.already.one': 'Ale {when} twoje AI przeczytało już 1 prywatny plik.',
    'ob.done.already.few': 'Ale {when} twoje AI przeczytało już {n} prywatne pliki.',
    'ob.done.already.many': 'Ale {when} twoje AI przeczytało już {n} prywatnych plików.',
    'ob.done.found.one': 'Znaleźliśmy 1 plik, który przeczytało twoje AI',
    'ob.done.found.few': 'Znaleźliśmy {n} pliki, które przeczytało twoje AI',
    'ob.done.found.many': 'Znaleźliśmy {n} plików, które przeczytało twoje AI',
    'ob.done.keys': 'Klucze w nich mogą wciąż działać. Zmień je teraz.',
    'ob.done.more': '+{n} więcej na liście Do naprawy',
    'ob.done.later': 'Później — przejdź do pulpitu',
    'ob.done.fix': 'Napraw je teraz — ok. 2 min każdy →',
    'ob.done.protected': 'Jesteś pod ochroną.',
    'ob.done.set': 'Gotowe.',
    'ob.done.knowing': 'Od teraz będziesz wiedzieć za każdym razem, gdy Claude Code otworzy coś prywatnego.',
    'ob.done.good': 'Dobra wiadomość — nie ma nic do naprawy.',
    'ob.done.good.text': 'Przejrzeliśmy twoje czaty z AI {when}. Twoje AI nie przeczytało niczego prywatnego.',
    'ob.done.gaps': 'Nie udało się sprawdzić każdego czatu.',
    'ob.done.gaps.go': 'Zobacz Rozmowy',
    'ob.done.open': 'Otwórz agentwhy →',
    'ob.done.empty.title': 'Wszystko ustawione.',
    'ob.done.empty.text': 'W tym folderze nie ma jeszcze czatów z AI. Popracuj tu ze swoim AI, a potem uruchom agentwhy jeszcze raz, żeby zobaczyć, co otworzyło.',
    'ob.summary.local': 'Tylko ty',
    'ob.summary.shared': 'Wszyscy w tym projekcie',
    'ob.summary.kinds.one': '1 rodzaj plików',
    'ob.summary.kinds.few': '{n} rodzaje plików',
    'ob.summary.kinds.many': '{n} rodzajów plików',
    'ob.summary.messages': 'Wiadomości: {n} z 3',
    'ob.summary.change': 'Zmień w Ustawieniach',
    'ob.failed.watch': 'Powiadomienia nie zostały włączone.',
    'ob.failed.protect': 'Twoje pliki nie zostały dodane.',
    'ob.failed.notices': 'Twoje wybory wiadomości nie zostały zapisane.',
    'ob.failed.search': 'Przeszukiwanie nie zostało zablokowane.',
    'ob.failed.mode': 'Część twoich wyborów Blokuj i Obserwuje nie została zapisana.',
    'ob.failed.go': 'Spróbuj ponownie w Ustawieniach',
    'ob.done.codex.on': 'Także Codex, od pierwszej wiadomości — niczego nie musisz tam potwierdzać.',
    'ob.done.codex.off': 'Codex nie jest jeszcze zablokowany: wciąż może otwierać te pliki.',
    'ob.done.codex.go': 'Zablokuj go w Ustawieniach',
    'ob.unrecorded': 'Nie udało się zapisać, że to zakończyłeś, więc zobaczysz to jeszcze raz następnym razem.',

    'ob.nojs': 'Twoja przeglądarka nie uruchamia skryptu tej strony, więc niczego tu nie ustawisz. Dokonaj tych wyborów w Ustawieniach.',
    'ob.nojs.settings': 'Otwórz Ustawienia',
    'ob.nojs.conversations': 'Otwórz Rozmowy',
    'ob.again.title': 'Przejdź konfigurację jeszcze raz',
    'ob.again.text': 'Te same trzy pytania co na początku: dla kogo jest agentwhy, które pliki są prywatne i kiedy dać ci znać. Nic się nie zmieni, dopóki nie skończysz.',
    'ob.again.go': 'Zacznij konfigurację',
  },
  de: {
    'ob.title': 'Willkommen · agentwhy',
    'ob.local': 'Läuft auf deinem Computer',
    'ob.skipIntro': 'Intro überspringen',

    'ob.intro.working': 'Deine KI hilft dir bei deinem Projekt…',
    'ob.intro.photos': 'Fotos', 'ob.intro.invoices': 'Rechnungen', 'ob.intro.passwords': 'Passwörter', 'ob.intro.contract': 'Vertrag.pdf',
    'ob.intro.customers': 'Kundenliste.xlsx', 'ob.intro.notes': 'Notizen.docx', 'ob.intro.bank': 'Bankdaten.pdf', 'ob.intro.website': 'Website',
    'ob.intro.you': 'Du',
    'ob.intro.ai': 'Deine KI',
    'ob.intro.ask': 'Kannst du meine Website reparieren?',
    'ob.intro.sure': 'Klar, ich kümmere mich darum.',
    'ob.intro.hidden': 'Diesen Teil siehst du nicht',
    'ob.intro.opening': 'Ich öffne die Datei mit deinen <strong>geheimen Schlüsseln</strong>…',
    'ob.intro.reading': '…und lese einen davon: {key}',
    'ob.intro.done': 'Fertig! Deine Website läuft wieder ✓',
    'ob.intro.nobody': 'Niemand hat dich gefragt.',

    'ob.eyebrow': 'Für Menschen, die mit einem KI-Agenten bauen',
    'ob.h1': 'Deine KI öffnet deine Dateien.',
    'ob.h1b': 'Jetzt weißt du, welche.',
    'ob.lead': 'Einmal einrichten. Wir sagen dir jedes Mal Bescheid, wenn Claude Code etwas Privates öffnet.',
    'ob.start': 'Los geht’s →',
    'ob.trust.local': 'Nichts verlässt deinen Computer',
    'ob.trust.inside': 'Zeigt nie, was in deinen Dateien steht',
    'ob.trust.free': 'Kostenlos, kein Konto',

    'ob.step': 'Schritt {n} von 3',
    'ob.stepper': 'Einrichtungsschritte',
    'ob.stepper.who': 'Wer',
    'ob.stepper.files': 'Dateien',
    'ob.stepper.project': 'Projekt',
    'ob.back': '← Zurück',
    'ob.skip': 'Überspringen',
    'ob.continue': 'Weiter →',
    'ob.finish': 'Einrichtung abschließen →',
    'ob.recommended': 'Empfohlen',
    'ob.for': 'Für {name}',

    'ob.project.title': 'Für welches Projekt ist das?',
    'ob.project.text': 'agentwhy schaut sich immer ein Projekt an. Wähle das, an dem du mit deiner KI arbeitest.',
    'ob.project.home': 'Du hast agentwhy in deinem Home-Ordner gestartet, und der ist kein Projekt. Wähle das, an dem du mit deiner KI arbeitest.',
    'ob.project.root': 'Du hast agentwhy im Hauptverzeichnis eines Laufwerks gestartet, und das ist kein Projekt. Wähle das, an dem du mit deiner KI arbeitest.',
    'ob.project.hint': 'Nicht sicher? Es ist der Ordner, den du in deinem Code-Editor öffnest.',
    'ob.project.pick': 'Nein, anderes Projekt wählen',
    'ob.project.worked.one': 'Deine KI hat hier gearbeitet: 1 Chat',
    'ob.project.worked.other': 'Deine KI hat hier gearbeitet: {n} Chats',
    'ob.project.in.editor': '{n} im Code-Editor',
    'ob.project.in.terminal': '{n} im Terminal',
    'ob.project.in.desktop': '{n} in der Claude-Desktop-App',
    'ob.project.in.script': '{n} von einem Skript gestartet',
    'ob.project.in.unknown': 'und {n} anderswo',
    'ob.project.found.title': 'Wir haben dein Projekt gefunden.',
    'ob.project.found.text': 'Hier hast du agentwhy gestartet. Ist es das richtige?',
    'ob.project.found.tag': 'Dieser Ordner',
    'ob.project.use': 'Ja, {name} nehmen →',
    'ob.project.inside.title': 'Du bist in einem Projekt.',
    'ob.project.inside.text': 'Du hast agentwhy in {place} gestartet. Deine KI-Chats liegen {up}.',
    'ob.project.up.one': 'einen Ordner höher',
    'ob.project.up.other': '{n} Ordner höher',
    'ob.project.upTag.one': 'Ein Ordner höher',
    'ob.project.upTag.other': '{n} Ordner höher',
    'ob.project.includes': 'Enthält den Ordner {name}',
    'ob.project.whole': 'Du bist in {here}. Wir schützen das ganze Projekt {name}.',
    'ob.project.useIt': '{name} nehmen →',
    'ob.project.inside.hint': 'Wenn das ganze Projekt geschützt ist, gilt das auch für {name}.',
    'ob.project.empty.title': 'Deine KI hat hier noch nicht gearbeitet.',
    'ob.project.empty.text': 'Wenn es ein neues Projekt ist, ist das in Ordnung. Ab jetzt behalten wir es im Blick.',
    'ob.project.empty.tag': 'Noch keine KI-Chats',
    'ob.project.isProject': 'Es ist ein Projektordner',
    'ob.project.none': 'Hier gibt es noch keine KI-Chats',
    'ob.project.anyway': 'Trotzdem nehmen →',
    'ob.project.empty.hint': 'Hast du deine Chats erwartet? Vielleicht hast du agentwhy im falschen Ordner gestartet.',
    'ob.project.refused.title': 'Wähle den Ordner deines Projekts.',
    'ob.project.refused.home': 'agentwhy ändert keine Einstellungen in deinem Home-Ordner: Claude Code liest die dortigen in jedem Projekt.',
    'ob.project.refused.root': 'agentwhy ändert keine Einstellungen im Hauptverzeichnis eines Laufwerks: es ist kein Projekt.',
    'ob.project.chatsIn': 'Deine KI-Chats liegen in {name}.',
    'ob.project.chatsInside': 'Deine KI-Chats liegen in Projekten in {name}.',
    'ob.project.picked': 'Du hast {place} gewählt. Dort gibt es keine eigenen KI-Chats.',
    'ob.project.weUse': 'Wir nehmen dieses Projekt',
    'ob.project.inThere': 'Projekte darin',
    'ob.project.nothingYet': 'Dort gibt es keine KI-Chats, also gäbe es noch nichts zu zeigen.',
    'ob.project.failed.title': 'Das hat nicht geklappt.',
    'ob.project.moment': 'Einen Moment. Die Einrichtung geht gleich hier weiter.',

    'ob.who.title': 'Für wen ist agentwhy?',
    'ob.who.text': 'Wir können deine KI nur für dich im Blick behalten oder für alle, die an {name} arbeiten.',
    'ob.who.local': 'Nur ich',
    'ob.who.local.sub': 'Nur auf diesem Computer. Niemand sonst ist betroffen.',
    'ob.who.shared': 'Alle in diesem Projekt',
    'ob.who.shared.sub': 'Alle, die mit Claude Code an diesem Projekt arbeiten, bekommen denselben Schutz.',
    'ob.who.you': 'Du',
    'ob.who.hint': 'Du arbeitest allein? Wähle „Nur ich“. Du kannst das später in den Einstellungen ändern.',

    'ob.files.title': 'Welche Dateien sind privat?',
    'ob.files.add': 'Weitere private Datei hinzufügen',
    'ob.files.info': 'Was das bewirkt',
    'ob.files.hint': 'Wenn du unsicher bist, lass alle auf Blockieren. Nichts hier liest oder lädt deine Dateien hoch.',

    'ob.change.file': 'Claude Code wird daran gehindert, eine Datei namens {name} zu öffnen.',
    'ob.change.folder': 'Claude Code wird daran gehindert, etwas in einem Ordner namens {name} zu öffnen.',
    'ob.change.pattern': 'Claude Code wird daran gehindert, eine Datei zu öffnen, die zu {name} passt.',
    'ob.change.honest': 'Das stoppt die offensichtlichen Versuche, nicht jeden Trick. Wenn etwas durchrutscht, siehst du es trotzdem in deinem Bericht.',

    'ob.when.h.one': 'in der letzten Stunde', 'ob.when.h.other': 'in den letzten {n} Stunden',
    'ob.when.d.one': 'am letzten Tag', 'ob.when.d.other': 'in den letzten {n} Tagen',
    'ob.when.w.one': 'in der letzten Woche', 'ob.when.w.other': 'in den letzten {n} Wochen',
    'ob.when.since': 'seit {date}',

    'ob.done.files.title': 'Eingerichtet. Eine Sache noch.',
    'ob.done.told': 'Ab jetzt erfährst du es sofort in Claude Code.',
    'ob.done.notTold': 'Schalte die Hinweise in den Einstellungen ein, um es nächstes Mal in Claude Code zu erfahren.',
    'ob.done.already.one': 'Aber {when} hat deine KI schon 1 private Datei gelesen.',
    'ob.done.already.other': 'Aber {when} hat deine KI schon {n} private Dateien gelesen.',
    'ob.done.found.one': 'Wir haben 1 Datei gefunden, die deine KI gelesen hat',
    'ob.done.found.other': 'Wir haben {n} Dateien gefunden, die deine KI gelesen hat',
    'ob.done.keys': 'Die Schlüssel darin funktionieren vielleicht noch. Ändere sie jetzt.',
    'ob.done.more': '+{n} weitere auf deiner Liste Zu beheben',
    'ob.done.later': 'Später — zu meiner Übersicht',
    'ob.done.fix': 'Jetzt beheben — etwa 2 Min. pro Datei →',
    'ob.done.protected': 'Du bist geschützt.',
    'ob.done.set': 'Eingerichtet.',
    'ob.done.knowing': 'Ab jetzt weißt du jedes Mal, wenn Claude Code etwas Privates öffnet.',
    'ob.done.good': 'Gute Nachricht — nichts zu beheben.',
    'ob.done.good.text': 'Wir haben deine KI-Chats {when} angesehen. Deine KI hat nichts Privates gelesen.',
    'ob.done.gaps': 'Wir konnten nicht jeden Chat prüfen.',
    'ob.done.gaps.go': 'Unterhaltungen ansehen',
    'ob.done.open': 'agentwhy öffnen →',
    'ob.done.empty.title': 'Alles eingerichtet.',
    'ob.done.empty.text': 'In diesem Ordner gibt es noch keine KI-Chats. Arbeite hier mit deiner KI und starte agentwhy dann noch einmal, um zu sehen, was sie geöffnet hat.',
    'ob.summary.local': 'Nur du',
    'ob.summary.shared': 'Alle in diesem Projekt',
    'ob.summary.kinds.one': '1 Art von Dateien',
    'ob.summary.kinds.other': '{n} Arten von Dateien',
    'ob.summary.messages': '{n} von 3 Nachrichten an',
    'ob.summary.change': 'In den Einstellungen ändern',
    'ob.failed.watch': 'Die Hinweise wurden nicht eingeschaltet.',
    'ob.failed.protect': 'Deine Dateien wurden nicht hinzugefügt.',
    'ob.failed.notices': 'Deine Auswahl der Nachrichten wurde nicht gespeichert.',
    'ob.failed.search': 'Die Suchen wurden nicht blockiert.',
    'ob.failed.mode': 'Ein Teil deiner Auswahl zwischen Blockieren und Beobachten wurde nicht gespeichert.',
    'ob.failed.go': 'In den Einstellungen noch einmal versuchen',
    'ob.done.codex.on': 'Auch Codex, von der ersten Nachricht an — dort musst du nichts bestätigen.',
    'ob.done.codex.off': 'Codex ist noch nicht blockiert: Es kann diese Dateien noch öffnen.',
    'ob.done.codex.go': 'In den Einstellungen blockieren',
    'ob.unrecorded': 'Wir konnten nicht speichern, dass du fertig bist, deshalb siehst du das nächstes Mal noch einmal.',

    'ob.nojs': 'Dein Browser führt das Skript dieser Seite nicht aus, deshalb lässt sich hier nichts einrichten. Triff diese Auswahl in den Einstellungen.',
    'ob.nojs.settings': 'Einstellungen öffnen',
    'ob.nojs.conversations': 'Unterhaltungen öffnen',
    'ob.again.title': 'Die Einrichtung noch einmal durchgehen',
    'ob.again.text': 'Die drei Fragen vom Anfang: für wen agentwhy ist, welche Dateien privat sind und wann wir dir Bescheid sagen. Nichts ändert sich, bevor du fertig bist.',
    'ob.again.go': 'Einrichtung starten',
  },
};
