// Copyright 2026 Nessprim Karol Kozer
// SPDX-License-Identifier: Apache-2.0
import type { Lang, Table } from '../../report-copy.ts';

/**
 * The words of the window that switches projects (`.ai/specs/2026-09-27-which-project.md` V10-V15, V25), in the glossary's
 * words: *project* is the thing, *folder* where it is on disk. A project is *set up*, never *protected*: the list knows
 * whether agentwhy runs there, not what each file is set to (V10, W33). Close is the app's.
 */
export const PROJECTS_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'proj.title': 'Switch project',
    'proj.lead': 'Pick the project you want agentwhy to watch.',
    'proj.here': 'You’re here now',
    'proj.others': 'Other projects · newest first',
    'proj.yours': 'Your projects · newest first',
    'moved.pageTitle': 'Another project · agentwhy',
    'moved.title': 'This page was for {was}.',
    'moved.text': 'agentwhy now shows {now}. It shows one project at a time.',
    'moved.back': 'Show {was} again',
    'moved.stay': 'Go to {now}',
    'moved.noScript': 'Turn on scripts in your browser to show {was} again from here.',
    'proj.startedIn': 'Where you started agentwhy',
    'proj.startedHere': 'Started here',
    'proj.in': 'in {place}',
    'proj.inHome': 'in your home folder',
    'proj.more.one': 'Show 1 more project',
    'proj.more.other': 'Show {n} more projects',
    'proj.hidden': 'Hidden: {what}',
    'proj.hidden.temporary.one': '1 temporary folder',
    'proj.hidden.temporary.other': '{n} temporary folders',
    'proj.hidden.gone.one': '1 that no longer exists',
    'proj.hidden.gone.other': '{n} that no longer exist',
    'proj.search': 'Search projects',
    'proj.noMatch': 'No project matches “{q}”.',
    'proj.col.project': 'Project',
    'proj.col.status': 'Status',
    'proj.card': 'Switch project',
    'proj.setUp': 'Set up',
    'proj.notSetUp': 'Not set up yet',
    'proj.open': 'Open',
    'proj.setItUp': 'Set it up →',
    'proj.used': 'Last used {when}',
    'proj.ago.now': 'just now',
    'proj.ago.minutes.one': '1 minute ago',
    'proj.ago.minutes.other': '{n} minutes ago',
    'proj.ago.hours.one': '1 hour ago',
    'proj.ago.hours.other': '{n} hours ago',
    'proj.ago.yesterday': 'yesterday',
    'proj.chats.one': '1 AI chat',
    'proj.chats.other': '{n} AI chats',
    'proj.gone': 'This folder isn’t there anymore',
    'proj.goneFold.one': '1 project can’t be found anymore',
    'proj.goneFold.other': '{n} projects can’t be found anymore',
    'proj.missing.title': 'Don’t see your project?',
    'proj.missing.text': 'We only list folders where you used Claude Code or Codex.',
    'proj.missing.how': 'Open your project’s folder in your code editor and start a chat with Claude Code or Codex there - then it shows up here.',
    'proj.choose': 'Choose a folder…',
    'proj.choosePrompt': 'Choose your project’s folder',
    'proj.chooseHome': 'Your home folder isn’t a project. Choose your project’s folder.',
    'proj.chooseRoot': 'The top of a disk isn’t a project. Choose your project’s folder.',
    'proj.chooseHere': 'That’s the project you’re in now.',
    'proj.nearAbove': 'Your AI chats are in {name}.',
    'proj.nearInside': 'These projects are inside {name}:',
    'proj.openName': 'Open {name}',
    'proj.useAnyway': 'Use {name} anyway',
    'proj.which': 'agentwhy reads your conversations with Claude Code - in the terminal and in your code editor - and with Codex. It protects files in both. It doesn’t see Cursor’s own AI or chats on claude.ai.',
    'proj.switching': 'Switching to {name}…',
    'proj.switchFailed': 'Couldn’t switch. {reason}',
    'proj.unreachable': 'agentwhy isn’t running anymore. Run agentwhy again to switch.',
    'proj.noScript': 'Turn on scripts in your browser to switch projects from here.',
    'proj.unreadable.one': '1 more project couldn’t be read.',
    'proj.unreadable.other': '{n} more projects couldn’t be read.',
    'proj.older.one': '1 older project',
    'proj.older.other': '{n} older projects',
    'proj.none': 'No other projects yet. Work with Claude Code or Codex in another folder, and it shows up here.',
  },
  pl: {
    'proj.title': 'Zmień projekt',
    'proj.lead': 'Wybierz projekt, który agentwhy ma obserwować.',
    'proj.here': 'Jesteś tutaj',
    'proj.others': 'Inne projekty · od najnowszych',
    'proj.yours': 'Twoje projekty · od najnowszych',
    'moved.pageTitle': 'Inny projekt · agentwhy',
    'moved.title': 'Ta strona była dla projektu {was}.',
    'moved.text': 'agentwhy pokazuje teraz {now}. Pokazuje jeden projekt naraz.',
    'moved.back': 'Pokaż znowu {was}',
    'moved.stay': 'Przejdź do {now}',
    'moved.noScript': 'Włącz skrypty w przeglądarce, żeby stąd znowu pokazać {was}.',
    'proj.startedIn': 'Tu uruchomiono agentwhy',
    'proj.startedHere': 'Uruchomiono tu',
    'proj.in': 'w {place}',
    'proj.inHome': 'w folderze domowym',
    'proj.more.one': 'Pokaż jeszcze 1 projekt',
    'proj.more.few': 'Pokaż jeszcze {n} projekty',
    'proj.more.many': 'Pokaż jeszcze {n} projektów',
    'proj.hidden': 'Ukryte: {what}',
    'proj.hidden.temporary.one': '1 folder tymczasowy',
    'proj.hidden.temporary.few': '{n} foldery tymczasowe',
    'proj.hidden.temporary.many': '{n} folderów tymczasowych',
    'proj.hidden.gone.one': '1, którego już nie ma',
    'proj.hidden.gone.few': '{n}, których już nie ma',
    'proj.hidden.gone.many': '{n}, których już nie ma',
    'proj.search': 'Szukaj projektu',
    'proj.noMatch': 'Żaden projekt nie pasuje do „{q}”.',
    'proj.col.project': 'Projekt',
    'proj.col.status': 'Stan',
    'proj.card': 'Zmień projekt',
    'proj.setUp': 'Ustawiony',
    'proj.notSetUp': 'Jeszcze nieustawiony',
    'proj.open': 'Otwórz',
    'proj.setItUp': 'Ustaw →',
    'proj.used': 'Ostatnio {when}',
    'proj.ago.now': 'przed chwilą',
    'proj.ago.minutes.one': '1 minutę temu',
    'proj.ago.minutes.few': '{n} minuty temu',
    'proj.ago.minutes.many': '{n} minut temu',
    'proj.ago.hours.one': '1 godzinę temu',
    'proj.ago.hours.few': '{n} godziny temu',
    'proj.ago.hours.many': '{n} godzin temu',
    'proj.ago.yesterday': 'wczoraj',
    'proj.chats.one': '1 czat z AI',
    'proj.chats.few': '{n} czaty z AI',
    'proj.chats.many': '{n} czatów z AI',
    'proj.gone': 'Tego folderu już nie ma',
    'proj.goneFold.one': '1 projektu nie da się już znaleźć',
    'proj.goneFold.few': '{n} projektów nie da się już znaleźć',
    'proj.goneFold.many': '{n} projektów nie da się już znaleźć',
    'proj.missing.title': 'Nie widzisz swojego projektu?',
    'proj.missing.text': 'Pokazujemy tylko foldery z czatami Claude Code lub Codexa.',
    'proj.missing.how': 'Otwórz folder projektu w edytorze kodu i zacznij tam czat z Claude Code lub Codexem - wtedy pojawi się tutaj.',
    'proj.choose': 'Wybierz folder…',
    'proj.choosePrompt': 'Wybierz folder swojego projektu',
    'proj.chooseHome': 'Folder domowy to nie projekt. Wybierz folder projektu.',
    'proj.chooseRoot': 'Główny katalog dysku to nie projekt. Wybierz folder projektu.',
    'proj.chooseHere': 'To projekt, w którym jesteś.',
    'proj.nearAbove': 'Twoje czaty z AI są w {name}.',
    'proj.nearInside': 'W folderze {name} są te projekty:',
    'proj.openName': 'Otwórz {name}',
    'proj.useAnyway': 'Użyj mimo to: {name}',
    'proj.which': 'agentwhy czyta Twoje rozmowy z Claude Code - w terminalu i w edytorze kodu - oraz z Codexem. Chroni pliki w obu. Nie widzi własnego AI Cursora ani czatów na claude.ai.',
    'proj.switching': 'Przełączam na {name}…',
    'proj.switchFailed': 'Nie udało się przełączyć. {reason}',
    'proj.unreachable': 'agentwhy już nie działa. Uruchom agentwhy jeszcze raz, żeby przełączyć.',
    'proj.noScript': 'Włącz skrypty w przeglądarce, żeby przełączać tu projekty.',
    'proj.unreadable.one': 'Nie udało się odczytać jeszcze 1 projektu.',
    'proj.unreadable.few': 'Nie udało się odczytać jeszcze {n} projektów.',
    'proj.unreadable.many': 'Nie udało się odczytać jeszcze {n} projektów.',
    'proj.older.one': '1 starszy projekt',
    'proj.older.few': '{n} starsze projekty',
    'proj.older.many': '{n} starszych projektów',
    'proj.none': 'Nie ma jeszcze innych projektów. Popracuj z Claude Code lub Codexem w innym folderze, a pojawi się tutaj.',
  },
  de: {
    'proj.title': 'Projekt wechseln',
    'proj.lead': 'Wähle das Projekt, das agentwhy beobachten soll.',
    'proj.here': 'Hier bist du gerade',
    'proj.others': 'Andere Projekte · die neuesten zuerst',
    'proj.yours': 'Deine Projekte · die neuesten zuerst',
    'moved.pageTitle': 'Anderes Projekt · agentwhy',
    'moved.title': 'Diese Seite war für {was}.',
    'moved.text': 'agentwhy zeigt jetzt {now}. Es zeigt immer ein Projekt.',
    'moved.back': '{was} wieder zeigen',
    'moved.stay': 'Zu {now}',
    'moved.noScript': 'Schalte Skripte im Browser ein, um {was} von hier aus wieder zu zeigen.',
    'proj.startedIn': 'Hier hast du agentwhy gestartet',
    'proj.startedHere': 'Hier gestartet',
    'proj.in': 'in {place}',
    'proj.inHome': 'im Home-Ordner',
    'proj.more.one': 'Noch 1 Projekt zeigen',
    'proj.more.other': 'Noch {n} Projekte zeigen',
    'proj.hidden': 'Ausgeblendet: {what}',
    'proj.hidden.temporary.one': '1 temporärer Ordner',
    'proj.hidden.temporary.other': '{n} temporäre Ordner',
    'proj.hidden.gone.one': '1, den es nicht mehr gibt',
    'proj.hidden.gone.other': '{n}, die es nicht mehr gibt',
    'proj.search': 'Projekt suchen',
    'proj.noMatch': 'Kein Projekt passt zu „{q}“.',
    'proj.col.project': 'Projekt',
    'proj.col.status': 'Status',
    'proj.card': 'Projekt wechseln',
    'proj.setUp': 'Eingerichtet',
    'proj.notSetUp': 'Noch nicht eingerichtet',
    'proj.open': 'Öffnen',
    'proj.setItUp': 'Einrichten →',
    'proj.used': 'Zuletzt {when}',
    'proj.ago.now': 'gerade eben',
    'proj.ago.minutes.one': 'vor 1 Minute',
    'proj.ago.minutes.other': 'vor {n} Minuten',
    'proj.ago.hours.one': 'vor 1 Stunde',
    'proj.ago.hours.other': 'vor {n} Stunden',
    'proj.ago.yesterday': 'gestern',
    'proj.chats.one': '1 KI-Chat',
    'proj.chats.other': '{n} KI-Chats',
    'proj.gone': 'Diesen Ordner gibt es nicht mehr',
    'proj.goneFold.one': '1 Projekt ist nicht mehr zu finden',
    'proj.goneFold.other': '{n} Projekte sind nicht mehr zu finden',
    'proj.missing.title': 'Du siehst dein Projekt nicht?',
    'proj.missing.text': 'Wir zeigen nur Ordner, in denen du Claude Code oder Codex benutzt hast.',
    'proj.missing.how': 'Öffne den Ordner deines Projekts im Code-Editor und starte dort einen Chat mit Claude Code oder Codex - dann erscheint er hier.',
    'proj.choose': 'Ordner wählen …',
    'proj.choosePrompt': 'Wähle den Ordner deines Projekts',
    'proj.chooseHome': 'Dein Home-Ordner ist kein Projekt. Wähle den Ordner deines Projekts.',
    'proj.chooseRoot': 'Die oberste Ebene eines Laufwerks ist kein Projekt. Wähle den Ordner deines Projekts.',
    'proj.chooseHere': 'Das ist das Projekt, in dem du gerade bist.',
    'proj.nearAbove': 'Deine KI-Chats liegen in {name}.',
    'proj.nearInside': 'In {name} liegen diese Projekte:',
    'proj.openName': '{name} öffnen',
    'proj.useAnyway': '{name} trotzdem nehmen',
    'proj.which': 'agentwhy liest deine Gespräche mit Claude Code - im Terminal und in deinem Code-Editor - und mit Codex. Dateien schützt es in beiden. Die eigene KI von Cursor und Chats auf claude.ai sieht es nicht.',
    'proj.switching': 'Wechsle zu {name} …',
    'proj.switchFailed': 'Wechseln hat nicht geklappt. {reason}',
    'proj.unreachable': 'agentwhy läuft nicht mehr. Starte agentwhy erneut, um zu wechseln.',
    'proj.noScript': 'Schalte Skripte im Browser ein, um hier das Projekt zu wechseln.',
    'proj.unreadable.one': '1 weiteres Projekt konnte nicht gelesen werden.',
    'proj.unreadable.other': '{n} weitere Projekte konnten nicht gelesen werden.',
    'proj.older.one': '1 älteres Projekt',
    'proj.older.other': '{n} ältere Projekte',
    'proj.none': 'Noch keine anderen Projekte. Arbeite in einem anderen Ordner mit Claude Code oder Codex, dann erscheint er hier.',
  },
};
