import type { Lang, Table } from '../../report-copy.ts';

/**
 * The words of the Settings page (`for-people-who-build-with-ai.md` §3 C, §7.1), in the glossary of the design
 * guidelines §7. The developer details keep the tool's own words (F41), and the answers under "Ask me" are written in
 * advance (F43): each says only what the tool does, never what it cannot know.
 */
export const SETTINGS_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'set.title': 'Settings · agentwhy',
    'set.eyebrow': 'Settings',
    'set.hero': 'We picked safe choices for you.',
    'set.lead': 'Change something only if you want to.',
    'set.cannot': 'Your project’s settings file couldn’t be read, so nothing can be changed here. Fix the file, then open this page again.',
    'set.tab.alerts': 'Alerts',
    'set.tab.files': 'Private files',
    'set.tab.general': 'General',

    'set.alerts.title': 'When should we tell you?',
    'set.alerts.lead': 'agentwhy adds a short note to your Claude Code chat. The first one matters most. The other two are optional and only work when the first is on.',
    'set.alerts.optional': 'Optional — turn on or off as you like',
    'set.card.read.name': 'When my AI reads a private file',
    'set.card.read.badge': 'Default · recommended',
    'set.card.optional': 'Optional',
    'set.card.read.when': 'So you can change the keys the same day, before anyone uses them. You’ll see what to do.',
    'set.card.read.answer': 'Heads up: while working, I read the passwords for your live app. See what to do →',
    'set.card.stopped.name': 'When my AI is stopped from opening a private file',
    'set.card.stopped.when': 'So you know a block held: your AI tried to open a blocked file and was stopped in time. You’ll only see this for files you block.',
    'set.card.stopped.answer': 'I tried to open your passwords file, but it’s blocked — nothing was read.',
    'set.card.fine.name': 'Once per conversation, even when all is fine',
    'set.card.fine.when': 'Peace of mind: a quick sign that we’re watching.',
    'set.card.fine.answer': 'All good — I didn’t open anything private.',
    'set.chat.ai': 'AI',
    'set.state.local': 'On — for just you',
    'set.state.shared': 'On — for everyone on this project',
    'set.state.on': 'On',
    'set.state.off': 'Off',
    'set.need': 'First turn on “When my AI reads a private file”. This one only works with it on.',
    'set.need.go': 'Turn on the first one',
    'set.notices.unusable': 'Your message choices couldn’t be read, so they can’t be changed here.',
    'set.general.title': 'Who are these settings for?',
    'set.general.lead': 'Your private files and protection. Pick who they apply to.',
    'set.general.local': 'Just me',
    'set.general.local.sub': 'Only on this computer. Others on this project don’t get them.',
    'set.general.shared': 'Everyone on this project',
    'set.general.shared.sub': 'Saved with the project, so everyone gets the same protection.',
    'set.general.current': 'Current',
    'set.general.you': 'You',
    'set.general.mixed': '<strong>Some of your settings are for just you, and some for everyone on this project.</strong> <span class="set-soft">Choose one, and we’ll move the rest there.</span>',
    'set.general.none': 'Nothing is saved yet. What you turn on is for just you.',
    'set.general.note': 'Your alert choices are always just for you.',
    'set.uninstall.title': 'Uninstall agentwhy',
    'set.uninstall.text': 'Turns everything off and removes agentwhy from this project. Your own files are not touched.',
    'set.uninstall.go': 'Uninstall…',

    'set.unread.one': '<strong>Your project marks 1 more file as private.</strong> <span class="set-soft">We haven’t been watching it yet.</span>',
    'set.unread.other': '<strong>Your project marks {n} more files as private.</strong> <span class="set-soft">We haven’t been watching them yet.</span>',
    'set.unwatched': '<strong>Some files we keep private aren’t watched yet.</strong> <span class="set-soft">Your project has a list of its own now, and they aren’t on it.</span>',
    'set.watch.one': 'Watch it too',
    'set.watch.other': 'Watch them too',
    'set.files.title': 'What counts as private',
    'set.files.lead': 'For each one, pick what happens when Claude Code tries to open it.',
    'set.rule.env': 'Passwords and keys',
    'set.rule.env.sub': 'Files like .env that connect your app to other services',
    'set.rule.npmrc': 'App install passwords',
    'set.rule.npmrc.sub': 'The .npmrc file',
    'set.rule.secrets': 'Secret folders',
    'set.rule.secrets.sub': 'Anything inside a folder called secrets',
    'set.rule.ssh': 'Computer login keys',
    'set.rule.ssh.sub': 'SSH keys that let you into servers',
    'set.rule.sub.you': 'You added this',
    'set.rule.sub.project': 'From your project',
    'set.rule.notWatched': 'Not watched yet',
    'set.rule.watch': 'Start watching',
    'set.src.agentwhy': 'Added by agentwhy',
    'set.src.project': 'From your project',
    'set.src.you': 'Added by you',
    'set.col.src': 'Added by',
    'set.col.act': 'Action',
    'set.src.short.agentwhy': 'agentwhy',
    'set.src.short.you': 'You',
    'set.src.short.project': 'Your project',
    'set.rule.own.file': 'A private file',
    'set.rule.own.folder': 'A private folder',
    'set.rule.own.pattern': 'Private files that match',
    'set.remove': 'Remove',
    'set.add': 'Add a private file',
    'set.legend.block': 'Claude Code can’t open it',
    'set.legend.tell': 'it can read it, you’ll be told',
    'set.col.file': 'File',
    'set.count.block': '<b class="set-count-n">{n}</b> blocked',
    'set.count.tell': '<b class="set-count-n">{n}</b> tracked',
    'set.finish.gap.one': '<strong>1 private file isn’t fully blocked.</strong> <span class="set-soft">Claude Code can still read what’s inside it.</span>',
    'set.finish.gap.other': '<strong>{n} private files aren’t fully blocked.</strong> <span class="set-soft">Claude Code can still read what’s inside them.</span>',
    'set.finish.go': 'Finish blocking',
    'set.finish.title': 'Finish blocking your private files?',
    'set.finish.text.one': 'Claude Code won’t be able to open {names} or search through it.',
    'set.finish.text.other': 'Claude Code won’t be able to open {names} or search through them.',
    'set.finish.yes.one': 'Yes, block it',
    'set.finish.yes.other': 'Yes, block them',
    'set.finish.honest': 'This stops the obvious tries, not every trick. If something slips past, you’ll still see it in your report.',
    'set.rule.gap.open': 'Not fully blocked — Claude Code can still read what’s inside with a search or a command.',
    'set.rule.gap.none': 'Not blocked yet — Claude Code can still open it.',
    'set.codex.off': '<strong>Codex isn’t blocked yet.</strong> <span class="set-soft">It can still open and search through the files blocked here.</span>',
    'set.codex.go': 'Block in Codex too',
    'set.codex.on': 'Codex is kept from the same files once you approve agentwhy in Codex. Until then, Codex doesn’t block anything.',
    'set.codex.title': 'Block these files in Codex too?',
    'set.codex.text': 'Codex won’t be able to open the files blocked here or search through them, once you approve agentwhy in Codex. Until then, it doesn’t block anything.',
    'set.codex.yes': 'Yes, block them in Codex',
    'set.exceptions.one': '1 exception — see the details for your developer.',
    'set.exceptions.other': '{n} exceptions — see the details for your developer.',


    'set.confirm.alerts.on': 'Turn on alerts?',
    'set.confirm.alerts.on.text': 'You’ll get a short message in your Claude Code chat when it reads something private.',
    'set.confirm.alerts.off': 'Turn off alerts?',
    'set.confirm.alerts.off.text': 'You won’t be told right away. You’ll still see everything later in your report.',
    'set.confirm.turnOn': 'Turn on',
    'set.confirm.turnOff': 'Turn off',
    'set.confirm.scope.local': 'Make these settings just for you?',
    'set.confirm.scope.local.text': 'We’ll move your private files, alerts and protection to this computer only. Others who work on this project won’t get them any more.',
    'set.confirm.scope.shared': 'Make these settings for everyone on this project?',
    'set.confirm.scope.shared.text': 'We’ll save your private files, alerts and protection with the project. Everyone who works on it gets them, wherever the project goes.',
    'set.confirm.scope.go': 'Yes, switch',
    'set.confirm.uninstall': 'Uninstall agentwhy from this project?',
    'set.confirm.uninstall.text': 'We’ll turn off alerts and search protection, and take out the private files agentwhy added. Your AI can open them again, and you won’t be told. Your own files are not touched.',
    'set.confirm.uninstall.go': 'Yes, uninstall',
    'set.confirm.add': 'Protect this file?',
    'set.confirm.add.file': 'This protects every file called {name} in your project.',
    'set.confirm.add.folder': 'This protects everything inside every folder called {name} in your project.',
    'set.confirm.add.pattern': 'This protects every file that matches {name} in your project.',
    'set.confirm.add.also': 'Claude Code won’t be able to open it or search through it.',
    'set.confirm.add.go': 'Yes, protect it',
    'set.confirm.watch': 'Watch these too?',
    'set.confirm.watch.text': 'We’ll watch the files your project already marks as private, and Claude Code will be stopped from opening or searching through them.',
    'set.confirm.watch.go': 'Yes, watch them',
    'set.confirm.row': 'Start watching these files?',
    'set.confirm.row.text': 'We’ll watch {name}, and Claude Code will be stopped from opening or searching through them.',
    'set.confirm.builtIn': 'The files we already watch are written into your project with it, so none of them stops being watched.',
    'set.confirm.everyone': 'Everyone on this project gets this change.',
    'set.confirm.remove': 'Stop protecting this?',
    'set.confirm.remove.text': 'We’ll stop watching {name}, and your AI can open it without asking.',
    'set.confirm.remove.go': 'Remove',
    'set.mode.label': 'When your AI reaches it',
    'set.mode.block': 'Block',
    'set.mode.tell': 'Track',
    'set.confirm.tell.secret': 'Let your AI read your passwords and keys?',
    'set.confirm.tell.secret.text': 'Your AI will be able to read {name}. Once it has seen them, you can’t take that back. The only fix is to change these passwords or keys. You’ll get a message in Claude Code every time.',
    'set.confirm.tell': 'Let your AI read this file?',
    'set.confirm.tell.text': 'Your AI will be able to open {name}. It will read what’s inside and have that information. You’ll get a message in Claude Code each time it happens.',
    'set.confirm.tell.alertsOff': 'Alerts are off, so you’ll only see it in your report.',
    'set.confirm.tell.go': 'Yes, just track it',
    'set.confirm.block': 'Block this file?',
    'set.confirm.block.text': 'Claude Code won’t be able to open {name} or search through it.',
    'set.confirm.block.go': 'Yes, block it',
    'set.confirm.untell': 'Stop watching this file?',
    'set.confirm.untell.text': '{name} won’t be private any more: your AI can open it, and you won’t be told.',
    'set.saving': 'Saving…',
    'set.refused': 'That didn’t work:',
    'set.asFile': 'This page was opened as a file, so it can’t change anything. To do it, run this in your project:',
    'set.unreachable': 'The page could not reach agentwhy start - it may have stopped. Run it again.',

    'set.add.title': 'Add a private file',
    'set.add.lead': 'Pick it on your computer. Claude Code won’t be able to open it.',
    'set.add.file': 'Choose a file',
    'set.add.file.eg': 'e.g. contract.pdf',
    'set.add.folder': 'Choose a folder',
    'set.add.folder.eg': 'e.g. data/',
    'set.add.type': 'Or type the name',
    'set.add.placeholder': 'contract.pdf or data/',
    'set.add.go': 'Add',

    'set.ask.title': 'Not sure what to pick? Ask me.',
    'set.ask.alerts.1': 'Should I turn on alerts?',
    'set.ask.alerts.1.a': 'Yes, for most people.\nWhen your AI reads something private, you hear about it in the same chat, while you can still act.\nNothing is blocked. Your AI keeps working.',
    'set.ask.alerts.2': 'What do I do when I get one?',
    'set.ask.alerts.2.a': 'Change the keys in that file.\nThe message says which file it was and what to do.\nYour AI asks if you want to see the report. It opens only if you say yes.',
    'set.ask.alerts.3': 'Who else sees these messages?',
    'set.ask.alerts.3.a': 'Only you and your AI.\nThe message appears in your AI chat, so your AI reads it too - that is how it can tell you.\nIt names the file, never what is inside it.\nWith “Everyone on this project”, each person gets the same messages in their own chat.',
    'set.ask.files.1': 'What is a .env file?',
    'set.ask.files.1.a': 'A file where apps keep passwords and keys.\nFor example, the key that lets your app take payments.\nIf your AI reads it, it has seen those keys.',
    'set.ask.files.2': 'Should I add my contracts?',
    'set.ask.files.2.a': 'Yes, if they hold something you wouldn’t paste into a chat.\nThe same goes for customer lists and IDs.\nOnce a file is added, you’ll know if your AI opens it.',
    'set.ask.files.3': 'Does agentwhy read my files?',
    'set.ask.files.3.a': 'No.\nagentwhy reads your AI’s own record of the conversation, on this computer, to see which files it opened.\nWhen you pick a file here, only its name is used.',
    'set.ask.general.1': 'Just me or everyone?',
    'set.ask.general.1.a': 'Just me, if you work alone.\nEveryone on this project, if others work on it with their own AI - then they are protected too.\nYou can switch any time: nothing is lost and nothing is turned off.',
    'set.ask.general.2': 'What does uninstall delete?',
    'set.ask.general.2.a': 'Only what agentwhy added to this project: alerts, search protection and the private files it protects.\nRules your project wrote by hand stay, and so do your files and your reports.\nYour alert choices and your Track list are kept too, in case you come back.',
    'set.ask.general.3': 'Can I install it again?',
    'set.ask.general.3.a': 'Yes, any time.\nTurn alerts and protection back on here, or run npx @agentwhy/cli init in your project.\nFiles you added yourself need to be added again.',

    'set.dev': 'Details for your developer',
    'set.dev.watch': 'Alerts (agentwhy watch) run from',
    'set.dev.refuse': 'Search protection (agentwhy refuse) runs from',
    'set.dev.reads': 'The hooks read rules from',
    'set.dev.reads.default': 'the built-in list',
    'set.dev.reads.policy': 'a policy file (--policy)',
    'set.dev.reads.other': 'another settings file (--settings)',
    'set.dev.rules': 'Private file rules',
    'set.dev.unread': 'Project rules not read',
    'set.dev.exceptions': 'Exceptions',
    'set.dev.notices': 'Message options saved in',
    'set.dev.on': 'Tell me from (--on)',
    'set.dev.clean': 'When nothing happened (--clean)',
    'set.dev.said': 'Said by · shown in',
    'set.dev.none': 'none',
    'set.dev.notInstalled': 'not installed',
    'set.dev.unknown': 'unknown - the project settings file could not be read',
    'set.state.unknown': 'Couldn’t be read',
    'set.shared': 'This page was shared, so it shows none of the settings of the computer that made it.',
    'set.add.cannot': 'This name has characters that work as wildcards, so it can’t be protected exactly. Rename the file, or ask your developer to add it.',
  },
  pl: {
    'set.title': 'Ustawienia · agentwhy',
    'set.eyebrow': 'Ustawienia',
    'set.hero': 'Wybraliśmy za ciebie bezpieczne ustawienia.',
    'set.lead': 'Zmień coś tylko wtedy, gdy chcesz.',
    'set.cannot': 'Nie udało się odczytać pliku ustawień twojego projektu, więc nic nie da się tu zmienić. Popraw plik i otwórz tę stronę ponownie.',
    'set.tab.alerts': 'Powiadomienia',
    'set.tab.files': 'Pliki prywatne',
    'set.tab.general': 'Ogólne',

    'set.alerts.title': 'Kiedy mamy ci powiedzieć?',
    'set.alerts.lead': 'agentwhy dopisuje krótką wiadomość do twojego czatu z Claude Code. Pierwsza jest najważniejsza. Pozostałe dwie są opcjonalne i działają tylko wtedy, gdy pierwsza jest włączona.',
    'set.alerts.optional': 'Opcjonalne — włącz albo wyłącz, jak wolisz',
    'set.card.read.name': 'Gdy moje AI przeczyta prywatny plik',
    'set.card.read.badge': 'Domyślne · polecane',
    'set.card.optional': 'Opcjonalne',
    'set.card.read.when': 'Żeby zmienić klucze tego samego dnia, zanim ktoś ich użyje. Zobaczysz, co zrobić.',
    'set.card.read.answer': 'Uwaga: w trakcie pracy przeczytałem hasła do twojej działającej aplikacji. Zobacz, co zrobić →',
    'set.card.stopped.name': 'Gdy moje AI zostanie zatrzymane przed otwarciem prywatnego pliku',
    'set.card.stopped.when': 'Wiesz wtedy, że blokada zadziałała: AI próbowało otworzyć zablokowany plik i zostało zatrzymane w porę. Zobaczysz to tylko przy plikach, które blokujesz.',
    'set.card.stopped.answer': 'Próbowałem otworzyć twój plik z hasłami, ale jest zablokowany — nic nie zostało przeczytane.',
    'set.card.fine.name': 'Raz na rozmowę, nawet gdy wszystko jest w porządku',
    'set.card.fine.when': 'Dla spokoju: krótki znak, że czuwamy.',
    'set.card.fine.answer': 'Wszystko w porządku — nie otwierałem niczego prywatnego.',
    'set.chat.ai': 'AI',
    'set.state.local': 'Włączone — tylko dla ciebie',
    'set.state.shared': 'Włączone — dla wszystkich w projekcie',
    'set.state.on': 'Włączone',
    'set.state.off': 'Wyłączone',
    'set.need': 'Najpierw włącz „Gdy moje AI przeczyta prywatny plik”. Ta opcja działa tylko razem z nią.',
    'set.need.go': 'Włącz pierwszą',
    'set.notices.unusable': 'Nie udało się odczytać twoich wyborów wiadomości, więc nie da się ich tu zmienić.',
    'set.general.title': 'Dla kogo są te ustawienia?',
    'set.general.lead': 'Twoje prywatne pliki i ochrona. Wybierz, kogo dotyczą.',
    'set.general.local': 'Tylko dla mnie',
    'set.general.local.sub': 'Tylko na tym komputerze. Inni w tym projekcie ich nie dostaną.',
    'set.general.shared': 'Dla wszystkich w projekcie',
    'set.general.shared.sub': 'Zapisane razem z projektem, więc wszyscy mają tę samą ochronę.',
    'set.general.current': 'Obecnie',
    'set.general.you': 'Ty',
    'set.general.mixed': '<strong>Część ustawień jest tylko dla ciebie, a część dla wszystkich w projekcie.</strong> <span class="set-soft">Wybierz jedno, a przeniesiemy tam resztę.</span>',
    'set.general.none': 'Nic jeszcze nie jest zapisane. To, co włączysz, będzie tylko dla ciebie.',
    'set.general.note': 'Twoje wybory powiadomień są zawsze tylko dla ciebie.',
    'set.uninstall.title': 'Odinstaluj agentwhy',
    'set.uninstall.text': 'Wyłącza wszystko i usuwa agentwhy z tego projektu. Twoje własne pliki zostają nietknięte.',
    'set.uninstall.go': 'Odinstaluj…',

    'set.unread.one': '<strong>Twój projekt oznacza jeszcze 1 plik jako prywatny.</strong> <span class="set-soft">Nie pilnowaliśmy go do tej pory.</span>',
    'set.unread.few': '<strong>Twój projekt oznacza jeszcze {n} pliki jako prywatne.</strong> <span class="set-soft">Nie pilnowaliśmy ich do tej pory.</span>',
    'set.unread.many': '<strong>Twój projekt oznacza jeszcze {n} plików jako prywatne.</strong> <span class="set-soft">Nie pilnowaliśmy ich do tej pory.</span>',
    'set.unwatched': '<strong>Niektóre pliki, które uznajemy za prywatne, nie są jeszcze pilnowane.</strong> <span class="set-soft">Twój projekt ma teraz własną listę i ich na niej nie ma.</span>',
    'set.watch.one': 'Pilnuj go też',
    'set.watch.few': 'Pilnuj ich też',
    'set.watch.many': 'Pilnuj ich też',
    'set.files.title': 'Co jest prywatne',
    'set.files.lead': 'Dla każdego wybierz, co się stanie, gdy Claude Code spróbuje go otworzyć.',
    'set.rule.env': 'Hasła i klucze',
    'set.rule.env.sub': 'Pliki takie jak .env, które łączą twoją aplikację z innymi usługami',
    'set.rule.npmrc': 'Hasła do instalowania pakietów',
    'set.rule.npmrc.sub': 'Plik .npmrc',
    'set.rule.secrets': 'Tajne foldery',
    'set.rule.secrets.sub': 'Wszystko w folderze o nazwie secrets',
    'set.rule.ssh': 'Klucze logowania do komputerów',
    'set.rule.ssh.sub': 'Klucze SSH, którymi logujesz się na serwery',
    'set.rule.sub.you': 'Dodane przez ciebie',
    'set.rule.sub.project': 'Z twojego projektu',
    'set.rule.notWatched': 'Jeszcze niepilnowane',
    'set.rule.watch': 'Zacznij pilnować',
    'set.src.agentwhy': 'Dodane przez agentwhy',
    'set.src.project': 'Z twojego projektu',
    'set.src.you': 'Dodane przez ciebie',
    'set.col.src': 'Dodane przez',
    'set.col.act': 'Akcja',
    'set.src.short.agentwhy': 'agentwhy',
    'set.src.short.you': 'Ty',
    'set.src.short.project': 'Twój projekt',
    'set.rule.own.file': 'Prywatny plik',
    'set.rule.own.folder': 'Prywatny folder',
    'set.rule.own.pattern': 'Prywatne pliki pasujące do wzorca',
    'set.remove': 'Usuń',
    'set.add': 'Dodaj prywatny plik',
    'set.legend.block': 'Claude Code nie może go otworzyć',
    'set.legend.tell': 'może go przeczytać, a ty się o tym dowiesz',
    'set.col.file': 'Plik',
    'set.count.block.one': '<b class="set-count-n">{n}</b> zablokowany',
    'set.count.block.few': '<b class="set-count-n">{n}</b> zablokowane',
    'set.count.block.many': '<b class="set-count-n">{n}</b> zablokowanych',
    'set.count.tell.one': '<b class="set-count-n">{n}</b> obserwowany',
    'set.count.tell.few': '<b class="set-count-n">{n}</b> obserwowane',
    'set.count.tell.many': '<b class="set-count-n">{n}</b> obserwowanych',
    'set.finish.gap.one': '<strong>1 prywatny plik nie jest w pełni zablokowany.</strong> <span class="set-soft">Claude Code wciąż może przeczytać jego zawartość.</span>',
    'set.finish.gap.few': '<strong>{n} prywatne pliki nie są w pełni zablokowane.</strong> <span class="set-soft">Claude Code wciąż może przeczytać ich zawartość.</span>',
    'set.finish.gap.many': '<strong>{n} prywatnych plików nie jest w pełni zablokowanych.</strong> <span class="set-soft">Claude Code wciąż może przeczytać ich zawartość.</span>',
    'set.finish.go': 'Dokończ blokowanie',
    'set.finish.title': 'Dokończyć blokowanie prywatnych plików?',
    'set.finish.text.one': 'Claude Code nie będzie mógł otworzyć {names} ani tego przeszukać.',
    'set.finish.text.few': 'Claude Code nie będzie mógł otworzyć {names} ani ich przeszukać.',
    'set.finish.text.many': 'Claude Code nie będzie mógł otworzyć {names} ani ich przeszukać.',
    'set.finish.yes.one': 'Tak, zablokuj',
    'set.finish.yes.few': 'Tak, zablokuj je',
    'set.finish.yes.many': 'Tak, zablokuj je',
    'set.finish.honest': 'To zatrzymuje oczywiste próby, nie każdą sztuczkę. Jeśli coś się prześlizgnie, i tak zobaczysz to w raporcie.',
    'set.rule.gap.open': 'Nie w pełni zablokowane — Claude Code wciąż może przeczytać zawartość przez przeszukiwanie albo komendę.',
    'set.rule.gap.none': 'Jeszcze niezablokowane — Claude Code wciąż może to otworzyć.',
    'set.codex.off': '<strong>Codex nie jest jeszcze zablokowany.</strong> <span class="set-soft">Wciąż może otwierać i przeszukiwać pliki zablokowane tutaj.</span>',
    'set.codex.go': 'Zablokuj też w Codexie',
    'set.codex.on': 'Codex nie dostanie się do tych samych plików, gdy zatwierdzisz agentwhy w Codexie. Do tego czasu Codex niczego nie blokuje.',
    'set.codex.title': 'Zablokować te pliki także w Codexie?',
    'set.codex.text': 'Codex nie będzie mógł otwierać plików zablokowanych tutaj ani ich przeszukiwać, gdy zatwierdzisz agentwhy w Codexie. Do tego czasu niczego nie blokuje.',
    'set.codex.yes': 'Tak, zablokuj w Codexie',
    'set.exceptions.one': '1 wyjątek — szczegóły w sekcji dla twojego programisty.',
    'set.exceptions.few': '{n} wyjątki — szczegóły w sekcji dla twojego programisty.',
    'set.exceptions.many': '{n} wyjątków — szczegóły w sekcji dla twojego programisty.',


    'set.confirm.alerts.on': 'Włączyć powiadomienia?',
    'set.confirm.alerts.on.text': 'Dostaniesz krótką wiadomość w czacie z Claude Code, gdy przeczyta coś prywatnego.',
    'set.confirm.alerts.off': 'Wyłączyć powiadomienia?',
    'set.confirm.alerts.off.text': 'Nie dowiesz się od razu. Wszystko i tak zobaczysz później w raporcie.',
    'set.confirm.turnOn': 'Włącz',
    'set.confirm.turnOff': 'Wyłącz',
    'set.confirm.scope.local': 'Ustawienia tylko dla ciebie?',
    'set.confirm.scope.local.text': 'Przeniesiemy twoje prywatne pliki, powiadomienia i ochronę tylko na ten komputer. Inne osoby pracujące nad projektem przestaną je dostawać.',
    'set.confirm.scope.shared': 'Ustawienia dla wszystkich w projekcie?',
    'set.confirm.scope.shared.text': 'Zapiszemy twoje prywatne pliki, powiadomienia i ochronę razem z projektem. Dostanie je każdy, kto nad nim pracuje, gdziekolwiek trafi projekt.',
    'set.confirm.scope.go': 'Tak, przełącz',
    'set.confirm.uninstall': 'Odinstalować agentwhy z tego projektu?',
    'set.confirm.uninstall.text': 'Wyłączymy powiadomienia i ochronę przed przeszukiwaniem oraz usuniemy prywatne pliki dodane przez agentwhy. Twoje AI znów będzie mogło je otwierać i nie dostaniesz o tym wiadomości. Twoje własne pliki zostają nietknięte.',
    'set.confirm.uninstall.go': 'Tak, odinstaluj',
    'set.confirm.add': 'Chronić ten plik?',
    'set.confirm.add.file': 'To chroni każdy plik o nazwie {name} w twoim projekcie.',
    'set.confirm.add.folder': 'To chroni wszystko w każdym folderze o nazwie {name} w twoim projekcie.',
    'set.confirm.add.pattern': 'To chroni każdy plik pasujący do {name} w twoim projekcie.',
    'set.confirm.add.also': 'Claude Code nie będzie mógł go otworzyć ani przeszukać.',
    'set.confirm.add.go': 'Tak, chroń go',
    'set.confirm.watch': 'Pilnować też tych?',
    'set.confirm.watch.text': 'Będziemy pilnować plików, które twój projekt już oznacza jako prywatne, a Claude Code nie będzie mógł ich otwierać ani przeszukiwać.',
    'set.confirm.watch.go': 'Tak, pilnuj ich',
    'set.confirm.row': 'Zacząć pilnować tych plików?',
    'set.confirm.row.text': 'Będziemy pilnować {name}, a Claude Code nie będzie mógł ich otwierać ani przeszukiwać.',
    'set.confirm.builtIn': 'Pliki, których już pilnujemy, zostaną zapisane w projekcie razem z nim, więc żaden nie przestanie być pilnowany.',
    'set.confirm.everyone': 'Ta zmiana dotyczy wszystkich w projekcie.',
    'set.confirm.remove': 'Przestać to chronić?',
    'set.confirm.remove.text': 'Przestaniemy pilnować {name}, a twoje AI będzie mogło to otworzyć bez pytania.',
    'set.confirm.remove.go': 'Usuń',
    'set.mode.label': 'Gdy Twoje AI po niego sięgnie',
    'set.mode.block': 'Blokuj',
    'set.mode.tell': 'Obserwuje',
    'set.confirm.tell.secret': 'Pozwolić AI czytać twoje hasła i klucze?',
    'set.confirm.tell.secret.text': 'Twoje AI będzie mogło przeczytać {name}. Gdy raz je zobaczy, nie da się tego cofnąć. Jedyne wyjście to zmienić te hasła lub klucze. Za każdym razem dostaniesz wiadomość w Claude Code.',
    'set.confirm.tell': 'Pozwolić AI czytać ten plik?',
    'set.confirm.tell.text': 'Twoje AI będzie mogło otworzyć {name}. Przeczyta to, co jest w środku, i będzie miało te informacje. Za każdym razem dostaniesz wiadomość w Claude Code.',
    'set.confirm.tell.alertsOff': 'Powiadomienia są wyłączone, więc zobaczysz to tylko w raporcie.',
    'set.confirm.tell.go': 'Tak, tylko obserwuj',
    'set.confirm.block': 'Zablokować ten plik?',
    'set.confirm.block.text': 'Claude Code nie będzie mógł otworzyć {name} ani go przeszukać.',
    'set.confirm.block.go': 'Tak, zablokuj',
    'set.confirm.untell': 'Przestać pilnować tego pliku?',
    'set.confirm.untell.text': '{name} nie będzie już prywatny: twoje AI może go otwierać i nie dostaniesz o tym wiadomości.',
    'set.saving': 'Zapisuję…',
    'set.refused': 'Nie udało się:',
    'set.asFile': 'Ta strona została otwarta jako plik, więc niczego nie zmieni. Żeby to zrobić, uruchom w swoim projekcie:',
    'set.unreachable': 'Strona nie mogła połączyć się z agentwhy start - mógł się zatrzymać. Uruchom go ponownie.',

    'set.add.title': 'Dodaj prywatny plik',
    'set.add.lead': 'Wybierz go na swoim komputerze. Claude Code nie będzie mógł go otworzyć.',
    'set.add.file': 'Wybierz plik',
    'set.add.file.eg': 'np. umowa.pdf',
    'set.add.folder': 'Wybierz folder',
    'set.add.folder.eg': 'np. dane/',
    'set.add.type': 'Albo wpisz nazwę',
    'set.add.placeholder': 'umowa.pdf albo dane/',
    'set.add.go': 'Dodaj',

    'set.ask.title': 'Nie wiesz, co wybrać? Zapytaj mnie.',
    'set.ask.alerts.1': 'Czy powinienem włączyć powiadomienia?',
    'set.ask.alerts.1.a': 'Tak, dla większości osób.\nGdy twoje AI przeczyta coś prywatnego, dowiesz się o tym w tym samym czacie, póki jeszcze możesz coś zrobić.\nNic nie jest blokowane. AI dalej pracuje.',
    'set.ask.alerts.2': 'Co mam zrobić, gdy dostanę taką wiadomość?',
    'set.ask.alerts.2.a': 'Zmień klucze w tym pliku.\nWiadomość mówi, który to był plik i co zrobić.\nAI zapyta, czy chcesz zobaczyć raport. Otworzy go tylko, jeśli się zgodzisz.',
    'set.ask.alerts.3': 'Kto jeszcze widzi te wiadomości?',
    'set.ask.alerts.3.a': 'Tylko ty i twoje AI.\nWiadomość pojawia się w czacie z AI, więc AI też ją czyta - dzięki temu może ci o tym powiedzieć.\nPodaje nazwę pliku, nigdy jego zawartość.\nPrzy „Dla wszystkich w projekcie” każdy dostaje takie same wiadomości w swoim czacie.',
    'set.ask.files.1': 'Co to jest plik .env?',
    'set.ask.files.1.a': 'Plik, w którym aplikacje trzymają hasła i klucze.\nNa przykład klucz, dzięki któremu twoja aplikacja przyjmuje płatności.\nJeśli AI go przeczyta, widziało te klucze.',
    'set.ask.files.2': 'Czy dodać moje umowy?',
    'set.ask.files.2.a': 'Tak, jeśli jest w nich coś, czego nie wkleiłbyś do czatu.\nTo samo dotyczy list klientów i dokumentów tożsamości.\nPo dodaniu pliku dowiesz się, jeśli AI go otworzy.',
    'set.ask.files.3': 'Czy agentwhy czyta moje pliki?',
    'set.ask.files.3.a': 'Nie.\nagentwhy czyta zapis rozmowy, który prowadzi samo AI, na tym komputerze, żeby zobaczyć, jakie pliki otworzyło.\nGdy wybierasz tu plik, używana jest tylko jego nazwa.',
    'set.ask.general.1': 'Tylko ja czy wszyscy?',
    'set.ask.general.1.a': 'Tylko dla mnie, jeśli pracujesz sam.\nDla wszystkich w projekcie, jeśli inni też nad nim pracują ze swoim AI - wtedy oni też są chronieni.\nMożesz to zmienić w każdej chwili: nic nie zginie i nic się nie wyłączy.',
    'set.ask.general.2': 'Co usuwa odinstalowanie?',
    'set.ask.general.2.a': 'Tylko to, co agentwhy dodał do tego projektu: powiadomienia, ochronę przed przeszukiwaniem i chronione przez niego prywatne pliki.\nReguły, które projekt zapisał ręcznie, zostają - tak jak twoje pliki i raporty.\nTwoje wybory powiadomień i lista „Obserwuje” też zostają, na wypadek powrotu.',
    'set.ask.general.3': 'Czy mogę zainstalować go ponownie?',
    'set.ask.general.3.a': 'Tak, w każdej chwili.\nWłącz tutaj z powrotem powiadomienia i ochronę albo uruchom npx @agentwhy/cli init w swoim projekcie.\nPliki dodane przez ciebie trzeba dodać jeszcze raz.',

    'set.dev': 'Szczegóły dla twojego programisty',
    'set.dev.watch': 'Powiadomienia (agentwhy watch) działają z',
    'set.dev.refuse': 'Ochrona przed przeszukiwaniem (agentwhy refuse) działa z',
    'set.dev.reads': 'Hooki czytają reguły z',
    'set.dev.reads.default': 'wbudowanej listy',
    'set.dev.reads.policy': 'pliku polityki (--policy)',
    'set.dev.reads.other': 'innego pliku ustawień (--settings)',
    'set.dev.rules': 'Reguły plików prywatnych',
    'set.dev.unread': 'Nieczytane reguły projektu',
    'set.dev.exceptions': 'Wyjątki',
    'set.dev.notices': 'Wybory wiadomości zapisane w',
    'set.dev.on': 'Mów od poziomu (--on)',
    'set.dev.clean': 'Gdy nic się nie stało (--clean)',
    'set.dev.said': 'Mówi · pokazywane w',
    'set.dev.none': 'brak',
    'set.dev.notInstalled': 'niezainstalowany',
    'set.dev.unknown': 'nieznane - nie udało się odczytać pliku ustawień projektu',
    'set.state.unknown': 'Nie udało się odczytać',
    'set.shared': 'Ta strona została udostępniona, więc nie pokazuje ustawień komputera, na którym powstała.',
    'set.add.cannot': 'Ta nazwa ma znaki, które działają jak symbole wieloznaczne, więc nie da się jej chronić dokładnie. Zmień nazwę pliku albo poproś programistę, żeby go dodał.',
  },
  de: {
    'set.title': 'Einstellungen · agentwhy',
    'set.eyebrow': 'Einstellungen',
    'set.hero': 'Wir haben sichere Einstellungen für dich gewählt.',
    'set.lead': 'Ändere nur etwas, wenn du es möchtest.',
    'set.cannot': 'Die Einstellungsdatei deines Projekts konnte nicht gelesen werden, daher lässt sich hier nichts ändern. Korrigiere die Datei und öffne diese Seite erneut.',
    'set.tab.alerts': 'Hinweise',
    'set.tab.files': 'Private Dateien',
    'set.tab.general': 'Allgemein',

    'set.alerts.title': 'Wann sollen wir es dir sagen?',
    'set.alerts.lead': 'agentwhy fügt deinem Chat mit Claude Code eine kurze Nachricht hinzu. Auf die erste kommt es an. Die anderen zwei sind optional und funktionieren nur, wenn die erste an ist.',
    'set.alerts.optional': 'Optional — schalte sie ein oder aus, wie du möchtest',
    'set.card.read.name': 'Wenn meine KI eine private Datei liest',
    'set.card.read.badge': 'Standard · empfohlen',
    'set.card.optional': 'Optional',
    'set.card.read.when': 'Damit du die Schlüssel noch am selben Tag ändern kannst, bevor jemand sie nutzt. Du siehst, was zu tun ist.',
    'set.card.read.answer': 'Achtung: Bei der Arbeit habe ich die Passwörter deiner Live-App gelesen. Sieh dir an, was zu tun ist →',
    'set.card.stopped.name': 'Wenn meine KI davon abgehalten wird, eine private Datei zu öffnen',
    'set.card.stopped.when': 'So weißt du, dass die Blockierung gehalten hat: Deine KI wollte eine blockierte Datei öffnen und wurde rechtzeitig gestoppt. Du siehst das nur bei Dateien, die du blockierst.',
    'set.card.stopped.answer': 'Ich wollte deine Passwortdatei öffnen, aber sie ist blockiert — nichts wurde gelesen.',
    'set.card.fine.name': 'Einmal pro Unterhaltung, auch wenn alles gut ist',
    'set.card.fine.when': 'Zur Beruhigung: ein kurzes Zeichen, dass wir aufpassen.',
    'set.card.fine.answer': 'Alles gut — ich habe nichts Privates geöffnet.',
    'set.chat.ai': 'KI',
    'set.state.local': 'An — nur für dich',
    'set.state.shared': 'An — für alle in diesem Projekt',
    'set.state.on': 'An',
    'set.state.off': 'Aus',
    'set.need': 'Schalte zuerst „Wenn meine KI eine private Datei liest“ ein. Diese Option geht nur zusammen damit.',
    'set.need.go': 'Erste einschalten',
    'set.notices.unusable': 'Deine Nachrichten-Einstellungen konnten nicht gelesen werden, daher lassen sie sich hier nicht ändern.',
    'set.general.title': 'Für wen gelten diese Einstellungen?',
    'set.general.lead': 'Deine privaten Dateien und dein Schutz. Wähle, für wen sie gelten.',
    'set.general.local': 'Nur für mich',
    'set.general.local.sub': 'Nur auf diesem Computer. Andere in diesem Projekt bekommen sie nicht.',
    'set.general.shared': 'Für alle in diesem Projekt',
    'set.general.shared.sub': 'Mit dem Projekt gespeichert, damit alle denselben Schutz haben.',
    'set.general.current': 'Aktuell',
    'set.general.you': 'Du',
    'set.general.mixed': '<strong>Einige deiner Einstellungen gelten nur für dich, andere für alle in diesem Projekt.</strong> <span class="set-soft">Wähle eins, und wir verschieben den Rest dorthin.</span>',
    'set.general.none': 'Noch ist nichts gespeichert. Was du einschaltest, gilt nur für dich.',
    'set.general.note': 'Deine Auswahl für Hinweise gilt immer nur für dich.',
    'set.uninstall.title': 'agentwhy deinstallieren',
    'set.uninstall.text': 'Schaltet alles aus und entfernt agentwhy aus diesem Projekt. Deine eigenen Dateien bleiben unberührt.',
    'set.uninstall.go': 'Deinstallieren…',

    'set.unread.one': '<strong>Dein Projekt markiert 1 weitere Datei als privat.</strong> <span class="set-soft">Wir haben sie bisher nicht im Blick gehabt.</span>',
    'set.unread.other': '<strong>Dein Projekt markiert {n} weitere Dateien als privat.</strong> <span class="set-soft">Wir haben sie bisher nicht im Blick gehabt.</span>',
    'set.unwatched': '<strong>Einige Dateien, die wir als privat behandeln, werden noch nicht im Blick behalten.</strong> <span class="set-soft">Dein Projekt hat jetzt eine eigene Liste, und sie stehen nicht darauf.</span>',
    'set.watch.one': 'Auch im Blick behalten',
    'set.watch.other': 'Auch im Blick behalten',
    'set.files.title': 'Was als privat gilt',
    'set.files.lead': 'Wähle für jede, was passiert, wenn Claude Code sie öffnen will.',
    'set.rule.env': 'Passwörter und Schlüssel',
    'set.rule.env.sub': 'Dateien wie .env, die deine App mit anderen Diensten verbinden',
    'set.rule.npmrc': 'Passwörter für App-Installationen',
    'set.rule.npmrc.sub': 'Die Datei .npmrc',
    'set.rule.secrets': 'Geheime Ordner',
    'set.rule.secrets.sub': 'Alles in einem Ordner namens secrets',
    'set.rule.ssh': 'Anmeldeschlüssel für Computer',
    'set.rule.ssh.sub': 'SSH-Schlüssel, mit denen du dich auf Servern anmeldest',
    'set.rule.sub.you': 'Von dir hinzugefügt',
    'set.rule.sub.project': 'Aus deinem Projekt',
    'set.rule.notWatched': 'Noch nicht im Blick',
    'set.rule.watch': 'Im Blick behalten',
    'set.src.agentwhy': 'Von agentwhy hinzugefügt',
    'set.src.project': 'Aus deinem Projekt',
    'set.src.you': 'Von dir hinzugefügt',
    'set.col.src': 'Hinzugefügt von',
    'set.col.act': 'Aktion',
    'set.src.short.agentwhy': 'agentwhy',
    'set.src.short.you': 'Dir',
    'set.src.short.project': 'Deinem Projekt',
    'set.rule.own.file': 'Eine private Datei',
    'set.rule.own.folder': 'Ein privater Ordner',
    'set.rule.own.pattern': 'Private Dateien, die hierzu passen',
    'set.remove': 'Entfernen',
    'set.add': 'Private Datei hinzufügen',
    'set.legend.block': 'Claude Code kann sie nicht öffnen',
    'set.legend.tell': 'sie kann sie lesen, und du erfährst es',
    'set.col.file': 'Datei',
    'set.count.block': '<b class="set-count-n">{n}</b> blockiert',
    'set.count.tell': '<b class="set-count-n">{n}</b> beobachtet',
    'set.finish.gap.one': '<strong>1 private Datei ist nicht ganz blockiert.</strong> <span class="set-soft">Claude Code kann ihren Inhalt noch lesen.</span>',
    'set.finish.gap.other': '<strong>{n} private Dateien sind nicht ganz blockiert.</strong> <span class="set-soft">Claude Code kann ihren Inhalt noch lesen.</span>',
    'set.finish.go': 'Blockieren abschließen',
    'set.finish.title': 'Private Dateien ganz blockieren?',
    'set.finish.text.one': 'Claude Code kann {names} dann weder öffnen noch durchsuchen.',
    'set.finish.text.other': 'Claude Code kann {names} dann weder öffnen noch durchsuchen.',
    'set.finish.yes.one': 'Ja, blockieren',
    'set.finish.yes.other': 'Ja, blockieren',
    'set.finish.honest': 'Das stoppt die offensichtlichen Versuche, nicht jeden Trick. Wenn etwas durchrutscht, siehst du es trotzdem in deinem Bericht.',
    'set.rule.gap.open': 'Nicht ganz blockiert – Claude Code kann den Inhalt noch mit einer Suche oder einem Befehl lesen.',
    'set.rule.gap.none': 'Noch nicht blockiert – Claude Code kann es noch öffnen.',
    'set.codex.off': '<strong>Codex ist noch nicht blockiert.</strong> <span class="set-soft">Es kann die hier blockierten Dateien noch öffnen und durchsuchen.</span>',
    'set.codex.go': 'Auch in Codex blockieren',
    'set.codex.on': 'Codex kommt an dieselben Dateien nicht heran, sobald du agentwhy in Codex freigibst. Bis dahin blockiert Codex nichts.',
    'set.codex.title': 'Diese Dateien auch in Codex blockieren?',
    'set.codex.text': 'Codex kann die hier blockierten Dateien dann weder öffnen noch durchsuchen, sobald du agentwhy in Codex freigibst. Bis dahin blockiert es nichts.',
    'set.codex.yes': 'Ja, in Codex blockieren',
    'set.exceptions.one': '1 Ausnahme — siehe die Details für deine Entwicklerin oder deinen Entwickler.',
    'set.exceptions.other': '{n} Ausnahmen — siehe die Details für deine Entwicklerin oder deinen Entwickler.',


    'set.confirm.alerts.on': 'Hinweise einschalten?',
    'set.confirm.alerts.on.text': 'Du bekommst eine kurze Nachricht im Chat mit Claude Code, wenn es etwas Privates liest.',
    'set.confirm.alerts.off': 'Hinweise ausschalten?',
    'set.confirm.alerts.off.text': 'Du erfährst es nicht sofort. Du siehst trotzdem alles später in deinem Bericht.',
    'set.confirm.turnOn': 'Einschalten',
    'set.confirm.turnOff': 'Ausschalten',
    'set.confirm.scope.local': 'Diese Einstellungen nur für dich?',
    'set.confirm.scope.local.text': 'Wir verschieben deine privaten Dateien, Hinweise und deinen Schutz nur auf diesen Computer. Andere, die an diesem Projekt arbeiten, bekommen sie nicht mehr.',
    'set.confirm.scope.shared': 'Diese Einstellungen für alle in diesem Projekt?',
    'set.confirm.scope.shared.text': 'Wir speichern deine privaten Dateien, Hinweise und deinen Schutz mit dem Projekt. Alle, die daran arbeiten, bekommen sie, wohin das Projekt auch geht.',
    'set.confirm.scope.go': 'Ja, wechseln',
    'set.confirm.uninstall': 'agentwhy aus diesem Projekt deinstallieren?',
    'set.confirm.uninstall.text': 'Wir schalten Hinweise und den Schutz vor Suchen aus und entfernen die privaten Dateien, die agentwhy hinzugefügt hat. Deine KI kann sie wieder öffnen, und du wirst nicht informiert. Deine eigenen Dateien bleiben unberührt.',
    'set.confirm.uninstall.go': 'Ja, deinstallieren',
    'set.confirm.add': 'Diese Datei schützen?',
    'set.confirm.add.file': 'Das schützt jede Datei namens {name} in deinem Projekt.',
    'set.confirm.add.folder': 'Das schützt alles in jedem Ordner namens {name} in deinem Projekt.',
    'set.confirm.add.pattern': 'Das schützt jede Datei, die zu {name} passt, in deinem Projekt.',
    'set.confirm.add.also': 'Claude Code kann sie dann weder öffnen noch durchsuchen.',
    'set.confirm.add.go': 'Ja, schützen',
    'set.confirm.watch': 'Diese auch im Blick behalten?',
    'set.confirm.watch.text': 'Wir behalten die Dateien im Blick, die dein Projekt schon als privat markiert, und Claude Code kann sie weder öffnen noch durchsuchen.',
    'set.confirm.watch.go': 'Ja, im Blick behalten',
    'set.confirm.row': 'Diese Dateien in den Blick nehmen?',
    'set.confirm.row.text': 'Wir behalten {name} im Blick, und Claude Code kann sie weder öffnen noch durchsuchen.',
    'set.confirm.builtIn': 'Die Dateien, die wir schon im Blick behalten, werden mit in dein Projekt geschrieben, damit keine davon herausfällt.',
    'set.confirm.everyone': 'Diese Änderung gilt für alle in diesem Projekt.',
    'set.confirm.remove': 'Nicht mehr schützen?',
    'set.confirm.remove.text': 'Wir behalten {name} nicht mehr im Blick, und deine KI kann es ohne Fragen öffnen.',
    'set.confirm.remove.go': 'Entfernen',
    'set.mode.label': 'Wenn deine KI darauf zugreift',
    'set.mode.block': 'Blockieren',
    'set.mode.tell': 'Beobachten',
    'set.confirm.tell.secret': 'Deine KI deine Passwörter und Schlüssel lesen lassen?',
    'set.confirm.tell.secret.text': 'Deine KI kann dann {name} lesen. Hat sie es einmal gesehen, lässt sich das nicht rückgängig machen. Dann hilft nur, diese Passwörter oder Schlüssel zu ändern. Du bekommst jedes Mal eine Nachricht in Claude Code.',
    'set.confirm.tell': 'Deine KI diese Datei lesen lassen?',
    'set.confirm.tell.text': 'Deine KI kann dann {name} öffnen. Sie liest, was darin steht, und hat dann diese Informationen. Du bekommst jedes Mal eine Nachricht in Claude Code.',
    'set.confirm.tell.alertsOff': 'Hinweise sind aus, also siehst du es nur in deinem Bericht.',
    'set.confirm.tell.go': 'Ja, nur beobachten',
    'set.confirm.block': 'Diese Datei blockieren?',
    'set.confirm.block.text': 'Claude Code kann {name} dann weder öffnen noch durchsuchen.',
    'set.confirm.block.go': 'Ja, blockieren',
    'set.confirm.untell': 'Diese Datei nicht mehr im Blick behalten?',
    'set.confirm.untell.text': '{name} ist dann nicht mehr privat: Deine KI kann sie öffnen, und du wirst nicht informiert.',
    'set.saving': 'Wird gespeichert…',
    'set.refused': 'Das hat nicht geklappt:',
    'set.asFile': 'Diese Seite wurde als Datei geöffnet und kann nichts ändern. Führe dafür das hier in deinem Projekt aus:',
    'set.unreachable': 'Die Seite hat agentwhy start nicht erreicht - vielleicht wurde es beendet. Starte es neu.',

    'set.add.title': 'Private Datei hinzufügen',
    'set.add.lead': 'Wähle sie auf deinem Computer aus. Claude Code kann sie dann nicht öffnen.',
    'set.add.file': 'Datei wählen',
    'set.add.file.eg': 'z. B. vertrag.pdf',
    'set.add.folder': 'Ordner wählen',
    'set.add.folder.eg': 'z. B. daten/',
    'set.add.type': 'Oder gib den Namen ein',
    'set.add.placeholder': 'vertrag.pdf oder daten/',
    'set.add.go': 'Hinzufügen',

    'set.ask.title': 'Unsicher, was du wählen sollst? Frag mich.',
    'set.ask.alerts.1': 'Soll ich Hinweise einschalten?',
    'set.ask.alerts.1.a': 'Ja, für die meisten.\nWenn deine KI etwas Privates liest, erfährst du es im selben Chat, solange du noch handeln kannst.\nNichts wird blockiert. Deine KI arbeitet weiter.',
    'set.ask.alerts.2': 'Was mache ich, wenn ich so eine Nachricht bekomme?',
    'set.ask.alerts.2.a': 'Ändere die Schlüssel in dieser Datei.\nDie Nachricht sagt, welche Datei es war und was zu tun ist.\nDeine KI fragt, ob du den Bericht sehen willst. Er öffnet sich nur, wenn du Ja sagst.',
    'set.ask.alerts.3': 'Wer sieht diese Nachrichten noch?',
    'set.ask.alerts.3.a': 'Nur du und deine KI.\nDie Nachricht erscheint im Chat mit deiner KI, also liest deine KI sie auch - so kann sie es dir sagen.\nSie nennt die Datei, nie ihren Inhalt.\nMit „Für alle in diesem Projekt“ bekommt jede Person dieselben Nachrichten in ihrem eigenen Chat.',
    'set.ask.files.1': 'Was ist eine .env-Datei?',
    'set.ask.files.1.a': 'Eine Datei, in der Apps Passwörter und Schlüssel aufbewahren.\nZum Beispiel den Schlüssel, mit dem deine App Zahlungen annimmt.\nWenn deine KI sie liest, hat sie diese Schlüssel gesehen.',
    'set.ask.files.2': 'Soll ich meine Verträge hinzufügen?',
    'set.ask.files.2.a': 'Ja, wenn darin etwas steht, das du nicht in einen Chat kopieren würdest.\nDas gilt auch für Kundenlisten und Ausweise.\nSobald eine Datei hinzugefügt ist, erfährst du, wenn deine KI sie öffnet.',
    'set.ask.files.3': 'Liest agentwhy meine Dateien?',
    'set.ask.files.3.a': 'Nein.\nagentwhy liest die Aufzeichnung der Unterhaltung, die deine KI selbst führt, auf diesem Computer, um zu sehen, welche Dateien sie geöffnet hat.\nWählst du hier eine Datei, wird nur ihr Name verwendet.',
    'set.ask.general.1': 'Nur ich oder alle?',
    'set.ask.general.1.a': 'Nur für mich, wenn du allein arbeitest.\nFür alle in diesem Projekt, wenn andere mit ihrer eigenen KI daran arbeiten - dann sind sie auch geschützt.\nDu kannst jederzeit wechseln: Nichts geht verloren, und nichts wird ausgeschaltet.',
    'set.ask.general.2': 'Was löscht das Deinstallieren?',
    'set.ask.general.2.a': 'Nur, was agentwhy diesem Projekt hinzugefügt hat: Hinweise, den Schutz vor Suchen und die privaten Dateien, die es schützt.\nRegeln, die dein Projekt von Hand geschrieben hat, bleiben - ebenso deine Dateien und Berichte.\nDeine Auswahl für Hinweise und deine „Beobachten“-Liste bleiben auch, falls du zurückkommst.',
    'set.ask.general.3': 'Kann ich es wieder installieren?',
    'set.ask.general.3.a': 'Ja, jederzeit.\nSchalte Hinweise und Schutz hier wieder ein, oder führe npx @agentwhy/cli init in deinem Projekt aus.\nDateien, die du selbst hinzugefügt hast, musst du erneut hinzufügen.',

    'set.dev': 'Details für deine Entwicklerin oder deinen Entwickler',
    'set.dev.watch': 'Hinweise (agentwhy watch) laufen aus',
    'set.dev.refuse': 'Schutz vor Suchen (agentwhy refuse) läuft aus',
    'set.dev.reads': 'Die Hooks lesen Regeln aus',
    'set.dev.reads.default': 'der eingebauten Liste',
    'set.dev.reads.policy': 'einer Richtliniendatei (--policy)',
    'set.dev.reads.other': 'einer anderen Einstellungsdatei (--settings)',
    'set.dev.rules': 'Regeln für private Dateien',
    'set.dev.unread': 'Nicht gelesene Projektregeln',
    'set.dev.exceptions': 'Ausnahmen',
    'set.dev.notices': 'Nachrichten-Einstellungen gespeichert in',
    'set.dev.on': 'Sag es mir ab (--on)',
    'set.dev.clean': 'Wenn nichts passiert ist (--clean)',
    'set.dev.said': 'Gesagt von · gezeigt in',
    'set.dev.none': 'keine',
    'set.dev.notInstalled': 'nicht installiert',
    'set.dev.unknown': 'unbekannt - die Einstellungsdatei des Projekts konnte nicht gelesen werden',
    'set.state.unknown': 'Konnte nicht gelesen werden',
    'set.shared': 'Diese Seite wurde geteilt und zeigt daher keine Einstellungen des Computers, auf dem sie entstand.',
    'set.add.cannot': 'Dieser Name enthält Zeichen, die als Platzhalter wirken, daher lässt er sich nicht genau schützen. Benenne die Datei um oder bitte deine Entwicklerin oder deinen Entwickler, sie hinzuzufügen.',
  },
};
