// Copyright 2026 Nessprim Karol Kozer
// SPDX-License-Identifier: Apache-2.0
import type { Lang, Table } from '../../report-copy.ts';

/**
 * The words of the To fix page (`.ai/specs/2026-09-23-to-fix.md`), in the glossary of the design guidelines §7. The
 * developer details keep the tool's own words (T16). A file's name in words is Settings' (`set.rule.*`, T6).
 */
export const TO_FIX_WORDS: Readonly<Record<Lang, Table>> = {
  en: {
    'fix.title': 'To fix · agentwhy',
    'fix.range': 'Last {range} · {dates}',
    'fix.range.since': 'Since {dates}',
    'fix.span.h.one': 'hour', 'fix.span.h.other': '{n} hours',
    'fix.span.d.one': 'day', 'fix.span.d.other': '{n} days',
    'fix.span.w.one': 'week', 'fix.span.w.other': '{n} weeks',
    'fix.hero.count.one': '1 file to fix.',
    'fix.hero.count.other': '{n} files to fix.',
    'fix.hero.none': 'Nothing left to fix.',
    'fix.hero.keys.one': 'Start with the 1 with real keys.',
    'fix.hero.keys.other': 'Start with the {n} with real keys.',
    'fix.hero.look': 'Just a quick look left.',
    'fix.hero.nice': 'Nice work.',
    'fix.lead': 'Your AI saw what’s inside these files. Change the keys in them, then tick them off here.',
    'fix.tab.todo': 'To fix',
    'fix.tab.done': 'Done',
    'fix.stopped.one': 'Your protection worked: 1 try was stopped.',
    'fix.stopped.other': 'Your protection worked: {n} tries were stopped.',
    'fix.marksUnreadable': 'Your record of what you fixed couldn’t be read, so nothing was left off this list because of it.',
    'fix.keys': 'Change these keys',
    'fix.keys.lead': 'Your AI read the real keys inside. Make new ones.',
    'fix.keys.go': 'Fix it →',
    'fix.look': 'Take a quick look',
    'fix.look.lead': 'These are sample files. If they hold real keys, change them. If not, tick them off.',
    'fix.look.go': 'Check it',
    'fix.back': 'Back again',
    'fix.in.one': 'in 1 conversation',
    'fix.in.other': 'in {n} conversations',
    'fix.private': 'A private file',
    'fix.seen.one': '<strong>1 file — nothing to do.</strong> <span class="tf-soft">Your AI only saw its name, never what’s inside.</span>',
    'fix.seen.other': '<strong>{n} files — nothing to do.</strong> <span class="tf-soft">Your AI only saw their names, never what’s inside.</span>',
    'fix.seen.label': 'Only saw the name',
    'fix.empty': 'Your AI didn’t read anything private that is still to fix.',
    'fix.done.lead': 'If your AI reads one of these again, it comes back to your list.',
    'fix.done.none': 'Nothing marked yet. When you fix a file, it shows up here.',
    'fix.done.fixed': '✓ Fixed {when}',
    'fix.done.undo': 'Undo',
    'fix.undo.title': 'Put this back on your list?',
    'fix.undo.text': 'It goes back to To fix, as if you had never ticked it off.',
    'fix.undo.go': 'Put it back',
    'fix.today': 'today',
    'fix.yesterday': 'yesterday',
    'fix.day.today': 'Today',
    'fix.day.yesterday': 'Yesterday',
    'fix.window.back': '<strong>It’s back.</strong> You marked it fixed on {day}. After that, your AI read it again.',
    'fix.window.todo': 'What to do',
    'fix.window.note': 'Note for yourself (optional)',
    'fix.window.notePlaceholder': 'e.g. new keys made in Stripe',
    'fix.happened.did': 'What your AI did',
    'fix.happened.keys': 'It opened this file and read the keys inside. The old keys still work until you change them.',
    'fix.happened.look': 'It opened this sample file and read what’s inside. If it holds real keys, they still work.',
    'fix.happened.unknown': 'It reached for this file, but the record doesn’t say what came back.',
    'fix.happened.todo.keys': 'Make new keys, so the ones your AI saw stop working. Fix it shows you how, one step at a time.',
    'fix.happened.todo.look': 'Look inside. If you see real keys, change them. Check it shows you how.',
    'fix.happened.todo.unknown': 'Look inside. If you see real keys, change them. Check it shows you how.',
    'fix.skip.handled': 'I checked it, nothing to change',
    'fix.story.from': 'From your newest conversation that read it: {title} · {day}, {time}.',
    'fix.story.more.one': 'It was read in 1 more - see Conversations.',
    'fix.story.more.other': 'It was read in {n} more - see Conversations.',
    'fix.story.tab': 'Conversations',
    'fix.window.after': 'If your AI reads it again later, it comes back to your list.',
    'fix.window.where': 'Where your AI read it',
    'fix.window.see': 'See report',
    'fix.window.noReport': 'No report',
    'fix.window.untitled': 'A conversation with no title',
    'fix.window.all': 'Show all {n}',
    'fix.window.gone.one': '1 more is older than this run.',
    'fix.window.gone.other': '{n} more are older than this run.',
    'fix.saving': 'Saving…',
    'fix.refused': 'That didn’t work:',
    'fix.asFile': 'This page was opened as a file, so it can’t change anything. To do it, run this in your project:',
    'fix.unreachable': 'The page could not reach agentwhy start - it may have stopped. Run it again.',
    'fix.dev': 'Details for your developer',
    'fix.dev.lead': 'What agentwhy check says about each file, and in which conversations. A conversation is named by its id - the name of its transcript file - cut to 8 characters. No key or password is shown here.',
    'fix.dev.lead.shared': 'What agentwhy check says about each file, and in which conversations, numbered as in the list. No key or password is shown here.',
    'fix.dev.col.says': 'What check says',
    'fix.dev.col.file': 'File',
    'fix.dev.col.in': 'Conversations',
    'fix.dev.means.rotate': 'contents read',
    'fix.dev.means.template': 'template contents read',
    'fix.dev.means.unknown': 'outcome not recorded',
    'fix.dev.means.route': 'a call opened it and nothing refused it',
    'fix.dev.means.result': 'name in command output only',
    'fix.dev.count.one': '1 conversation',
    'fix.dev.count.other': '{n} conversations',
    'fix.dev.lines': 'Lines',
    'fix.dev.commands': 'Commands',
    'fix.dev.cmd.full': 'Every line, with its paths and what to do about them',
    'fix.dev.cmd.mark': 'Mark a file fixed once its keys are changed',
  },
  pl: {
    'fix.title': 'Do naprawy · agentwhy',
    'fix.range': 'Ostatnie {range} · {dates}',
    'fix.range.since': 'Od {dates}',
    'fix.span.h.one': 'godzina', 'fix.span.h.few': '{n} godziny', 'fix.span.h.many': '{n} godzin',
    'fix.span.d.one': 'dzień', 'fix.span.d.few': '{n} dni', 'fix.span.d.many': '{n} dni',
    'fix.span.w.one': 'tydzień', 'fix.span.w.few': '{n} tygodnie', 'fix.span.w.many': '{n} tygodni',
    'fix.hero.count.one': '1 plik do naprawy.',
    'fix.hero.count.few': '{n} pliki do naprawy.',
    'fix.hero.count.many': '{n} plików do naprawy.',
    'fix.hero.none': 'Nie ma nic do naprawy.',
    'fix.hero.keys.one': 'Zacznij od 1 z prawdziwymi kluczami.',
    'fix.hero.keys.few': 'Zacznij od {n} z prawdziwymi kluczami.',
    'fix.hero.keys.many': 'Zacznij od {n} z prawdziwymi kluczami.',
    'fix.hero.look': 'Zostało tylko szybkie sprawdzenie.',
    'fix.hero.nice': 'Dobra robota.',
    'fix.lead': 'Twoje AI widziało zawartość tych plików. Zmień w nich klucze, a potem odhacz je tutaj.',
    'fix.tab.todo': 'Do naprawy',
    'fix.tab.done': 'Zrobione',
    'fix.stopped.one': 'Twoja ochrona zadziałała: zatrzymano 1 próbę.',
    'fix.stopped.few': 'Twoja ochrona zadziałała: zatrzymano {n} próby.',
    'fix.stopped.many': 'Twoja ochrona zadziałała: zatrzymano {n} prób.',
    'fix.marksUnreadable': 'Nie udało się odczytać zapisu tego, co naprawiłeś, więc nic nie zostało przez to pominięte na tej liście.',
    'fix.keys': 'Zmień te klucze',
    'fix.keys.lead': 'Twoje AI przeczytało prawdziwe klucze w środku. Zrób nowe.',
    'fix.keys.go': 'Napraw →',
    'fix.look': 'Rzuć okiem',
    'fix.look.lead': 'To pliki przykładowe. Jeśli są w nich prawdziwe klucze, zmień je. Jeśli nie, odhacz je.',
    'fix.look.go': 'Sprawdź',
    'fix.back': 'Wrócił',
    'fix.in.one': 'w 1 rozmowie',
    'fix.in.few': 'w {n} rozmowach',
    'fix.in.many': 'w {n} rozmowach',
    'fix.private': 'Prywatny plik',
    'fix.seen.one': '<strong>1 plik — nic do zrobienia.</strong> <span class="tf-soft">Twoje AI widziało tylko jego nazwę, nigdy zawartość.</span>',
    'fix.seen.few': '<strong>{n} pliki — nic do zrobienia.</strong> <span class="tf-soft">Twoje AI widziało tylko ich nazwy, nigdy zawartość.</span>',
    'fix.seen.many': '<strong>{n} plików — nic do zrobienia.</strong> <span class="tf-soft">Twoje AI widziało tylko ich nazwy, nigdy zawartość.</span>',
    'fix.seen.label': 'Widziało tylko nazwę',
    'fix.empty': 'Twoje AI nie przeczytało niczego prywatnego, co wciąż trzeba naprawić.',
    'fix.done.lead': 'Jeśli twoje AI znów przeczyta któryś z nich, wróci on na twoją listę.',
    'fix.done.none': 'Nic jeszcze nie oznaczono. Gdy naprawisz plik, pojawi się tutaj.',
    'fix.done.fixed': '✓ Naprawione {when}',
    'fix.done.undo': 'Cofnij',
    'fix.undo.title': 'Przywrócić to na listę?',
    'fix.undo.text': 'Wróci do „Do naprawy”, jakbyś go nigdy nie odhaczył.',
    'fix.undo.go': 'Przywróć',
    'fix.today': 'dziś',
    'fix.yesterday': 'wczoraj',
    'fix.day.today': 'Dziś',
    'fix.day.yesterday': 'Wczoraj',
    'fix.window.back': '<strong>Wrócił.</strong> Oznaczyłeś go jako naprawiony {day}. Potem twoje AI znów go przeczytało.',
    'fix.window.todo': 'Co zrobić',
    'fix.window.note': 'Notatka dla siebie (opcjonalnie)',
    'fix.window.notePlaceholder': 'np. nowe klucze zrobione w Stripe',
    'fix.happened.did': 'Co zrobiło twoje AI',
    'fix.happened.keys': 'Otworzyło ten plik i przeczytało klucze w środku. Stare klucze działają, dopóki ich nie zmienisz.',
    'fix.happened.look': 'Otworzyło ten plik przykładowy i przeczytało, co w nim jest. Jeśli są w nim prawdziwe klucze, nadal działają.',
    'fix.happened.unknown': 'Sięgnęło po ten plik, ale zapis nie mówi, co wróciło.',
    'fix.happened.todo.keys': 'Zrób nowe klucze, żeby te, które widziało AI, przestały działać. „Napraw” pokaże ci jak, krok po kroku.',
    'fix.happened.todo.look': 'Zajrzyj do środka. Jeśli widzisz prawdziwe klucze, zmień je. „Sprawdź” pokaże ci jak.',
    'fix.happened.todo.unknown': 'Zajrzyj do środka. Jeśli widzisz prawdziwe klucze, zmień je. „Sprawdź” pokaże ci jak.',
    'fix.skip.handled': 'Sprawdzone, nic do zmiany',
    'fix.story.from': 'Z najnowszej rozmowy, w której AI go przeczytało: {title} · {day}, {time}.',
    'fix.story.more.one': 'Przeczytało go jeszcze w 1 rozmowie - zobacz Rozmowy.',
    'fix.story.more.few': 'Przeczytało go jeszcze w {n} rozmowach - zobacz Rozmowy.',
    'fix.story.more.many': 'Przeczytało go jeszcze w {n} rozmowach - zobacz Rozmowy.',
    'fix.story.tab': 'Rozmowy',
    'fix.window.after': 'Jeśli twoje AI przeczyta go później znowu, wróci na twoją listę.',
    'fix.window.where': 'Gdzie twoje AI go przeczytało',
    'fix.window.see': 'Zobacz raport',
    'fix.window.noReport': 'Brak raportu',
    'fix.window.untitled': 'Rozmowa bez tytułu',
    'fix.window.all': 'Pokaż wszystkie ({n})',
    'fix.window.gone.one': 'Jeszcze 1 jest starsza niż ten przebieg.',
    'fix.window.gone.few': 'Jeszcze {n} są starsze niż ten przebieg.',
    'fix.window.gone.many': 'Jeszcze {n} jest starszych niż ten przebieg.',
    'fix.saving': 'Zapisuję…',
    'fix.refused': 'Nie udało się:',
    'fix.asFile': 'Ta strona została otwarta jako plik, więc niczego nie zmieni. Żeby to zrobić, uruchom w swoim projekcie:',
    'fix.unreachable': 'Strona nie mogła połączyć się z agentwhy start - mógł się zatrzymać. Uruchom go ponownie.',
    'fix.dev': 'Szczegóły dla twojego programisty',
    'fix.dev.lead': 'Co agentwhy check mówi o każdym pliku i w których rozmowach. Rozmowę nazywa jej identyfikator - nazwa pliku z jej zapisem - skrócony do 8 znaków. Nie ma tu żadnego klucza ani hasła.',
    'fix.dev.lead.shared': 'Co agentwhy check mówi o każdym pliku i w których rozmowach, ponumerowanych jak na liście. Nie ma tu żadnego klucza ani hasła.',
    'fix.dev.col.says': 'Co mówi check',
    'fix.dev.col.file': 'Plik',
    'fix.dev.col.in': 'Rozmowy',
    'fix.dev.means.rotate': 'odczytano zawartość',
    'fix.dev.means.template': 'odczytano zawartość szablonu',
    'fix.dev.means.unknown': 'wynik nie został zapisany',
    'fix.dev.means.route': 'wywołanie go otworzyło i nic tego nie zatrzymało',
    'fix.dev.means.result': 'tylko nazwa w wyniku polecenia',
    'fix.dev.count.one': '1 rozmowa',
    'fix.dev.count.few': '{n} rozmowy',
    'fix.dev.count.many': '{n} rozmów',
    'fix.dev.lines': 'Wiersze',
    'fix.dev.commands': 'Polecenia',
    'fix.dev.cmd.full': 'Każdy wiersz, z jego ścieżkami i tym, co z nimi zrobić',
    'fix.dev.cmd.mark': 'Oznacz plik jako naprawiony, gdy klucze są już zmienione',
  },
  de: {
    'fix.title': 'Zu beheben · agentwhy',
    'fix.range': 'Letzte {range} · {dates}',
    'fix.range.since': 'Seit {dates}',
    'fix.span.h.one': 'Stunde', 'fix.span.h.other': '{n} Stunden',
    'fix.span.d.one': 'Tag', 'fix.span.d.other': '{n} Tage',
    'fix.span.w.one': 'Woche', 'fix.span.w.other': '{n} Wochen',
    'fix.hero.count.one': '1 Datei zu beheben.',
    'fix.hero.count.other': '{n} Dateien zu beheben.',
    'fix.hero.none': 'Nichts mehr zu beheben.',
    'fix.hero.keys.one': 'Fang mit der 1 mit echten Schlüsseln an.',
    'fix.hero.keys.other': 'Fang mit den {n} mit echten Schlüsseln an.',
    'fix.hero.look': 'Nur noch ein kurzer Blick.',
    'fix.hero.nice': 'Gut gemacht.',
    'fix.lead': 'Deine KI hat gesehen, was in diesen Dateien steht. Ändere die Schlüssel darin und hake sie dann hier ab.',
    'fix.tab.todo': 'Zu beheben',
    'fix.tab.done': 'Erledigt',
    'fix.stopped.one': 'Dein Schutz hat gewirkt: 1 Versuch wurde gestoppt.',
    'fix.stopped.other': 'Dein Schutz hat gewirkt: {n} Versuche wurden gestoppt.',
    'fix.marksUnreadable': 'Deine Aufzeichnung des Erledigten konnte nicht gelesen werden, daher wurde deshalb nichts von dieser Liste weggelassen.',
    'fix.keys': 'Diese Schlüssel ändern',
    'fix.keys.lead': 'Deine KI hat die echten Schlüssel darin gelesen. Erstelle neue.',
    'fix.keys.go': 'Beheben →',
    'fix.look': 'Kurz ansehen',
    'fix.look.lead': 'Das sind Beispieldateien. Wenn echte Schlüssel darin stehen, ändere sie. Wenn nicht, hake sie ab.',
    'fix.look.go': 'Ansehen',
    'fix.back': 'Wieder da',
    'fix.in.one': 'in 1 Unterhaltung',
    'fix.in.other': 'in {n} Unterhaltungen',
    'fix.private': 'Eine private Datei',
    'fix.seen.one': '<strong>1 Datei — nichts zu tun.</strong> <span class="tf-soft">Deine KI hat nur ihren Namen gesehen, nie den Inhalt.</span>',
    'fix.seen.other': '<strong>{n} Dateien — nichts zu tun.</strong> <span class="tf-soft">Deine KI hat nur ihre Namen gesehen, nie den Inhalt.</span>',
    'fix.seen.label': 'Nur den Namen gesehen',
    'fix.empty': 'Deine KI hat nichts Privates gelesen, das noch zu beheben ist.',
    'fix.done.lead': 'Wenn deine KI eine davon wieder liest, kommt sie zurück auf deine Liste.',
    'fix.done.none': 'Noch nichts erledigt. Wenn du eine Datei behebst, erscheint sie hier.',
    'fix.done.fixed': '✓ Behoben {when}',
    'fix.done.undo': 'Rückgängig',
    'fix.undo.title': 'Wieder auf die Liste setzen?',
    'fix.undo.text': 'Sie kommt zurück zu „Zu beheben“, als hättest du sie nie abgehakt.',
    'fix.undo.go': 'Zurücksetzen',
    'fix.today': 'heute',
    'fix.yesterday': 'gestern',
    'fix.day.today': 'Heute',
    'fix.day.yesterday': 'Gestern',
    'fix.window.back': '<strong>Sie ist wieder da.</strong> Du hast sie am {day} als behoben markiert. Danach hat deine KI sie wieder gelesen.',
    'fix.window.todo': 'Was zu tun ist',
    'fix.window.note': 'Notiz für dich (optional)',
    'fix.window.notePlaceholder': 'z. B. neue Schlüssel in Stripe erstellt',
    'fix.happened.did': 'Was deine KI getan hat',
    'fix.happened.keys': 'Sie hat diese Datei geöffnet und die Schlüssel darin gelesen. Die alten Schlüssel funktionieren, bis du sie änderst.',
    'fix.happened.look': 'Sie hat diese Beispieldatei geöffnet und gelesen, was darin steht. Wenn echte Schlüssel darin sind, funktionieren sie noch.',
    'fix.happened.unknown': 'Sie hat nach dieser Datei gegriffen, aber die Aufzeichnung sagt nicht, was zurückkam.',
    'fix.happened.todo.keys': 'Erstelle neue Schlüssel, damit die, die deine KI gesehen hat, nicht mehr funktionieren. „Beheben“ zeigt dir, wie, Schritt für Schritt.',
    'fix.happened.todo.look': 'Sieh hinein. Wenn du echte Schlüssel siehst, ändere sie. „Ansehen“ zeigt dir, wie.',
    'fix.happened.todo.unknown': 'Sieh hinein. Wenn du echte Schlüssel siehst, ändere sie. „Ansehen“ zeigt dir, wie.',
    'fix.skip.handled': 'Geprüft, nichts zu ändern',
    'fix.story.from': 'Aus deiner neuesten Unterhaltung, in der sie gelesen wurde: {title} · {day}, {time}.',
    'fix.story.more.one': 'Sie wurde in 1 weiteren gelesen - siehe Unterhaltungen.',
    'fix.story.more.other': 'Sie wurde in {n} weiteren gelesen - siehe Unterhaltungen.',
    'fix.story.tab': 'Unterhaltungen',
    'fix.window.after': 'Wenn deine KI sie später wieder liest, kommt sie zurück auf deine Liste.',
    'fix.window.where': 'Wo deine KI sie gelesen hat',
    'fix.window.see': 'Bericht ansehen',
    'fix.window.noReport': 'Kein Bericht',
    'fix.window.untitled': 'Eine Unterhaltung ohne Titel',
    'fix.window.all': 'Alle {n} zeigen',
    'fix.window.gone.one': '1 weitere ist älter als dieser Lauf.',
    'fix.window.gone.other': '{n} weitere sind älter als dieser Lauf.',
    'fix.saving': 'Wird gespeichert…',
    'fix.refused': 'Das hat nicht geklappt:',
    'fix.asFile': 'Diese Seite wurde als Datei geöffnet und kann nichts ändern. Führe dafür das hier in deinem Projekt aus:',
    'fix.unreachable': 'Die Seite hat agentwhy start nicht erreicht - vielleicht wurde es beendet. Starte es neu.',
    'fix.dev': 'Details für deine Entwicklerin oder deinen Entwickler',
    'fix.dev.lead': 'Was agentwhy check zu jeder Datei sagt, und in welchen Unterhaltungen. Eine Unterhaltung heißt nach ihrer ID - dem Namen ihrer Protokolldatei -, gekürzt auf 8 Zeichen. Hier steht kein Schlüssel und kein Passwort.',
    'fix.dev.lead.shared': 'Was agentwhy check zu jeder Datei sagt, und in welchen Unterhaltungen, nummeriert wie in der Liste. Hier steht kein Schlüssel und kein Passwort.',
    'fix.dev.col.says': 'Was check sagt',
    'fix.dev.col.file': 'Datei',
    'fix.dev.col.in': 'Unterhaltungen',
    'fix.dev.means.rotate': 'Inhalt gelesen',
    'fix.dev.means.template': 'Inhalt einer Vorlage gelesen',
    'fix.dev.means.unknown': 'Ergebnis nicht aufgezeichnet',
    'fix.dev.means.route': 'ein Aufruf hat sie geöffnet, nichts hat es verhindert',
    'fix.dev.means.result': 'nur der Name in einer Befehlsausgabe',
    'fix.dev.count.one': '1 Unterhaltung',
    'fix.dev.count.other': '{n} Unterhaltungen',
    'fix.dev.lines': 'Zeilen',
    'fix.dev.commands': 'Befehle',
    'fix.dev.cmd.full': 'Jede Zeile, mit ihren Pfaden und was zu tun ist',
    'fix.dev.cmd.mark': 'Eine Datei als behoben markieren, sobald ihre Schlüssel geändert sind',
  },
};
